using System;

namespace model
{
    /// <summary>
    /// U8客户档案
    /// </summary>
    public class CustomerModel
    {
        public string cCusCode { get; set; }
        public string cCusName { get; set; }
        public string cCusAbbName { get; set; }
        public string cCCCode { get; set; }
        public string cDCCode { get; set; }
        public string cTrade { get; set; }
        public string cCusAddress { get; set; }
        public string cCusPostCode { get; set; }
        public string cCusRegCode { get; set; }
        public string cCusBank { get; set; }
        public string cCusAccount { get; set; }
        public string dCusDevDate { get; set; }
        public string cCusLPerson { get; set; }
        public string cCusEmail { get; set; }
        public string cCusPerson { get; set; }
        public string cCusPhone { get; set; }
        public string cCusFax { get; set; }
        public string cCusBP { get; set; }
        public string cCusHand { get; set; }
        public string cCusPPerson { get; set; }
        public string iCusDisRate { get; set; }
        public string cCusCreGrade { get; set; }
        public string iCusCreLine { get; set; }
        public string iCusCreDate { get; set; }
        public string cCusPayCond { get; set; }
        public string cCusOAddress { get; set; }
        public string cCusOType { get; set; }
        public string cCusHeadCode { get; set; }
        public string cCusWhCode { get; set; }
        public string cCusDepart { get; set; }
        public string iARMoney { get; set; }
        public string dLastDate { get; set; }
        public string iLastMoney { get; set; }
        public string dLRDate { get; set; }
        public string iLRMoney { get; set; }
        public string dEndDate { get; set; }
        public string iFrequency { get; set; }
        public string cCusDefine1 { get; set; }
        public string cCusDefine2 { get; set; }
        public string cCusDefine3 { get; set; }
        public string iCostGrade { get; set; }
        public string cCreatePerson { get; set; }
        public string cModifyPerson { get; set; }
        public string dModifyDate { get; set; }
        public string cRelVendor { get; set; }
        public string iId { get; set; }
        public string cPriceGroup { get; set; }
        public string cOfferGrade { get; set; }
        public string iOfferRate { get; set; }
        public string cCusDefine4 { get; set; }
        public string cCusDefine5 { get; set; }
        public string cCusDefine6 { get; set; }
        public string cCusDefine7 { get; set; }
        public string cCusDefine8 { get; set; }
        public string cCusDefine9 { get; set; }
        public string cCusDefine10 { get; set; }
        public string cCusDefine11 { get; set; }
        public string cCusDefine12 { get; set; }
        public string cCusDefine13 { get; set; }
        public string cCusDefine14 { get; set; }
        public string cCusDefine15 { get; set; }
        public string cCusDefine16 { get; set; }
        public string pubufts { get; set; }
        public string cInvoiceCompany { get; set; }
        public string bCredit { get; set; }
        public string bCreditDate { get; set; }
        public string bCreditByHead { get; set; }
        public string bLicenceDate { get; set; }
        public string dLicenceSDate { get; set; }
        public string dLicenceEDate { get; set; }
        public string iLicenceADays { get; set; }
        public string bBusinessDate { get; set; }
        public string dBusinessSDate { get; set; }
        public string dBusinessEDate { get; set; }
        public string iBusinessADays { get; set; }
        public string bProxy { get; set; }
        public string dProxySDate { get; set; }
        public string dProxyEDate { get; set; }
        public string iProxyADays { get; set; }
        public string cMemo { get; set; }
        public string bLimitSale { get; set; }
        public string cCusContactCode { get; set; }
        public string cCusCountryCode { get; set; }
        public string cCusEnName { get; set; }
        public string cCusEnAddr1 { get; set; }
        public string cCusEnAddr2 { get; set; }
        public string cCusEnAddr3 { get; set; }
        public string cCusEnAddr4 { get; set; }
        public string cCusPortCode { get; set; }
        public string cPrimaryVen { get; set; }
        public string fCommisionRate { get; set; }
        public string fInsueRate { get; set; }
        public string bHomeBranch { get; set; }
        public string cBranchAddr { get; set; }
        public string cBranchPhone { get; set; }
        public string cBranchPerson { get; set; }
        public string cCusTradeCCode { get; set; }
        public string CustomerKCode { get; set; }
        public string bCusState { get; set; }
        public string bShop { get; set; }
        public string cCusBankCode { get; set; }
        public string cCusExch_name { get; set; }
        public string iCusGSPType { get; set; }
        public string iCusGSPAuth { get; set; }
        public string cCusGSPAuthNo { get; set; }
        public string cCusBusinessNo { get; set; }
        public string cCusLicenceNo { get; set; }
        public string bCusDomestic { get; set; }
        public string bCusOverseas { get; set; }
        public string cCusCreditCompany { get; set; }
        public string cCusSAProtocol { get; set; }
        public string cCusExProtocol { get; set; }
        public string cCusOtherProtocol { get; set; }
        public string fCusDiscountRate { get; set; }
        public string cCusSSCode { get; set; }
        public string cCusCMProtocol { get; set; }
        public string dCusCreateDatetime { get; set; }
        public string cCusAppDocNo { get; set; }
        public string cCusMnemCode { get; set; }
        public string fAdvancePaymentRatio { get; set; }
        public string bServiceAttribute { get; set; }
        public string bRequestSign { get; set; }
        public string bOnGPinStore { get; set; }
        public string cCusMngTypeCode { get; set; }
        public string account_type { get; set; }
        public string cCusImAgentProtocol { get; set; }
        public string iSourceType { get; set; }
        public string iSourceId { get; set; }
        public string fExpense { get; set; }
        public string fApprovedExpense { get; set; }
        public string dTouchedTime { get; set; }
        public string dRecentlyInvoiceTime { get; set; }
        public string dRecentlyQuoteTime { get; set; }
        public string dRecentlyActivityTime { get; set; }
        public string dRecentlyChanceTime { get; set; }
        public string dRecentlyContractTime { get; set; }
        public string cLtcCustomerCode { get; set; }
        public string bTransFlag { get; set; }
        public string cLtcPerson { get; set; }
        public string dLtcDate { get; set; }
        public string cLocationSite { get; set; }
        public string iCusTaxRate { get; set; }
        public string alloct_dept_time { get; set; }
        public string allot_user_time { get; set; }
        public string recyle_dept_time { get; set; }
        public string recyle_pub_time { get; set; }
        public string cLicenceNo { get; set; }
        public string cLicenceRange { get; set; }
        public string cCusBusinessRange { get; set; }
        public string cCusGSPAuthRange { get; set; }
        public string dCusGSPEDate { get; set; }
        public string dCusGSPSDate { get; set; }
        public string iCusGSPADays { get; set; }
        public string bIsCusAttachFile { get; set; }
        public string dRecentContractDate { get; set; }
        public string dRecentDeliveryDate { get; set; }
        public string dRecentOutboundDate { get; set; }

    }
}
