//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_AuthLevel
    {
        public string cKey { get; set; }
        public string cItem { get; set; }
        public Nullable<double> FLevel1 { get; set; }
        public Nullable<double> FLevel2 { get; set; }
        public Nullable<double> FLevel3 { get; set; }
        public Nullable<double> FLevel4 { get; set; }
        public Nullable<double> FLevel5 { get; set; }
        public Nullable<double> FLevel6 { get; set; }
        public byte[] pubufts { get; set; }
        public short iYear { get; set; }
    }
}
