//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_BatchProperty_Log
    {
        public long HistoryId { get; set; }
        public Nullable<byte> VariationAction { get; set; }
        public Nullable<long> VariationLogId { get; set; }
        public bool bDeletedRst { get; set; }
        public System.DateTime dLogTime { get; set; }
        public System.Guid cBatchPropertyGUID { get; set; }
        public string cInvCode_cBatch_FreeXX { get; set; }
        public string cInvCode { get; set; }
        public string cBatch { get; set; }
        public string cFree1 { get; set; }
        public string cFree2 { get; set; }
        public string cFree3 { get; set; }
        public string cFree4 { get; set; }
        public string cFree5 { get; set; }
        public string cFree6 { get; set; }
        public string cFree7 { get; set; }
        public string cFree8 { get; set; }
        public string cFree9 { get; set; }
        public string cFree10 { get; set; }
        public Nullable<decimal> cBatchProperty1 { get; set; }
        public Nullable<decimal> cBatchProperty2 { get; set; }
        public Nullable<decimal> cBatchProperty3 { get; set; }
        public Nullable<decimal> cBatchProperty4 { get; set; }
        public Nullable<decimal> cBatchProperty5 { get; set; }
        public string cBatchProperty6 { get; set; }
        public string cBatchProperty7 { get; set; }
        public string cBatchProperty8 { get; set; }
        public string cBatchProperty9 { get; set; }
        public Nullable<System.DateTime> cBatchProperty10 { get; set; }
    }
}
