//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ap_MidExch
    {
        public int Auto_ID { get; set; }
        public string cMidExch { get; set; }
        public string cExchName { get; set; }
        public double iMidExchRate { get; set; }
        public double iExchRate { get; set; }
        public decimal iError { get; set; }
    }
}
