//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ap_Note_Sub
    {
        public string cLink { get; set; }
        public string cProcStyle { get; set; }
        public System.DateTime dDate { get; set; }
        public Nullable<decimal> iIntrest { get; set; }
        public Nullable<decimal> iExpense { get; set; }
        public Nullable<decimal> iAmount { get; set; }
        public string cBank { get; set; }
        public Nullable<float> iDisctIntrest { get; set; }
        public string cCode { get; set; }
        public string cOperator { get; set; }
        public string cCancelNo { get; set; }
        public string cCoVouchType { get; set; }
        public string cCoVouchID { get; set; }
        public string cPzID { get; set; }
        public string cFlag { get; set; }
        public int ID { get; set; }
        public Nullable<byte> iBsType { get; set; }
        public Nullable<System.DateTime> dHideDate { get; set; }
        public string cTrustReceiver { get; set; }
        public Nullable<decimal> iAmount_Local { get; set; }
        public Nullable<decimal> iIntrest_Local { get; set; }
        public Nullable<decimal> iExpense_Local { get; set; }
        public Nullable<decimal> iOverAmount { get; set; }
        public Nullable<double> nfrat { get; set; }
    }
}
