//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ap_XjDetail
    {
        public string cCancelNo { get; set; }
        public string cVouchType { get; set; }
        public string cVouchId { get; set; }
        public System.DateTime dVouchDate { get; set; }
        public string cDwCode { get; set; }
        public string cexch_name { get; set; }
        public decimal iAmount { get; set; }
        public decimal iAmount_f { get; set; }
        public Nullable<double> iAmount_s { get; set; }
        public string cCoVouchType { get; set; }
        public string cCoVouchId { get; set; }
        public string cOrderNo { get; set; }
        public string cInvCode { get; set; }
        public Nullable<int> ibvid { get; set; }
        public int iSOsID { get; set; }
        public string cFlag { get; set; }
        public Nullable<System.Guid> BalancesGuid { get; set; }
        public string cDLCode { get; set; }
        public Nullable<int> idlsid { get; set; }
    }
}
