//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyCustomersNo_E006
    {
        public string ApplyCustomersNo_E006_F000 { get; set; }
        public string ApplyCustomersNo_E006_F000_UAPRuntime_FileID { get; set; }
        public int ApplyCustomersNo_E006_PK { get; set; }
        public Nullable<System.Guid> AA_ApplyCustomers_PK { get; set; }
        public Nullable<System.Guid> AA_ApplyCustomersMain_PK { get; set; }
        public Nullable<int> UAPRuntime_RowNO { get; set; }
        public string UAP_VoucherTransform_Rowkey { get; set; }
    }
}
