//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoSetFieldInf
    {
        public int AutoID { get; set; }
        public string CTableCode { get; set; }
        public string CfieldEName { get; set; }
        public string CfieldCName { get; set; }
        public string cFieldType { get; set; }
        public int CFieldLen { get; set; }
        public Nullable<int> cFieldDecLen { get; set; }
        public string cFieldDefault { get; set; }
        public string isDefined { get; set; }
        public string isUsed { get; set; }
        public string cArchiveName { get; set; }
        public string cArchiveField { get; set; }
    }
}
