//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bas_part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bas_part()
        {
            this.SQ_BOMCOMP = new HashSet<SQ_BOMCOMP>();
            this.SQ_BOMPARENT = new HashSet<SQ_BOMPARENT>();
        }
    
        public int PartId { get; set; }
        public string InvCode { get; set; }
        public string Free1 { get; set; }
        public string Free2 { get; set; }
        public string Free3 { get; set; }
        public string Free4 { get; set; }
        public string Free5 { get; set; }
        public string Free6 { get; set; }
        public string Free7 { get; set; }
        public string Free8 { get; set; }
        public string Free9 { get; set; }
        public string Free10 { get; set; }
        public Nullable<decimal> SafeQty { get; set; }
        public Nullable<decimal> MinQty { get; set; }
        public Nullable<decimal> MulQty { get; set; }
        public Nullable<decimal> FixQty { get; set; }
        public Nullable<bool> bVirtual { get; set; }
        public string DrawCode { get; set; }
        public byte[] Ufts { get; set; }
        public Nullable<int> LLC { get; set; }
        public string cBasEngineerFigNo { get; set; }
        public Nullable<double> fBasMaxSupply { get; set; }
        public short iSurenessType { get; set; }
        public Nullable<short> iDateType { get; set; }
        public Nullable<int> iDateSum { get; set; }
        public Nullable<short> iDynamicSurenessType { get; set; }
        public Nullable<double> iBestrowSum { get; set; }
        public Nullable<double> iPercentumSum { get; set; }
        public Nullable<decimal> RoundingFactor { get; set; }
        public Nullable<bool> FreeStockFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQ_BOMCOMP> SQ_BOMCOMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQ_BOMPARENT> SQ_BOMPARENT { get; set; }
    }
}
