//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_BudgetVoucherList
    {
        public string cBudgetVoucherID { get; set; }
        public string cFormCode { get; set; }
        public string cVoucherStyle { get; set; }
        public Nullable<System.DateTime> cVoucherDate { get; set; }
        public string cVersionCode { get; set; }
        public string cCaliberKey1 { get; set; }
        public string cCaliberCode1 { get; set; }
        public string cCaliberKey2 { get; set; }
        public string cCaliberCode2 { get; set; }
        public string cCaliberKey3 { get; set; }
        public string cCaliberCode3 { get; set; }
        public string cHeadCustomItem1 { get; set; }
        public string cHeadCustomItem2 { get; set; }
        public string cHeadCustomItem3 { get; set; }
        public string cHeadCustomItem4 { get; set; }
        public string cHeadCustomItem5 { get; set; }
        public string cHeadCustomItem6 { get; set; }
        public string cHeadCustomItem7 { get; set; }
        public string cHeadCustomItem8 { get; set; }
        public string cHeadCustomItem9 { get; set; }
        public string cHeadCustomItem10 { get; set; }
        public Nullable<int> iVoucherID { get; set; }
        public Nullable<int> iState { get; set; }
        public string cOrganizer { get; set; }
        public string cSubmitter { get; set; }
        public string cAuditor { get; set; }
        public string cAuditOpinion { get; set; }
        public string cItemCode { get; set; }
        public string cItemName { get; set; }
        public Nullable<short> iPeriodType { get; set; }
        public Nullable<int> iPeriod { get; set; }
        public string cSummary { get; set; }
        public string cCaliberKey4 { get; set; }
        public string cCaliberCode4 { get; set; }
        public string cCaliberKey5 { get; set; }
        public string cCaliberCode5 { get; set; }
        public string cCaliberKey6 { get; set; }
        public string cCaliberCode6 { get; set; }
        public string IYear { get; set; }
        public int iMakeYear { get; set; }
    }
}
