//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_BudgetAccount
    {
        public System.Guid cAccountID { get; set; }
        public string cServerCode { get; set; }
        public string cDataSource { get; set; }
        public string cUserName { get; set; }
        public string cUserPassword { get; set; }
        public byte[] tStamp { get; set; }
        public string cConnString { get; set; }
        public System.Guid cCtrlAccountID { get; set; }
    }
}
