//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_CtrlObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BG_CtrlObject()
        {
            this.BG_CtrlAccount_Detail = new HashSet<BG_CtrlAccount_Detail>();
            this.BG_CtrlObject_Res = new HashSet<BG_CtrlObject_Res>();
        }
    
        public string cSysId { get; set; }
        public short iStyle { get; set; }
        public byte[] tStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_CtrlAccount_Detail> BG_CtrlAccount_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_CtrlObject_Res> BG_CtrlObject_Res { get; set; }
    }
}
