//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_DataDeliverMail
    {
        public System.Guid cID { get; set; }
        public string cMailServer { get; set; }
        public int cPort { get; set; }
        public string cUserName { get; set; }
        public string cPassWord { get; set; }
        public byte[] tStamp { get; set; }
    }
}
