//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_FormFactListBGDatas
    {
        public System.Guid cFFDId { get; set; }
        public short iPeriodType { get; set; }
        public int iPeriod { get; set; }
        public Nullable<bool> bIsText { get; set; }
        public Nullable<int> iOrder { get; set; }
        public int iMakeYear { get; set; }
    }
}
