//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_FormActionPeriod
    {
        public string cFormCode { get; set; }
        public Nullable<int> ReadyPeriodType { get; set; }
        public Nullable<int> ReadyPeriodValue { get; set; }
        public Nullable<int> NowPeriodType { get; set; }
        public Nullable<int> NowPeriodValue { get; set; }
        public Nullable<int> UndoPeriodType { get; set; }
        public Nullable<int> UndoPeriodValue { get; set; }
        public int iMakeYear { get; set; }
    }
}
