//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_GroupFormConstituteID
    {
        public System.Guid cConstituteID { get; set; }
        public string cFormCode { get; set; }
        public string cConstituteDetail { get; set; }
        public byte[] dFile { get; set; }
        public Nullable<bool> bIsTemplet { get; set; }
        public Nullable<System.Guid> cBodyConstituteId { get; set; }
    }
}
