//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_MakeYearImport
    {
        public int iMakeYear { get; set; }
        public bool bImportArch { get; set; }
        public bool bImportItem { get; set; }
        public bool bImportForm { get; set; }
        public bool bImportItemExpr { get; set; }
        public bool bImportData { get; set; }
        public bool bImportAnaly { get; set; }
        public bool bImportCtrlRule { get; set; }
    }
}
