//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_Organ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BG_Organ()
        {
            this.BG_FormHypothesisValue = new HashSet<BG_FormHypothesisValue>();
            this.BG_FormOrgan = new HashSet<BG_FormOrgan>();
            this.BG_FormOrganItem = new HashSet<BG_FormOrganItem>();
            this.BG_UserAuth = new HashSet<BG_UserAuth>();
        }
    
        public string cOrganCode { get; set; }
        public string cOrganName { get; set; }
        public bool bOwner { get; set; }
        public bool bParent { get; set; }
        public bool bUpOrgan { get; set; }
        public bool bAuditAuth { get; set; }
        public string cOrganClass { get; set; }
        public string cServer { get; set; }
        public string cDataSource { get; set; }
        public string cYear { get; set; }
        public short iSource { get; set; }
        public string cEMail { get; set; }
        public string cTel { get; set; }
        public string cMark { get; set; }
        public byte[] tStamp { get; set; }
        public int iMakeYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_FormHypothesisValue> BG_FormHypothesisValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_FormOrgan> BG_FormOrgan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_FormOrganItem> BG_FormOrganItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_UserAuth> BG_UserAuth { get; set; }
    }
}
