//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_QueryFormHead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BG_QueryFormHead()
        {
            this.BG_QueryFormCaliber = new HashSet<BG_QueryFormCaliber>();
            this.BG_QueryFormItem = new HashSet<BG_QueryFormItem>();
        }
    
        public string cFormCode { get; set; }
        public string cFormName { get; set; }
        public string cVersionCode { get; set; }
        public string cUnit { get; set; }
        public short iPeriod { get; set; }
        public string cCondions { get; set; }
        public byte[] cStamp { get; set; }
        public int iMakeYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_QueryFormCaliber> BG_QueryFormCaliber { get; set; }
        public virtual BG_Version BG_Version { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_QueryFormItem> BG_QueryFormItem { get; set; }
    }
}
