//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_VarianceAnalysisFormula
    {
        public string cPKID { get; set; }
        public string cCode { get; set; }
        public Nullable<int> iType { get; set; }
        public string cItemCode { get; set; }
        public string cTargetCode { get; set; }
        public string cCaliberKey1 { get; set; }
        public string cCaliberCode1 { get; set; }
        public string cCaliberKey2 { get; set; }
        public string cCaliberCode2 { get; set; }
        public string cCaliberKey3 { get; set; }
        public string cCaliberCode3 { get; set; }
        public Nullable<int> iPeriodType { get; set; }
        public Nullable<int> iPeriod { get; set; }
        public string cDownValue { get; set; }
        public string cUpValue { get; set; }
        public string cCaliberKey4 { get; set; }
        public string cCaliberCode4 { get; set; }
        public string cCaliberKey5 { get; set; }
        public string cCaliberCode5 { get; set; }
        public string cCaliberKey6 { get; set; }
        public string cCaliberCode6 { get; set; }
        public Nullable<int> iYear { get; set; }
        public int iMakeYear { get; set; }
    }
}
