//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog_article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public blog_article()
        {
            this.blog_reply = new HashSet<blog_reply>();
            this.blog_favorites = new HashSet<blog_favorites>();
        }
    
        public long id { get; set; }
        public string subject { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> issue_time { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
        public Nullable<int> click_number { get; set; }
        public Nullable<int> reply_number { get; set; }
        public byte state { get; set; }
        public long family_id { get; set; }
        public Nullable<int> y { get; set; }
        public Nullable<int> m { get; set; }
        public long employee_id { get; set; }
        public Nullable<long> id_company { get; set; }
        public Nullable<byte> attachment_flag { get; set; }
        public Nullable<long> article_size { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blog_reply> blog_reply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blog_favorites> blog_favorites { get; set; }
        public virtual blog_employee blog_employee { get; set; }
        public virtual blog_family blog_family { get; set; }
    }
}
