//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BN_BizNotify_TPL
    {
        public string cGuidID { get; set; }
        public string cBizObjectId { get; set; }
        public string cBizEventId { get; set; }
        public string cReceiverValue { get; set; }
        public byte iTargetType { get; set; }
        public byte iTemplateType { get; set; }
    }
}
