//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BN_BizNotify
    {
        public string cBizNotifyId { get; set; }
        public string cBizNotifyName { get; set; }
        public byte iBizNotifyType { get; set; }
        public string cBizObjectId { get; set; }
        public string cBizEventId { get; set; }
        public string cCondition { get; set; }
        public Nullable<int> iSequence { get; set; }
        public bool bEnabled { get; set; }
        public string cConditionXML { get; set; }
        public string cProcessID { get; set; }
        public string cActionID { get; set; }
        public string cAttachmentType { get; set; }
        public Nullable<int> updateStatus { get; set; }
        public Nullable<byte> iNotifyStyle { get; set; }
    }
}
