//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusSenObject
    {
        public string BusObId { get; set; }
        public string BusObName { get; set; }
        public string LangId { get; set; }
        public string SubId { get; set; }
        public int Grade { get; set; }
        public bool bField { get; set; }
        public string Parent { get; set; }
        public byte[] pubufts { get; set; }
        public string objectid { get; set; }
    }
}
