//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ca_AmoctRemain_fx
    {
        public int autoid { get; set; }
        public Nullable<int> iPeriod { get; set; }
        public int cPPid { get; set; }
        public string cBatch { get; set; }
        public string cAmoID { get; set; }
        public int cAmoType { get; set; }
        public int ifxdid { get; set; }
        public Nullable<decimal> iQua { get; set; }
        public Nullable<decimal> iFinAmo { get; set; }
        public Nullable<double> iFinPdtPrice { get; set; }
        public Nullable<decimal> iFinQua { get; set; }
        public bool bQC { get; set; }
        public Nullable<decimal> iOnpPdtUnitAmo { get; set; }
    }
}
