//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_AlloComCost
    {
        public string cPubCostCode { get; set; }
        public string cDeptID { get; set; }
        public Nullable<decimal> iMoneyRatio { get; set; }
        public string cAlloMethod { get; set; }
        public string cSelfDefMethod { get; set; }
        public string cSelfDefFormula { get; set; }
        public int iYear { get; set; }
    }
}
