//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_ComMatAllocRangeExpand
    {
        public string cDeptId { get; set; }
        public int cAmoType { get; set; }
        public string cAmoId { get; set; }
        public string cOutBatch { get; set; }
        public string cRdCode { get; set; }
        public int iRealcoId { get; set; }
        public int iBasecoId { get; set; }
        public string cBatch { get; set; }
        public int iPartid { get; set; }
        public string Version { get; set; }
        public string iDentcode { get; set; }
        public Nullable<int> iLevel { get; set; }
        public bool bRefFromBom { get; set; }
    }
}
