//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ca_CoReal_zlfrel
    {
        public int aotoID { get; set; }
        public Nullable<int> iPeriod { get; set; }
        public Nullable<int> uID { get; set; }
        public string uBatch { get; set; }
        public Nullable<int> oID { get; set; }
        public string oBatch { get; set; }
        public Nullable<short> ProductType { get; set; }
    }
}
