//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_Control
    {
        public string cAuth { get; set; }
        public string cSource { get; set; }
        public string cId { get; set; }
        public string cUser { get; set; }
        public string cComputer { get; set; }
        public int autoid { get; set; }
    }
}
