//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_DirectSupplyRelation
    {
        public string cComponentMoCode { get; set; }
        public int iComponentMoSn { get; set; }
        public int iComponentRouteSn { get; set; }
        public int ComponentId { get; set; }
        public string cDsMoCode { get; set; }
        public string iDsMoSn { get; set; }
    }
}
