//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_OnlIA
    {
        public string cDeptID { get; set; }
        public int cPPID { get; set; }
        public string cBatch { get; set; }
        public string cOthAmoID { get; set; }
        public string cSource { get; set; }
        public Nullable<decimal> iOthAmo { get; set; }
        public int iperiod { get; set; }
        public int autoid { get; set; }
        public bool bQC { get; set; }
    }
}
