//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_PlanD_Fx
    {
        public int autoid { get; set; }
        public string cVerID { get; set; }
        public int cPPID { get; set; }
        public int ifxdid { get; set; }
        public Nullable<decimal> iQua { get; set; }
        public Nullable<decimal> iPdtUnitAMo { get; set; }
        public Nullable<decimal> iPartHourQua { get; set; }
        public Nullable<decimal> iPartHourAmo { get; set; }
        public Nullable<decimal> iQua_B { get; set; }
        public Nullable<decimal> iPdtUnitAMo_B { get; set; }
        public Nullable<decimal> iPartHourQua_B { get; set; }
        public Nullable<decimal> iPartHourAmo_B { get; set; }
    }
}
