//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ca_Visio_CondRet
    {
        public int iMapID { get; set; }
        public string cObjCode { get; set; }
        public string cCondType { get; set; }
        public Nullable<bool> iRetValue { get; set; }
    }
}
