//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ca_zjquantity
    {
        public int autoid { get; set; }
        public int zid { get; set; }
        public int jid { get; set; }
        public Nullable<decimal> iquantity { get; set; }
        public Nullable<decimal> iquantity_Auxi { get; set; }
        public string zbatch { get; set; }
        public string jbatch { get; set; }
    }
}
