//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cal_reply
    {
        public long id { get; set; }
        public long event_id { get; set; }
        public int cal_type { get; set; }
        public string reply_info { get; set; }
        public long reply_user_id { get; set; }
        public string reply_option { get; set; }
        public System.DateTime reply_date { get; set; }
        public string ext1 { get; set; }
        public string ext2 { get; set; }
    
        public virtual cal_event cal_event { get; set; }
    }
}
