//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_BalanceDetail
    {
        public Nullable<System.Guid> BalancesGUID { get; set; }
        public int intAutoID { get; set; }
        public decimal decMoney { get; set; }
        public decimal decExchangeRate { get; set; }
        public string cBill { get; set; }
        public string cItem { get; set; }
        public string cBalance { get; set; }
        public Nullable<System.DateTime> dtBalanceDate { get; set; }
        public string cBillClass { get; set; }
        public string intTemplateShowID { get; set; }
        public string intTemplatePrintID { get; set; }
        public byte[] Modifytamp { get; set; }
        public Nullable<decimal> iQuantity { get; set; }
        public string cBalanceID { get; set; }
        public string strSpare1 { get; set; }
        public string strSpare2 { get; set; }
        public string strSpare3 { get; set; }
        public Nullable<decimal> decRMB { get; set; }
        public Nullable<System.Guid> DetailGuid { get; set; }
        public string cCancelNo { get; set; }
        public string cProcStyle { get; set; }
        public Nullable<decimal> ExecPieceNum { get; set; }
        public string cExecID { get; set; }
    
        public virtual CM_Balances CM_Balances { get; set; }
    }
}
