//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_Contract_Main
    {
        public string strContractID { get; set; }
        public string strRel { get; set; }
        public string strSource { get; set; }
        public Nullable<byte> intDetail { get; set; }
        public Nullable<byte> intMustDetail { get; set; }
        public string strTempleteShowID { get; set; }
        public string strTempletePrintID { get; set; }
        public Nullable<byte> intKL { get; set; }
        public string strSpare1 { get; set; }
        public string strSpare2 { get; set; }
        public string strSpare3 { get; set; }
        public Nullable<double> dblPreAPARCurrency { get; set; }
        public Nullable<double> dblPreAPARCurrencyRMB { get; set; }
        public string strTaxRatio { get; set; }
    }
}
