//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CN_AcctFilterColPro
    {
        public int ID { get; set; }
        public Nullable<int> SchemeID { get; set; }
        public string ShowName { get; set; }
        public Nullable<int> KeyName { get; set; }
        public Nullable<int> IsVisble { get; set; }
        public Nullable<int> ColWidth { get; set; }
        public Nullable<int> ColOrder { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> SortType { get; set; }
        public Nullable<int> IsSubSum { get; set; }
        public Nullable<int> IsLevelSum { get; set; }
        public Nullable<int> IsMuchTitle { get; set; }
        public int iLanguage { get; set; }
    }
}
