//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CN_LockAcctBook
    {
        public int AutoID { get; set; }
        public string cVouchType { get; set; }
        public string ID { get; set; }
        public string cAuth { get; set; }
        public string cUser { get; set; }
        public string cWorkStation { get; set; }
    }
}
