//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class col_branch
    {
        public long id { get; set; }
        public Nullable<int> condition_type { get; set; }
        public string form_condition { get; set; }
        public string condition_title { get; set; }
        public string condition_desc { get; set; }
        public Nullable<long> template_id { get; set; }
        public Nullable<long> link_id { get; set; }
        public Nullable<bool> is_force { get; set; }
        public string condition_base { get; set; }
        public Nullable<byte> app_type { get; set; }
    }
}
