//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crm_CusValModel_s
    {
        public string OID { get; set; }
        public int AutoID { get; set; }
        public string cCusValModelOID { get; set; }
        public Nullable<int> iSeq { get; set; }
        public string cCusValType { get; set; }
        public Nullable<double> fQRate { get; set; }
        public Nullable<double> fARate { get; set; }
        public string cMemo { get; set; }
        public byte[] ufts { get; set; }
    }
}
