//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crm_Competitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Crm_Competitor()
        {
            this.Crm_OppCompetitor = new HashSet<Crm_OppCompetitor>();
        }
    
        public string OID { get; set; }
        public int AutoID { get; set; }
        public string cCompetitorCode { get; set; }
        public string cCompetitorName { get; set; }
        public string cCompetitorAbbr { get; set; }
        public string cDCCode { get; set; }
        public string cTradeCCode { get; set; }
        public string cCompetitorPCompany { get; set; }
        public Nullable<int> bcCompetitorLevelID { get; set; }
        public string cCompetitorPrincipal { get; set; }
        public string cCompetitorAddress { get; set; }
        public string cCompetitorPhone { get; set; }
        public string cCompetitorFax { get; set; }
        public string cCompetitorPostcode { get; set; }
        public string cCompetitorHomepage { get; set; }
        public string cCreator { get; set; }
        public Nullable<System.DateTime> dCreateDate { get; set; }
        public string cRevisor { get; set; }
        public Nullable<System.DateTime> dModifyDate { get; set; }
        public string cCompetitorStockCode { get; set; }
        public string cCompetitorAdvantage { get; set; }
        public string cCompetitorDisadvantage { get; set; }
        public string cCompetitorMemo { get; set; }
        public byte[] ufts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crm_OppCompetitor> Crm_OppCompetitor { get; set; }
    }
}
