//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dimension
    {
        public string cDimCode { get; set; }
        public Nullable<bool> bComposited { get; set; }
        public string cDimValuesView { get; set; }
        public string cBaseDimCode { get; set; }
        public string cBaseDimValuesQuery { get; set; }
        public string cBusinessObjectName { get; set; }
        public Nullable<bool> bGenerate { get; set; }
        public string cProcessMethod { get; set; }
        public string cReferId { get; set; }
        public string cReferFilterSQL { get; set; }
    }
}
