//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_metadata
    {
        public long doc_resource_id { get; set; }
        public string avarchar1 { get; set; }
        public string avarchar2 { get; set; }
        public string avarchar3 { get; set; }
        public string avarchar4 { get; set; }
        public string avarchar5 { get; set; }
        public string avarchar6 { get; set; }
        public string avarchar7 { get; set; }
        public string avarchar8 { get; set; }
        public string avarchar9 { get; set; }
        public string avarchar10 { get; set; }
        public string avarchar11 { get; set; }
        public string avarchar12 { get; set; }
        public string avarchar13 { get; set; }
        public string avarchar14 { get; set; }
        public string avarchar15 { get; set; }
        public string avarchar16 { get; set; }
        public string avarchar17 { get; set; }
        public string avarchar18 { get; set; }
        public string avarchar19 { get; set; }
        public string avarchar20 { get; set; }
        public string avarchar21 { get; set; }
        public string avarchar22 { get; set; }
        public string avarchar23 { get; set; }
        public string avarchar24 { get; set; }
        public string avarchar25 { get; set; }
        public string avarchar26 { get; set; }
        public string avarchar27 { get; set; }
        public string avarchar28 { get; set; }
        public string avarchar29 { get; set; }
        public string avarchar30 { get; set; }
        public string avarchar31 { get; set; }
        public string avarchar32 { get; set; }
        public string avarchar33 { get; set; }
        public string avarchar34 { get; set; }
        public string avarchar35 { get; set; }
        public string avarchar36 { get; set; }
        public string avarchar37 { get; set; }
        public string avarchar38 { get; set; }
        public string avarchar39 { get; set; }
        public string avarchar40 { get; set; }
        public string avarchar41 { get; set; }
        public string avarchar42 { get; set; }
        public string avarchar43 { get; set; }
        public string avarchar44 { get; set; }
        public string avarchar45 { get; set; }
        public string avarchar46 { get; set; }
        public string avarchar47 { get; set; }
        public string avarchar48 { get; set; }
        public string avarchar49 { get; set; }
        public string avarchar50 { get; set; }
        public string avarchar51 { get; set; }
        public string avarchar52 { get; set; }
        public string avarchar53 { get; set; }
        public string avarchar54 { get; set; }
        public string avarchar55 { get; set; }
        public string avarchar56 { get; set; }
        public string avarchar57 { get; set; }
        public string avarchar58 { get; set; }
        public string avarchar59 { get; set; }
        public string avarchar60 { get; set; }
        public Nullable<int> integer1 { get; set; }
        public Nullable<int> integer2 { get; set; }
        public Nullable<int> integer3 { get; set; }
        public Nullable<int> integer4 { get; set; }
        public Nullable<int> integer5 { get; set; }
        public Nullable<int> integer6 { get; set; }
        public Nullable<int> integer7 { get; set; }
        public Nullable<int> integer8 { get; set; }
        public Nullable<int> integer9 { get; set; }
        public Nullable<int> integer10 { get; set; }
        public Nullable<decimal> decimal1 { get; set; }
        public Nullable<decimal> decimal2 { get; set; }
        public Nullable<decimal> decimal3 { get; set; }
        public Nullable<decimal> decimal4 { get; set; }
        public Nullable<decimal> decimal5 { get; set; }
        public Nullable<decimal> decimal6 { get; set; }
        public Nullable<decimal> decimal7 { get; set; }
        public Nullable<decimal> decimal8 { get; set; }
        public Nullable<decimal> decimal9 { get; set; }
        public Nullable<decimal> decimal10 { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<System.DateTime> date2 { get; set; }
        public Nullable<System.DateTime> date3 { get; set; }
        public Nullable<System.DateTime> date4 { get; set; }
        public Nullable<System.DateTime> date5 { get; set; }
        public Nullable<System.DateTime> date6 { get; set; }
        public Nullable<System.DateTime> date7 { get; set; }
        public Nullable<System.DateTime> date8 { get; set; }
        public Nullable<System.DateTime> date9 { get; set; }
        public Nullable<System.DateTime> date10 { get; set; }
        public Nullable<System.DateTime> date11 { get; set; }
        public Nullable<System.DateTime> date12 { get; set; }
        public Nullable<System.DateTime> date13 { get; set; }
        public Nullable<System.DateTime> date14 { get; set; }
        public Nullable<System.DateTime> date15 { get; set; }
        public Nullable<System.DateTime> date16 { get; set; }
        public Nullable<System.DateTime> date17 { get; set; }
        public Nullable<System.DateTime> date18 { get; set; }
        public Nullable<System.DateTime> date19 { get; set; }
        public Nullable<System.DateTime> date20 { get; set; }
        public Nullable<System.DateTime> datetime1 { get; set; }
        public Nullable<System.DateTime> datetime2 { get; set; }
        public Nullable<System.DateTime> datetime3 { get; set; }
        public Nullable<System.DateTime> datetime4 { get; set; }
        public Nullable<System.DateTime> datetime5 { get; set; }
        public Nullable<System.DateTime> datetime6 { get; set; }
        public Nullable<System.DateTime> datetime7 { get; set; }
        public Nullable<System.DateTime> datetime8 { get; set; }
        public Nullable<System.DateTime> datetime9 { get; set; }
        public Nullable<System.DateTime> datetime10 { get; set; }
        public Nullable<System.DateTime> datetime11 { get; set; }
        public Nullable<System.DateTime> datetime12 { get; set; }
        public Nullable<System.DateTime> datetime13 { get; set; }
        public Nullable<System.DateTime> datetime14 { get; set; }
        public Nullable<System.DateTime> datetime15 { get; set; }
        public Nullable<System.DateTime> datetime16 { get; set; }
        public Nullable<System.DateTime> datetime17 { get; set; }
        public Nullable<System.DateTime> datetime18 { get; set; }
        public Nullable<System.DateTime> datetime19 { get; set; }
        public Nullable<System.DateTime> datetime20 { get; set; }
        public string text1 { get; set; }
        public string text2 { get; set; }
        public string text3 { get; set; }
        public string text4 { get; set; }
        public string text5 { get; set; }
        public string text6 { get; set; }
        public string text7 { get; set; }
        public string text8 { get; set; }
        public string text9 { get; set; }
        public string text10 { get; set; }
        public string text11 { get; set; }
        public string text12 { get; set; }
        public string text13 { get; set; }
        public string text14 { get; set; }
        public string text15 { get; set; }
        public Nullable<byte> boolean1 { get; set; }
        public Nullable<byte> boolean2 { get; set; }
        public Nullable<byte> boolean3 { get; set; }
        public Nullable<byte> boolean4 { get; set; }
        public Nullable<byte> boolean5 { get; set; }
        public Nullable<long> reference1 { get; set; }
        public Nullable<long> reference2 { get; set; }
        public Nullable<long> reference3 { get; set; }
        public Nullable<long> reference4 { get; set; }
        public Nullable<long> reference5 { get; set; }
        public Nullable<long> reference6 { get; set; }
        public Nullable<long> reference7 { get; set; }
        public Nullable<long> reference8 { get; set; }
        public Nullable<long> reference9 { get; set; }
        public Nullable<long> reference10 { get; set; }
        public Nullable<long> enum1 { get; set; }
        public Nullable<long> enum2 { get; set; }
        public Nullable<long> enum3 { get; set; }
        public Nullable<long> enum4 { get; set; }
        public Nullable<long> enum5 { get; set; }
        public Nullable<long> enum6 { get; set; }
        public Nullable<long> enum7 { get; set; }
        public Nullable<long> enum8 { get; set; }
        public Nullable<long> enum9 { get; set; }
        public Nullable<long> enum10 { get; set; }
    }
}
