//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_lib_members
    {
        public long id { get; set; }
        public long doc_lib_id { get; set; }
        public long user_id { get; set; }
        public string user_type { get; set; }
    
        public virtual doc_libs doc_libs { get; set; }
    }
}
