//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_acl
    {
        public long id { get; set; }
        public int potenttype { get; set; }
        public long user_id { get; set; }
        public string user_type { get; set; }
        public byte sharetype { get; set; }
        public Nullable<long> owner_id { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public long doc_resource_id { get; set; }
        public byte is_alert { get; set; }
        public Nullable<long> doc_alert_id { get; set; }
        public int len_potent { get; set; }
        public string len_potent2 { get; set; }
        public int acl_order { get; set; }
    
        public virtual doc_resources doc_resources { get; set; }
    }
}
