//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EB_Switch_ShopSetting
    {
        public long iAutoID { get; set; }
        public long iShopID { get; set; }
        public string cSellerNick { get; set; }
        public Nullable<int> iAuthStatus { get; set; }
        public string cSessionKey { get; set; }
        public string cAppKey { get; set; }
        public string cAppSecret { get; set; }
        public string cPayPlatform { get; set; }
        public string cPayAccount { get; set; }
        public string cPayPartnerID { get; set; }
        public string cPayPartnerSecret { get; set; }
        public string cStatementPath { get; set; }
    }
}
