//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EB_Switch_TransferDetail
    {
        public long iAutoID { get; set; }
        public long iShopID { get; set; }
        public System.DateTime dCreated { get; set; }
        public int iDirection { get; set; }
        public string cItemKey { get; set; }
        public string cItemDetail { get; set; }
        public System.Guid cApiID { get; set; }
        public int iStatus { get; set; }
        public string cMemo { get; set; }
        public string cHandler { get; set; }
    }
}
