//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecn_ecnapply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ecn_ecnapply()
        {
            this.ecn_ecnapplydetail = new HashSet<ecn_ecnapplydetail>();
            this.ecn_ecnnote = new HashSet<ecn_ecnnote>();
        }
    
        public int ApplyId { get; set; }
        public string DocCode { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<int> ReasonId { get; set; }
        public string EmplCode { get; set; }
        public Nullable<System.DateTime> PlanAuditDate { get; set; }
        public Nullable<System.DateTime> PlanReleaseDate { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string Submitor { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public string Releaser { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> AuditStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<int> UpdCount { get; set; }
        public byte[] Ufts { get; set; }
        public string Define1 { get; set; }
        public string Define2 { get; set; }
        public string Define3 { get; set; }
        public Nullable<System.DateTime> Define4 { get; set; }
        public Nullable<int> Define5 { get; set; }
        public Nullable<System.DateTime> Define6 { get; set; }
        public Nullable<double> Define7 { get; set; }
        public string Define8 { get; set; }
        public string Define9 { get; set; }
        public string Define10 { get; set; }
        public string Define11 { get; set; }
        public string Define12 { get; set; }
        public string Define13 { get; set; }
        public string Define14 { get; set; }
        public Nullable<int> Define15 { get; set; }
        public Nullable<double> Define16 { get; set; }
        public Nullable<int> VTid { get; set; }
        public Nullable<byte> IsWFControlled { get; set; }
        public Nullable<int> iVerifyState { get; set; }
        public Nullable<int> iReturnCount { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public Nullable<System.DateTime> ReleaseTime { get; set; }
        public Nullable<System.DateTime> SubmitTime { get; set; }
        public string CloseUser { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<System.DateTime> CloseTime { get; set; }
        public Nullable<byte> OrgStatus { get; set; }
        public Nullable<int> iPrintCount { get; set; }
        public string cCurrentAuditor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecn_ecnapplydetail> ecn_ecnapplydetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecn_ecnnote> ecn_ecnnote { get; set; }
    }
}
