//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class edoc_summary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public edoc_summary()
        {
            this.edoc_archive_record = new HashSet<edoc_archive_record>();
            this.edoc_body = new HashSet<edoc_body>();
            this.edoc_opinion = new HashSet<edoc_opinion>();
        }
    
        public long id { get; set; }
        public string identifier { get; set; }
        public Nullable<byte> has_archive { get; set; }
        public byte edoc_type { get; set; }
        public Nullable<long> deadline { get; set; }
        public byte can_track { get; set; }
        public string comments { get; set; }
        public string process_id { get; set; }
        public Nullable<long> case_id { get; set; }
        public Nullable<long> form_id { get; set; }
        public System.DateTime create_time { get; set; }
        public Nullable<long> start_user_id { get; set; }
        public System.DateTime start_time { get; set; }
        public string create_person { get; set; }
        public Nullable<System.DateTime> complete_time { get; set; }
        public byte state { get; set; }
        public string subject { get; set; }
        public string doc_type { get; set; }
        public string send_type { get; set; }
        public string doc_mark { get; set; }
        public string serial_no { get; set; }
        public string secret_level { get; set; }
        public string urgent_level { get; set; }
        public Nullable<int> keep_period { get; set; }
        public string send_unit { get; set; }
        public string send_unit_id { get; set; }
        public string issuer { get; set; }
        public Nullable<System.DateTime> signing_date { get; set; }
        public string send_to { get; set; }
        public string send_to_id { get; set; }
        public string copy_to { get; set; }
        public string copy_to_id { get; set; }
        public string report_to { get; set; }
        public string report_to_id { get; set; }
        public string keywords { get; set; }
        public string print_unit { get; set; }
        public Nullable<int> copies { get; set; }
        public string printer { get; set; }
        public Nullable<long> advance_remind { get; set; }
        public Nullable<long> templete_id { get; set; }
        public string workflow_rule { get; set; }
        public Nullable<System.DateTime> pack_date { get; set; }
        public string avarchar1 { get; set; }
        public string avarchar2 { get; set; }
        public string avarchar3 { get; set; }
        public string avarchar4 { get; set; }
        public string avarchar5 { get; set; }
        public string avarchar6 { get; set; }
        public string avarchar7 { get; set; }
        public string avarchar8 { get; set; }
        public string avarchar9 { get; set; }
        public string avarchar10 { get; set; }
        public string avarchar11 { get; set; }
        public string avarchar12 { get; set; }
        public string avarchar13 { get; set; }
        public string avarchar14 { get; set; }
        public string avarchar15 { get; set; }
        public string avarchar16 { get; set; }
        public string avarchar17 { get; set; }
        public string avarchar18 { get; set; }
        public string avarchar19 { get; set; }
        public string avarchar20 { get; set; }
        public string text1 { get; set; }
        public string text2 { get; set; }
        public string text3 { get; set; }
        public string text4 { get; set; }
        public string text5 { get; set; }
        public string text6 { get; set; }
        public string text7 { get; set; }
        public string text8 { get; set; }
        public string text9 { get; set; }
        public string text10 { get; set; }
        public Nullable<int> integer1 { get; set; }
        public Nullable<int> integer2 { get; set; }
        public Nullable<int> integer3 { get; set; }
        public Nullable<int> integer4 { get; set; }
        public Nullable<int> integer5 { get; set; }
        public Nullable<int> integer6 { get; set; }
        public Nullable<int> integer7 { get; set; }
        public Nullable<int> integer8 { get; set; }
        public Nullable<int> integer9 { get; set; }
        public Nullable<int> integer10 { get; set; }
        public Nullable<int> integer11 { get; set; }
        public Nullable<int> integer12 { get; set; }
        public Nullable<int> integer13 { get; set; }
        public Nullable<int> integer14 { get; set; }
        public Nullable<int> integer15 { get; set; }
        public Nullable<int> integer16 { get; set; }
        public Nullable<int> integer17 { get; set; }
        public Nullable<int> integer18 { get; set; }
        public Nullable<int> integer19 { get; set; }
        public Nullable<int> integer20 { get; set; }
        public Nullable<decimal> decimal1 { get; set; }
        public Nullable<decimal> decimal2 { get; set; }
        public Nullable<decimal> decimal3 { get; set; }
        public Nullable<decimal> decimal4 { get; set; }
        public Nullable<decimal> decimal5 { get; set; }
        public Nullable<decimal> decimal6 { get; set; }
        public Nullable<decimal> decimal7 { get; set; }
        public Nullable<decimal> decimal8 { get; set; }
        public Nullable<decimal> decimal9 { get; set; }
        public Nullable<decimal> decimal10 { get; set; }
        public Nullable<decimal> decimal11 { get; set; }
        public Nullable<decimal> decimal12 { get; set; }
        public Nullable<decimal> decimal13 { get; set; }
        public Nullable<decimal> decimal14 { get; set; }
        public Nullable<decimal> decimal15 { get; set; }
        public Nullable<decimal> decimal16 { get; set; }
        public Nullable<decimal> decimal17 { get; set; }
        public Nullable<decimal> decimal18 { get; set; }
        public Nullable<decimal> decimal19 { get; set; }
        public Nullable<decimal> decimal20 { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<System.DateTime> date2 { get; set; }
        public Nullable<System.DateTime> date3 { get; set; }
        public Nullable<System.DateTime> date4 { get; set; }
        public Nullable<System.DateTime> date5 { get; set; }
        public Nullable<System.DateTime> date6 { get; set; }
        public Nullable<System.DateTime> date7 { get; set; }
        public Nullable<System.DateTime> date8 { get; set; }
        public Nullable<System.DateTime> date9 { get; set; }
        public Nullable<System.DateTime> date10 { get; set; }
        public Nullable<System.DateTime> date11 { get; set; }
        public Nullable<System.DateTime> date12 { get; set; }
        public Nullable<System.DateTime> date13 { get; set; }
        public Nullable<System.DateTime> date14 { get; set; }
        public Nullable<System.DateTime> date15 { get; set; }
        public Nullable<System.DateTime> date16 { get; set; }
        public Nullable<System.DateTime> date17 { get; set; }
        public Nullable<System.DateTime> date18 { get; set; }
        public Nullable<System.DateTime> date19 { get; set; }
        public Nullable<System.DateTime> date20 { get; set; }
        public string list1 { get; set; }
        public string list2 { get; set; }
        public string list3 { get; set; }
        public string list4 { get; set; }
        public string list5 { get; set; }
        public string list6 { get; set; }
        public string list7 { get; set; }
        public string list8 { get; set; }
        public string list9 { get; set; }
        public string list10 { get; set; }
        public string list11 { get; set; }
        public string list12 { get; set; }
        public string list13 { get; set; }
        public string list14 { get; set; }
        public string list15 { get; set; }
        public string list16 { get; set; }
        public string list17 { get; set; }
        public string list18 { get; set; }
        public string list19 { get; set; }
        public string list20 { get; set; }
        public Nullable<byte> isunit { get; set; }
        public string doc_mark2 { get; set; }
        public string send_unit2 { get; set; }
        public string send_unit_id2 { get; set; }
        public string send_to2 { get; set; }
        public string send_to_id2 { get; set; }
        public string copy_to2 { get; set; }
        public string copy_to_id2 { get; set; }
        public string report_to2 { get; set; }
        public string report_to_id2 { get; set; }
        public Nullable<int> copies2 { get; set; }
        public Nullable<long> org_department_id { get; set; }
        public Nullable<long> org_account_id { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string avarchar21 { get; set; }
        public string avarchar22 { get; set; }
        public string avarchar23 { get; set; }
        public string avarchar24 { get; set; }
        public string avarchar25 { get; set; }
        public string avarchar26 { get; set; }
        public string avarchar27 { get; set; }
        public string avarchar28 { get; set; }
        public string avarchar29 { get; set; }
        public string avarchar30 { get; set; }
        public string text11 { get; set; }
        public string text12 { get; set; }
        public string text13 { get; set; }
        public string text14 { get; set; }
        public string text15 { get; set; }
        public Nullable<long> archive_id { get; set; }
        public Nullable<long> process_type { get; set; }
        public Nullable<long> sub_edoc_type { get; set; }
        public string filesm { get; set; }
        public string filefz { get; set; }
        public string party { get; set; }
        public string administrative { get; set; }
        public string send_department { get; set; }
        public string send_department2 { get; set; }
        public string send_department_id { get; set; }
        public string send_department_id2 { get; set; }
        public string attachments { get; set; }
        public Nullable<long> over_worktime { get; set; }
        public Nullable<long> run_worktime { get; set; }
        public Nullable<long> over_time { get; set; }
        public Nullable<long> run_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<edoc_archive_record> edoc_archive_record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<edoc_body> edoc_body { get; set; }
        public virtual edoc_form edoc_form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<edoc_opinion> edoc_opinion { get; set; }
    }
}
