//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDOC_ZCDB
    {
        public long ID { get; set; }
        public Nullable<long> AFFAIR_ID { get; set; }
        public Nullable<System.DateTime> ZCDB_TIME { get; set; }
    }
}
