//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engine_PubChannelTaskComplete
    {
        public string MsgID { get; set; }
        public string ChannelID { get; set; }
        public bool Completed { get; set; }
        public bool Succeed { get; set; }
        public Nullable<long> RepSize { get; set; }
        public string Report { get; set; }
    }
}
