//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ex_innergather
    {
        public string objectid { get; set; }
        public string guid { get; set; }
        public Nullable<decimal> fsaleqty { get; set; }
        public Nullable<decimal> fsalenum { get; set; }
        public Nullable<decimal> fsalemoney { get; set; }
        public Nullable<decimal> fnatsalemoney { get; set; }
        public Nullable<decimal> fstockupqty { get; set; }
        public Nullable<decimal> fstockupnum { get; set; }
        public Nullable<decimal> fpuqty { get; set; }
        public Nullable<decimal> fpunum { get; set; }
        public Nullable<decimal> fmoqty { get; set; }
        public Nullable<decimal> fmonum { get; set; }
        public Nullable<decimal> funsaleqty { get; set; }
        public Nullable<decimal> funsalenum { get; set; }
        public Nullable<decimal> funsalemoney { get; set; }
        public Nullable<decimal> fnatunsalemoney { get; set; }
        public Nullable<decimal> foutqty { get; set; }
        public Nullable<decimal> foutnum { get; set; }
        public Nullable<decimal> funoutqty { get; set; }
        public Nullable<decimal> funoutnum { get; set; }
        public Nullable<decimal> finvoiceqty { get; set; }
        public Nullable<decimal> finvoicenum { get; set; }
        public Nullable<decimal> finvoicemoney { get; set; }
        public Nullable<decimal> fnatinvoicemoney { get; set; }
        public Nullable<decimal> funinvoiceqty { get; set; }
        public Nullable<decimal> funinvoicenum { get; set; }
        public Nullable<decimal> funinvoicemoney { get; set; }
        public Nullable<decimal> fnatuninvoicemoney { get; set; }
        public Nullable<decimal> fgatheringmoney { get; set; }
        public Nullable<decimal> fnatgatheringmoney { get; set; }
        public Nullable<decimal> fpaymoney { get; set; }
        public Nullable<decimal> fnatpaymoney { get; set; }
        public Nullable<int> iunittype { get; set; }
    }
}
