//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EX_ORDER_DEMO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EX_ORDER_DEMO()
        {
            this.EX_ORDERS_DEMO = new HashSet<EX_ORDERS_DEMO>();
        }
    
        public int MAINID { get; set; }
        public string CORDERCODE { get; set; }
        public Nullable<System.DateTime> DDATE { get; set; }
        public string CDEPNAME { get; set; }
        public string CPERSONNAME { get; set; }
        public string CTMNAME { get; set; }
        public string CBUSTYPE { get; set; }
        public string CSTNAME { get; set; }
        public string CCUSABBNAME { get; set; }
        public string CUPAYMEMO { get; set; }
        public string CINCOTERMREMARK { get; set; }
        public string CMEMO { get; set; }
        public string CEXCH_NAME { get; set; }
        public decimal IEXCHRATE { get; set; }
        public string CSSNAME { get; set; }
        public int IDATE { get; set; }
        public string CUPLOADMEMO { get; set; }
        public string CSCNAME { get; set; }
        public string CBATCHLOAD { get; set; }
        public string CTRANS { get; set; }
        public string CSOURCEADDRESS { get; set; }
        public string CLOADPORT { get; set; }
        public string CTARGETPORT { get; set; }
        public string CVENABBNAME { get; set; }
        public Nullable<System.DateTime> DLASTDATE { get; set; }
        public string CUPLOAD { get; set; }
        public decimal FPAYRATE { get; set; }
        public decimal FPAY { get; set; }
        public string CSUREMEMO { get; set; }
        public string CBUSCHECKMEMO { get; set; }
        public string CPAYMEMO { get; set; }
        public string CNOWAYMEMO { get; set; }
        public string CDECIDEMEMO { get; set; }
        public string CMAKER { get; set; }
        public string CCLOSER { get; set; }
        public string CVERIFIER { get; set; }
        public string CMODIFER { get; set; }
        public string CLOCKER { get; set; }
        public string CQUOCODE { get; set; }
        public string CPAPERMEMO { get; set; }
        public string CUPAPERMEMO { get; set; }
        public string CDEFINE1 { get; set; }
        public string CDEFINE2 { get; set; }
        public string CDEFINE3 { get; set; }
        public Nullable<System.DateTime> CDEFINE4 { get; set; }
        public Nullable<int> CDEFINE5 { get; set; }
        public Nullable<System.DateTime> CDEFINE6 { get; set; }
        public Nullable<decimal> CDEFINE7 { get; set; }
        public string CDEFINE8 { get; set; }
        public string CDEFINE9 { get; set; }
        public string CDEFINE10 { get; set; }
        public string CDEFINE11 { get; set; }
        public string CDEFINE12 { get; set; }
        public string CDEFINE13 { get; set; }
        public string CDEFINE14 { get; set; }
        public Nullable<int> CDEFINE15 { get; set; }
        public Nullable<decimal> CDEFINE16 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EX_ORDERS_DEMO> EX_ORDERS_DEMO { get; set; }
    }
}
