//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ex_orderassistant_history
    {
        public int id { get; set; }
        public int iversion { get; set; }
        public string cshippingitem { get; set; }
        public string cpaymentitem { get; set; }
        public string cinsureitem { get; set; }
        public string ccheckitem { get; set; }
        public string ccompensationitem { get; set; }
        public string cforcemajeureitem { get; set; }
        public string cartbitationitem { get; set; }
        public long HistoryId { get; set; }
        public Nullable<byte> VariationAction { get; set; }
        public int VariationLogId { get; set; }
        public Nullable<byte> SubVariationAction { get; set; }
    }
}
