//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ex_port
    {
        public string guid { get; set; }
        public int iportid { get; set; }
        public string cportcode { get; set; }
        public Nullable<int> inationid { get; set; }
        public string cportname { get; set; }
        public string cportenglish { get; set; }
        public string cdccode { get; set; }
        public short iportattrid { get; set; }
        public string cportremark { get; set; }
        public byte[] ufts { get; set; }
    }
}
