//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ex_stockupdetail
    {
        public string guids { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> iconsignmentrowno { get; set; }
        public int autoid { get; set; }
        public string cordercode { get; set; }
        public Nullable<int> iorderautoid { get; set; }
        public Nullable<int> irowno { get; set; }
        public string ccusinvcode { get; set; }
        public string ccusinvname { get; set; }
        public string cinvcode { get; set; }
        public Nullable<int> iinautoid { get; set; }
        public string coutwhcode { get; set; }
        public string cbatch { get; set; }
        public Nullable<System.DateTime> dprodate { get; set; }
        public Nullable<int> imassdate { get; set; }
        public Nullable<short> imassunitid { get; set; }
        public Nullable<System.DateTime> dvdate { get; set; }
        public string cincode { get; set; }
        public string csacomunitcode { get; set; }
        public Nullable<decimal> fquantity { get; set; }
        public Nullable<decimal> fchangrate { get; set; }
        public Nullable<decimal> fnum { get; set; }
        public Nullable<decimal> fstquantity { get; set; }
        public Nullable<decimal> fstnum { get; set; }
        public string cstpersoncode { get; set; }
        public Nullable<System.DateTime> dstdate { get; set; }
        public Nullable<decimal> foverflowrange { get; set; }
        public string citem_class { get; set; }
        public string citem_cname { get; set; }
        public string citemcode { get; set; }
        public string citemname { get; set; }
        public string cmemo { get; set; }
        public Nullable<System.DateTime> dshippingdate { get; set; }
        public Nullable<decimal> funsaleqty { get; set; }
        public Nullable<decimal> foutqty { get; set; }
        public Nullable<decimal> funoutqty { get; set; }
        public Nullable<bool> bdrawbackflag { get; set; }
        public Nullable<bool> bexecute { get; set; }
        public int iversion { get; set; }
        public string clinecloser { get; set; }
        public Nullable<System.DateTime> dlineclosedate { get; set; }
        public Nullable<short> iexcutetime { get; set; }
        public byte[] lineufts { get; set; }
        public string objectid_source { get; set; }
        public string guid_source { get; set; }
        public string ufts_source { get; set; }
        public Nullable<int> iexecutetime { get; set; }
        public Nullable<decimal> funsalenum { get; set; }
        public Nullable<decimal> funsalemoney { get; set; }
        public Nullable<decimal> fnatunsalemoney { get; set; }
        public Nullable<decimal> foutnum { get; set; }
        public Nullable<decimal> funoutnum { get; set; }
        public string cdefine22 { get; set; }
        public string cdefine23 { get; set; }
        public string cdefine24 { get; set; }
        public string cdefine25 { get; set; }
        public Nullable<double> cdefine26 { get; set; }
        public Nullable<double> cdefine27 { get; set; }
        public string cdefine28 { get; set; }
        public string cdefine29 { get; set; }
        public string cdefine30 { get; set; }
        public string cdefine31 { get; set; }
        public string cdefine32 { get; set; }
        public string cdefine33 { get; set; }
        public Nullable<int> cdefine34 { get; set; }
        public Nullable<int> cdefine35 { get; set; }
        public Nullable<System.DateTime> cdefine36 { get; set; }
        public Nullable<System.DateTime> cdefine37 { get; set; }
        public string cfree1 { get; set; }
        public string cfree2 { get; set; }
        public string cfree3 { get; set; }
        public string cfree4 { get; set; }
        public string cfree5 { get; set; }
        public string cfree6 { get; set; }
        public string cfree7 { get; set; }
        public string cfree8 { get; set; }
        public string cfree9 { get; set; }
        public string cfree10 { get; set; }
        public Nullable<int> iexpiratdatecalcu { get; set; }
        public string cexpirationdate { get; set; }
        public Nullable<System.DateTime> dexpirationdate { get; set; }
        public Nullable<decimal> cBatchProperty1 { get; set; }
        public Nullable<decimal> cBatchProperty2 { get; set; }
        public Nullable<decimal> cBatchProperty3 { get; set; }
        public Nullable<decimal> cBatchProperty4 { get; set; }
        public Nullable<decimal> cBatchProperty5 { get; set; }
        public string cBatchProperty6 { get; set; }
        public string cBatchProperty7 { get; set; }
        public string cBatchProperty8 { get; set; }
        public string cBatchProperty9 { get; set; }
        public Nullable<System.DateTime> cBatchProperty10 { get; set; }
        public Nullable<int> iciqbookid { get; set; }
        public string cciqbookcode { get; set; }
        public string cciqcode { get; set; }
        public Nullable<decimal> fciqchangrate { get; set; }
        public string cvmivencode { get; set; }
        public string cinvouchtype { get; set; }
        public string corufts { get; set; }
        public string ccontractid { get; set; }
        public string ccontracttagcode { get; set; }
        public Nullable<System.Guid> ccontractrowguid { get; set; }
        public string cbsysbarcode { get; set; }
    }
}
