//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ex_tableid
    {
        public string vouchtype { get; set; }
        public string name { get; set; }
        public string tablename { get; set; }
        public string fieldname { get; set; }
        public string headertablename { get; set; }
        public string detailtablename { get; set; }
        public string headerviewname { get; set; }
        public string detailviewname { get; set; }
        public string uniqueryviewname { get; set; }
        public string filtertablename { get; set; }
    }
}
