//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exchange_account
    {
        public long id { get; set; }
        public string account_id { get; set; }
        public string name { get; set; }
        public byte account_type { get; set; }
        public string description { get; set; }
        public byte is_internal_account { get; set; }
        public Nullable<long> internal_org_id { get; set; }
        public Nullable<long> internal_dept_id { get; set; }
        public Nullable<long> internal_user_id { get; set; }
        public string exchange_server_id { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime last_update { get; set; }
        public byte status { get; set; }
        public long domain_id { get; set; }
    }
}
