//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exp_Function
    {
        public string cFuncId { get; set; }
        public string cFuncName { get; set; }
        public string cAssembly { get; set; }
        public string cReturnType { get; set; }
        public string cGroupId { get; set; }
        public int iOrder { get; set; }
        public int iGroupOrder { get; set; }
        public short iApplyType { get; set; }
        public short iHandle { get; set; }
        public short iCodeType { get; set; }
        public string cCode { get; set; }
    }
}
