//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FA_AccAttachs
    {
        public int Inid { get; set; }
        public int sCardID { get; set; }
        public string CClientFileName { get; set; }
        public string CServerFileName { get; set; }
        public Nullable<System.DateTime> SubmitTime { get; set; }
        public Nullable<int> iDoc { get; set; }
    }
}
