//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_CardsSheets
    {
        public string sID { get; set; }
        public string sCardNum { get; set; }
        public Nullable<int> lSheetNum { get; set; }
        public string sNum { get; set; }
        public string sVoucherNum { get; set; }
        public string sEvaNum { get; set; }
        public Nullable<System.DateTime> dStartDate { get; set; }
        public Nullable<System.DateTime> dEndDate { get; set; }
        public string memReason { get; set; }
        public string memRemark { get; set; }
        public Nullable<System.DateTime> dTransDate { get; set; }
        public string sDeptName { get; set; }
        public Nullable<int> lDays { get; set; }
        public Nullable<double> dblAfterValue { get; set; }
        public Nullable<double> dblTransValue { get; set; }
        public string sMark { get; set; }
        public string sLockedBy { get; set; }
        public int PID { get; set; }
        public Nullable<double> dblCleanUpValTax { get; set; }
    }
}
