//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_AccDef
    {
        public int iid { get; set; }
        public string cAccID { get; set; }
        public string cAccName { get; set; }
        public string cIntrID { get; set; }
        public string cexch_name { get; set; }
        public Nullable<decimal> mqot { get; set; }
        public byte istate { get; set; }
        public string cUnitCode { get; set; }
        public byte itype { get; set; }
        public byte iio { get; set; }
        public string cCadID { get; set; }
        public byte iDataSrc { get; set; }
        public System.DateTime dOpenDate { get; set; }
        public Nullable<decimal> mb { get; set; }
        public Nullable<decimal> mh { get; set; }
        public Nullable<bool> bDestroy { get; set; }
        public string cAccBank { get; set; }
        public string accdef_id { get; set; }
        public string accunit_id { get; set; }
        public string irate_id { get; set; }
        public string cad_id { get; set; }
        public string yt_cad_id { get; set; }
        public Nullable<bool> iYt { get; set; }
        public string cYtID { get; set; }
        public Nullable<decimal> qcye_natural_mny { get; set; }
        public Nullable<decimal> qcjs_natural_mny { get; set; }
        public Nullable<bool> deficit_flag { get; set; }
        public Nullable<decimal> deficit_mny { get; set; }
        public Nullable<bool> deficitrestrict_flag { get; set; }
        public string digest { get; set; }
        public Nullable<bool> sngPayoutLmd_flag { get; set; }
        public Nullable<decimal> sngPayout_mny { get; set; }
        public Nullable<bool> payoutOver_flag { get; set; }
        public string bAccCode { get; set; }
        public string bAccName { get; set; }
        public string bAccBank { get; set; }
        public string gAccCode { get; set; }
        public string gAccName { get; set; }
        public string gAccBank { get; set; }
    }
}
