//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_CreDoc
    {
        public decimal group_id { get; set; }
        public string accunit_id { get; set; }
        public Nullable<System.DateTime> estDate { get; set; }
        public Nullable<System.DateTime> perStart { get; set; }
        public Nullable<System.DateTime> perEnd { get; set; }
        public string creClass { get; set; }
    }
}
