//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fitemstructure
    {
        public int i_id { get; set; }
        public string citem_class { get; set; }
        public byte citem_sqr { get; set; }
        public string cfield_name { get; set; }
        public string ctext { get; set; }
        public byte imode { get; set; }
        public byte itype { get; set; }
        public byte ilength { get; set; }
        public byte iscale { get; set; }
        public bool blist { get; set; }
        public bool bsum { get; set; }
        public bool bRef { get; set; }
        public byte iSubItem { get; set; }
        public Nullable<byte> iDefine { get; set; }
        public bool bPrimaryKey { get; set; }
        public Nullable<int> iSource { get; set; }
        public string cTableName { get; set; }
        public string cFieldName { get; set; }
        public short bOrderBy { get; set; }
        public Nullable<int> iWidth { get; set; }
        public Nullable<int> iAlign { get; set; }
    }
}
