//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class flt_Solution
    {
        public System.Guid ID { get; set; }
        public string FilterID { get; set; }
        public string SolutionName { get; set; }
        public bool IsDefault { get; set; }
        public string XMLExpression { get; set; }
        public bool IsPublic { get; set; }
        public string UserID { get; set; }
        public bool isSample { get; set; }
        public bool isAdvance { get; set; }
        public string LocaleID { get; set; }
        public string NewReportID { get; set; }
        public string cClassID { get; set; }
        public string AdvanceXMLExpression { get; set; }
        public string ViewId { get; set; }
        public string GroupId { get; set; }
        public Nullable<int> PageRowCount { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public string RunData { get; set; }
    }
}
