//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FM_Vouch
    {
        public string cBus_id { get; set; }
        public byte iPeriod { get; set; }
        public string cSign { get; set; }
        public string cNo_id { get; set; }
        public Nullable<short> inid { get; set; }
        public System.DateTime dDate { get; set; }
        public string cVouchType { get; set; }
        public string cVouch_id { get; set; }
    }
}
