//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formson_0473
    {
        public decimal id { get; set; }
        public Nullable<decimal> formmain_0472Id { get; set; }
        public string field0002 { get; set; }
        public string field0003 { get; set; }
        public string field0004 { get; set; }
        public string field0005 { get; set; }
        public string field0006 { get; set; }
        public Nullable<decimal> sort { get; set; }
    }
}
