//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_queryplan
    {
        public long id { get; set; }
        public long formappmain_id { get; set; }
        public string query_name { get; set; }
        public string plan_name { get; set; }
        public string plan_define { get; set; }
        public Nullable<short> plan_type { get; set; }
        public Nullable<long> user_id { get; set; }
    }
}
