//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formson_0196
    {
        public decimal id { get; set; }
        public Nullable<decimal> formmain_0194Id { get; set; }
        public string field0017 { get; set; }
        public string field0018 { get; set; }
        public Nullable<decimal> field0019 { get; set; }
        public Nullable<decimal> field0020 { get; set; }
        public Nullable<decimal> sort { get; set; }
        public Nullable<decimal> field0022 { get; set; }
    }
}
