//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_bf_column
    {
        public long id { get; set; }
        public string name { get; set; }
        public Nullable<byte> sort_id { get; set; }
        public Nullable<byte> category { get; set; }
        public Nullable<byte> parent_category { get; set; }
        public Nullable<long> form_biz_config_id { get; set; }
        public Nullable<long> form_id { get; set; }
    
        public virtual form_biz_config form_biz_config { get; set; }
    }
}
