//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_trigger_running
    {
        public long id { get; set; }
        public Nullable<long> summary_id { get; set; }
        public Nullable<long> form_appmain_id { get; set; }
        public Nullable<long> record_id { get; set; }
        public string trigger_config { get; set; }
        public string relation_condition { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<long> ext1 { get; set; }
        public string ext2 { get; set; }
        public string ext3 { get; set; }
    }
}
