//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_AccMultiAss
    {
        public int i_id { get; set; }
        public string ccode { get; set; }
        public string cexch_name { get; set; }
        public string cdept_id { get; set; }
        public string cperson_id { get; set; }
        public string ccus_id { get; set; }
        public string csup_id { get; set; }
        public string citem_class { get; set; }
        public string citem_id { get; set; }
        public string cname { get; set; }
        public string cDefine1 { get; set; }
        public string cDefine2 { get; set; }
        public string cDefine3 { get; set; }
        public Nullable<System.DateTime> cDefine4 { get; set; }
        public Nullable<int> cDefine5 { get; set; }
        public Nullable<System.DateTime> cDefine6 { get; set; }
        public Nullable<double> cDefine7 { get; set; }
        public string cDefine8 { get; set; }
        public string cDefine9 { get; set; }
        public string cDefine10 { get; set; }
        public string cDefine11 { get; set; }
        public string cDefine12 { get; set; }
        public string cDefine13 { get; set; }
        public string cDefine14 { get; set; }
        public Nullable<int> cDefine15 { get; set; }
        public Nullable<double> cDefine16 { get; set; }
        public Nullable<byte> iperiod { get; set; }
        public Nullable<decimal> mb { get; set; }
        public Nullable<decimal> md { get; set; }
        public Nullable<decimal> addmd { get; set; }
        public Nullable<decimal> mc { get; set; }
        public Nullable<decimal> addmc { get; set; }
        public Nullable<decimal> me { get; set; }
        public Nullable<decimal> mb_f { get; set; }
        public Nullable<decimal> md_f { get; set; }
        public Nullable<decimal> addmd_f { get; set; }
        public Nullable<decimal> mc_f { get; set; }
        public Nullable<decimal> addmc_f { get; set; }
        public Nullable<decimal> me_f { get; set; }
        public Nullable<double> nb_s { get; set; }
        public Nullable<double> nd_s { get; set; }
        public Nullable<double> addnd_s { get; set; }
        public Nullable<double> nc_s { get; set; }
        public Nullable<double> addnc_s { get; set; }
        public Nullable<double> ne_s { get; set; }
        public Nullable<short> iyear { get; set; }
        public Nullable<int> iYPeriod { get; set; }
    }
}
