//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_BatchPZSet
    {
        public int Inid { get; set; }
        public string UserName { get; set; }
        public byte Iperiod { get; set; }
        public Nullable<int> MaxPZNo { get; set; }
        public string FCCode { get; set; }
        public Nullable<int> PZCount { get; set; }
        public string KmDirect { get; set; }
        public Nullable<double> Qantity { get; set; }
        public Nullable<decimal> FCValue { get; set; }
        public Nullable<decimal> LCValue { get; set; }
        public string csign { get; set; }
    }
}
