//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_MRColumnDic_Main
    {
        public string cKey { get; set; }
        public Nullable<bool> bAfterItem { get; set; }
        public Nullable<bool> bCrossShow { get; set; }
        public Nullable<int> iOrder { get; set; }
        public string cField { get; set; }
        public Nullable<bool> bSum { get; set; }
        public Nullable<bool> bAmountSum { get; set; }
        public Nullable<bool> bForeignSum { get; set; }
        public Nullable<bool> bAmountForeign { get; set; }
        public Nullable<bool> bTotal { get; set; }
        public Nullable<bool> bPeriodNetTotal { get; set; }
        public Nullable<bool> bYearNetTotal { get; set; }
        public string cCaption { get; set; }
        public Nullable<int> iAlign { get; set; }
        public Nullable<int> iColWidth { get; set; }
        public Nullable<bool> bMustSelect { get; set; }
    }
}
