//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_MRReportOption
    {
        public int iReportID { get; set; }
        public Nullable<int> cCodeLevel { get; set; }
        public Nullable<int> cCodeLen { get; set; }
        public Nullable<int> cDeptLevel { get; set; }
        public Nullable<int> cDeptLen { get; set; }
        public Nullable<int> cCCLevel { get; set; }
        public Nullable<int> cCCLen { get; set; }
        public Nullable<int> cVCLevel { get; set; }
        public Nullable<int> cVCLen { get; set; }
        public Nullable<int> cItemCLevel { get; set; }
        public Nullable<int> cItemCLen { get; set; }
        public Nullable<int> cDistCLevel { get; set; }
        public Nullable<int> cDistCLen { get; set; }
        public Nullable<bool> bAcc { get; set; }
        public Nullable<bool> bTotal { get; set; }
        public Nullable<bool> bMonthSubTotal { get; set; }
        public Nullable<bool> bPeriodNetOccur { get; set; }
        public Nullable<bool> bYearNetOccur { get; set; }
        public Nullable<int> iNotShow { get; set; }
        public Nullable<int> iPrice { get; set; }
        public Nullable<bool> bDeptInclude { get; set; }
        public bool bCusName { get; set; }
        public bool bVenName { get; set; }
    }
}
