//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_PrintEx_Client
    {
        public string cSystemName { get; set; }
        public string cSystemSubNum { get; set; }
        public int nTableNum { get; set; }
        public string cTableName { get; set; }
        public string cTableCode { get; set; }
        public string cPaperType { get; set; }
        public bool bOrientation { get; set; }
        public Nullable<byte> iTitleRes { get; set; }
        public string cResPathHead { get; set; }
        public string cResPathTail { get; set; }
        public Nullable<int> iSelfDefWidth { get; set; }
        public Nullable<int> iselfDefHeight { get; set; }
        public Nullable<int> iLeftMargin { get; set; }
        public Nullable<int> iRightMargin { get; set; }
        public Nullable<int> iBottomMargin { get; set; }
        public Nullable<int> iTopMargin { get; set; }
        public string cStation { get; set; }
    }
}
