//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_ViewItem
    {
        public int iID { get; set; }
        public string cTitleName { get; set; }
        public string cQcQmName { get; set; }
        public string cTJFS { get; set; }
        public string cCode1 { get; set; }
        public string cCode2 { get; set; }
        public string cCode3 { get; set; }
        public string cCode4 { get; set; }
        public string cCode5 { get; set; }
    }
}
