//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSP_VOUCHERREF
    {
        public decimal ID { get; set; }
        public string CVOUCHTYPE { get; set; }
        public string CAPPNAME { get; set; }
        public string COTHERTYPE { get; set; }
        public string COTHERSYS { get; set; }
        public string CUSERCHECK { get; set; }
        public string CREPNAME { get; set; }
        public string CVOUCHNAME { get; set; }
        public string COTHERNAME { get; set; }
        public string CMAINFIELD { get; set; }
        public Nullable<bool> BDEFAULT { get; set; }
    }
}
