//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSP_VOUCHBLIGHT
    {
        public int ID { get; set; }
        public Nullable<int> INATIVE { get; set; }
        public string CBLIGHTBEHAVE { get; set; }
        public string CBLIGHTDISPOSE { get; set; }
        public Nullable<int> IBLIGHTRESULE { get; set; }
        public string CBEHAVE1 { get; set; }
        public string CBEHAVE2 { get; set; }
        public string CDEADREASON { get; set; }
        public string CPERSON { get; set; }
        public Nullable<int> IPROVINCE { get; set; }
        public string CEVERAILMENT { get; set; }
        public string CPROVINCESIGNATURE { get; set; }
        public string CNATIVESIGNATURE { get; set; }
        public string CINNER { get; set; }
        public string COUTER { get; set; }
        public string COTHER { get; set; }
        public string CDUTY { get; set; }
        public Nullable<int> IEVERINFECT { get; set; }
        public string CWEIGHT { get; set; }
        public string CID { get; set; }
        public string CMANUFACTURER { get; set; }
        public string CTEL { get; set; }
        public Nullable<System.DateTime> DDATE { get; set; }
        public string CNAME { get; set; }
        public string CSEX { get; set; }
        public Nullable<System.DateTime> CBLIGHTDATE { get; set; }
        public string CNATION { get; set; }
        public string CBLIGHTNAME { get; set; }
        public Nullable<int> IBLIGHT { get; set; }
        public string CCASEID { get; set; }
        public string CADDRESS { get; set; }
        public string CPERSONTEL { get; set; }
        public Nullable<int> IEVERBLIGHT { get; set; }
        public Nullable<System.DateTime> DDEADDATE { get; set; }
        public Nullable<System.DateTime> DBIRTH { get; set; }
        public Nullable<bool> BDEAD { get; set; }
        public Nullable<bool> BISURGENT { get; set; }
        public byte[] UFTS { get; set; }
        public string CVOUCHTYPE { get; set; }
        public Nullable<int> IVTID { get; set; }
        public string CDEFINE1 { get; set; }
        public string CDEFINE2 { get; set; }
        public string CDEFINE3 { get; set; }
        public string CDEFINE4 { get; set; }
        public string CDEFINE5 { get; set; }
        public Nullable<System.DateTime> CDEFINE6 { get; set; }
        public Nullable<bool> BREFER { get; set; }
        public string CVERIFIER { get; set; }
    }
}
