//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSP_VOUCHUNSALABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GSP_VOUCHUNSALABLE()
        {
            this.GSP_VOUCHSUNSALABLE = new HashSet<GSP_VOUCHSUNSALABLE>();
        }
    
        public int ID { get; set; }
        public string cVouchCode { get; set; }
        public string cVouchType { get; set; }
        public string cDepCode { get; set; }
        public Nullable<System.DateTime> dDate { get; set; }
        public Nullable<int> iRdId { get; set; }
        public string cRdCode { get; set; }
        public Nullable<System.DateTime> dArvdate { get; set; }
        public string cVenCode { get; set; }
        public string cRdMaker { get; set; }
        public string cMaker { get; set; }
        public string cVerifier { get; set; }
        public string cMemo { get; set; }
        public string cWhCode { get; set; }
        public Nullable<bool> bRefer { get; set; }
        public byte[] Ufts { get; set; }
        public Nullable<int> Vt_id { get; set; }
        public string cDefine1 { get; set; }
        public string cDefine2 { get; set; }
        public string cDefine3 { get; set; }
        public Nullable<System.DateTime> cDefine4 { get; set; }
        public Nullable<int> cDefine5 { get; set; }
        public Nullable<System.DateTime> cDefine6 { get; set; }
        public Nullable<decimal> cDefine7 { get; set; }
        public string cDefine8 { get; set; }
        public string cDefine9 { get; set; }
        public string cDefine10 { get; set; }
        public string cDefine11 { get; set; }
        public string cDefine12 { get; set; }
        public string cDefine13 { get; set; }
        public string cDefine14 { get; set; }
        public Nullable<int> cDefine15 { get; set; }
        public Nullable<decimal> cDefine16 { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GSP_VOUCHSUNSALABLE> GSP_VOUCHSUNSALABLE { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
