//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSP_VOUCHCONDUCTSUM
    {
        public string CSUM { get; set; }
        public Nullable<int> INUMBER { get; set; }
        public Nullable<int> IQUARTER { get; set; }
        public Nullable<System.DateTime> DCHKDATE { get; set; }
        public string CAVRRATE { get; set; }
        public string CALLRATE { get; set; }
        public string CPROBABILITY { get; set; }
        public int ID { get; set; }
        public string CVOUCHTYPE { get; set; }
        public byte[] UFTS { get; set; }
        public Nullable<int> IVTID { get; set; }
        public string CID { get; set; }
        public string CMAKER { get; set; }
        public string CVERIFIER { get; set; }
        public string CDEFINE1 { get; set; }
        public string CDEFINE2 { get; set; }
        public string CDEFINE3 { get; set; }
        public Nullable<System.DateTime> CDEFINE4 { get; set; }
        public Nullable<int> CDEFINE5 { get; set; }
        public Nullable<System.DateTime> CDEFINE6 { get; set; }
        public Nullable<decimal> CDEFINE7 { get; set; }
        public string CDEFINE8 { get; set; }
        public string CDEFINE9 { get; set; }
        public string CDEFINE10 { get; set; }
        public string CDEFINE11 { get; set; }
        public string CDEFINE12 { get; set; }
        public string CDEFINE13 { get; set; }
        public string CDEFINE14 { get; set; }
        public Nullable<int> CDEFINE15 { get; set; }
        public Nullable<decimal> CDEFINE16 { get; set; }
    }
}
