//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HB_SampleOperate
    {
        public int SampleOperateID { get; set; }
        public string AssignFirmCode { get; set; }
        public string OperatorID { get; set; }
        public string Hypo_FirmCode { get; set; }
        public Nullable<int> SampleID { get; set; }
        public Nullable<System.DateTime> AssignTime { get; set; }
        public string ReportNotice { get; set; }
        public string IsAccurate { get; set; }
        public string IsMustAudite { get; set; }
        public string IsCancel { get; set; }
        public byte[] TableStamp { get; set; }
    }
}
