//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_BD_DeptAuthSet
    {
        public string cFuncId { get; set; }
        public string cFunName { get; set; }
        public string cParentFun { get; set; }
        public string cStar { get; set; }
        public string cStarRegion { get; set; }
        public string IsUseRegion { get; set; }
        public Nullable<int> iShowOrder { get; set; }
    }
}
