//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_hi_log_list
    {
        public System.Guid Pk_hr_hi_log_list { get; set; }
        public Nullable<System.Guid> rNodeID { get; set; }
        public string rTableName { get; set; }
        public string cfieldID { get; set; }
        public string cfieldName { get; set; }
        public string coldInfo { get; set; }
        public string cnewInfo { get; set; }
    
        public virtual hr_hi_log hr_hi_log { get; set; }
    }
}
