//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_hi_Enter_WM
    {
        public System.Guid PK_hr_hi_Enter_WM { get; set; }
        public string cpsn_num { get; set; }
        public string cdepcode { get; set; }
        public string vbooncode { get; set; }
        public string vpaymonth { get; set; }
        public string daccountdate { get; set; }
        public string vpaymonthDesc { get; set; }
        public string cYear { get; set; }
        public Nullable<int> iaccountflag { get; set; }
        public string CRegion { get; set; }
        public string BaseType { get; set; }
        public Nullable<bool> bThanLimit { get; set; }
        public Nullable<bool> bSFJT { get; set; }
        public Nullable<bool> bGZKC { get; set; }
        public string VoucherID { get; set; }
    }
}
