//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_HI_Transfer_WAItem
    {
        public System.Guid PK_HR_HI_Transfer_WAItem { get; set; }
        public string Cpsn_Num { get; set; }
        public string WaItem { get; set; }
        public Nullable<double> WaItemValue { get; set; }
        public string WaItemBeginDate { get; set; }
        public string WaItemMonth { get; set; }
        public Nullable<int> cRealMonth { get; set; }
        public Nullable<int> CheckFlag { get; set; }
        public string cYear { get; set; }
        public string VoucherID { get; set; }
    }
}
