//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_hi_probation
    {
        public System.Guid PK_hr_hi_probation { get; set; }
        public string cPsn_Num { get; set; }
        public Nullable<int> iRecordID { get; set; }
        public bool blastflag { get; set; }
        public string vstatus1 { get; set; }
        public Nullable<decimal> nstatus2 { get; set; }
        public string dBeginDate { get; set; }
        public string dEndDate { get; set; }
        public byte[] mWorkSummary { get; set; }
        public string mWorkSummaryqpb { get; set; }
        public string rMentor { get; set; }
        public string rCheckResult { get; set; }
        public string vCheckOpinion { get; set; }
        public string vMentorOpinion { get; set; }
    }
}
