//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_hi_person_back
    {
        public string cPsn_Num { get; set; }
        public string cPsn_Name { get; set; }
        public string cDept_num { get; set; }
        public Nullable<int> iRecordID { get; set; }
        public string rPersonType { get; set; }
        public string rSex { get; set; }
        public string dBirthDate { get; set; }
        public string rNativePlace { get; set; }
        public string rNational { get; set; }
        public string rhealthStatus { get; set; }
        public string rMarriStatus { get; set; }
        public string vIDNo { get; set; }
        public byte[] MPicture { get; set; }
        public string rPerResidence { get; set; }
        public string vAliaName { get; set; }
        public string dJoinworkDate { get; set; }
        public string dEnterDate { get; set; }
        public string dRegularDate { get; set; }
        public string rBusinessSort { get; set; }
        public string rWorkMajor { get; set; }
        public string rEmigFlag { get; set; }
        public string vSSNo { get; set; }
        public string rPerStatus { get; set; }
        public string rworkAttend { get; set; }
        public string vCardNo { get; set; }
        public string rtbmRule { get; set; }
        public Nullable<int> iRegisterType { get; set; }
        public string rCheckInFlag { get; set; }
        public string dLastDate { get; set; }
        public byte[] hrts { get; set; }
        public string vstatus1 { get; set; }
        public Nullable<decimal> nstatus2 { get; set; }
        public bool bPsnPerson { get; set; }
        public string cPsnMobilePhone { get; set; }
        public string cPsnFPhone { get; set; }
        public string cPsnOPhone { get; set; }
        public string cPsnInPhone { get; set; }
        public string cPsnEmail { get; set; }
        public string cPsnPostAddr { get; set; }
        public string cPsnPostCode { get; set; }
        public string cPsnFAddr { get; set; }
        public string cPsnQQCode { get; set; }
        public string cPsnURL { get; set; }
        public string CpsnOSeat { get; set; }
        public string dEnterUnitDate { get; set; }
        public string cPsnProperty { get; set; }
        public string cPsnBankCode { get; set; }
        public string cPsnAccount { get; set; }
        public System.Guid pk_hr_hi_person { get; set; }
        public Nullable<bool> bProbation { get; set; }
        public string cDutyclass { get; set; }
        public Nullable<bool> bTakeTM { get; set; }
        public string MPictureqpb { get; set; }
        public string newPsn_Num { get; set; }
    }
}
