//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_om_dutydesc
    {
        public System.Guid pk_hr_om_dutydesc { get; set; }
        public string cDutycode { get; set; }
        public Nullable<int> irecordID { get; set; }
        public Nullable<bool> blastflag { get; set; }
        public string vstatus1 { get; set; }
        public Nullable<decimal> nstatus2 { get; set; }
        public string vreqedu { get; set; }
        public string vreqsex { get; set; }
        public string vreqyold { get; set; }
        public string vreqpro { get; set; }
        public string vreqexp { get; set; }
        public string vreqtlimit { get; set; }
    }
}
