//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_PF_Target
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_PF_Target()
        {
            this.HR_PF_ActionPlan = new HashSet<HR_PF_ActionPlan>();
            this.HR_PF_ActionPlanData = new HashSet<HR_PF_ActionPlanData>();
            this.HR_PF_AppraiseData = new HashSet<HR_PF_AppraiseData>();
            this.HR_PF_Formula = new HashSet<HR_PF_Formula>();
            this.HR_PF_FormulaTarget = new HashSet<HR_PF_FormulaTarget>();
            this.HR_PF_FormulaTargetRelation = new HashSet<HR_PF_FormulaTargetRelation>();
            this.HR_PF_GoalChangeChild = new HashSet<HR_PF_GoalChangeChild>();
            this.HR_PF_OperationFormula = new HashSet<HR_PF_OperationFormula>();
            this.HR_PF_PersonTableStructure = new HashSet<HR_PF_PersonTableStructure>();
            this.HR_PF_ResultChangeTargetChild = new HashSet<HR_PF_ResultChangeTargetChild>();
            this.HR_PF_SchemaGoalValidateRule = new HashSet<HR_PF_SchemaGoalValidateRule>();
            this.HR_PF_SchemaNoteTemplate = new HashSet<HR_PF_SchemaNoteTemplate>();
            this.HR_PF_SchemaTableStructure = new HashSet<HR_PF_SchemaTableStructure>();
            this.HR_PF_SchemaTarget = new HashSet<HR_PF_SchemaTarget>();
            this.HR_PF_TableData = new HashSet<HR_PF_TableData>();
            this.HR_PF_TableTarget = new HashSet<HR_PF_TableTarget>();
        }
    
        public string cTargetCode { get; set; }
        public string cTargetName { get; set; }
        public string cTargetClassCode { get; set; }
        public string cTargetExplain { get; set; }
        public string cCheckStandard { get; set; }
        public Nullable<int> iGrade { get; set; }
        public byte[] tStamp { get; set; }
        public string cDefine1 { get; set; }
        public string cDefine2 { get; set; }
        public string cDefine3 { get; set; }
        public string cDeptNums { get; set; }
        public Nullable<bool> bIsUsed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_ActionPlan> HR_PF_ActionPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_ActionPlanData> HR_PF_ActionPlanData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_AppraiseData> HR_PF_AppraiseData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_Formula> HR_PF_Formula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_FormulaTarget> HR_PF_FormulaTarget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_FormulaTargetRelation> HR_PF_FormulaTargetRelation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_GoalChangeChild> HR_PF_GoalChangeChild { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_OperationFormula> HR_PF_OperationFormula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_PersonTableStructure> HR_PF_PersonTableStructure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_ResultChangeTargetChild> HR_PF_ResultChangeTargetChild { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_SchemaGoalValidateRule> HR_PF_SchemaGoalValidateRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_SchemaNoteTemplate> HR_PF_SchemaNoteTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_SchemaTableStructure> HR_PF_SchemaTableStructure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_SchemaTarget> HR_PF_SchemaTarget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_TableData> HR_PF_TableData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_TableTarget> HR_PF_TableTarget { get; set; }
        public virtual HR_PF_TargetClass HR_PF_TargetClass { get; set; }
    }
}
