//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_PF_PlanWorkFlow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_PF_PlanWorkFlow()
        {
            this.HR_PF_PlanWorkFlowDimensionality = new HashSet<HR_PF_PlanWorkFlowDimensionality>();
        }
    
        public System.Guid uPlanWorkFlowPK { get; set; }
        public string cPlanCode { get; set; }
        public short sWorkStep { get; set; }
        public int iStepSerialnumber { get; set; }
        public string cActivityName { get; set; }
        public bool bMailInform { get; set; }
        public bool bNoteInform { get; set; }
        public bool bIsEdit { get; set; }
        public System.DateTime dBeginTime { get; set; }
        public System.DateTime dEndTime { get; set; }
        public string cCodeID { get; set; }
        public Nullable<short> sRelationToCheckperson { get; set; }
        public byte[] tStamp { get; set; }
        public string cDefine1 { get; set; }
        public string cDefine2 { get; set; }
        public string cDefine3 { get; set; }
    
        public virtual HR_CT050 HR_CT050 { get; set; }
        public virtual HR_PF_Plan HR_PF_Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_PlanWorkFlowDimensionality> HR_PF_PlanWorkFlowDimensionality { get; set; }
    }
}
