//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_PF_GradeManner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_PF_GradeManner()
        {
            this.HR_PF_ForceDistributeRule = new HashSet<HR_PF_ForceDistributeRule>();
            this.HR_PF_GradeMannerRating = new HashSet<HR_PF_GradeMannerRating>();
            this.HR_PF_SchemaTarget = new HashSet<HR_PF_SchemaTarget>();
        }
    
        public string cGradeMannerCode { get; set; }
        public string cGradeMannerName { get; set; }
        public short sType { get; set; }
        public Nullable<decimal> fUpperlimit { get; set; }
        public Nullable<decimal> fLowerlimit { get; set; }
        public string cRemark { get; set; }
        public byte[] tStamp { get; set; }
        public string cDefine1 { get; set; }
        public string cDefine2 { get; set; }
        public string cDefine3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_ForceDistributeRule> HR_PF_ForceDistributeRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_GradeMannerRating> HR_PF_GradeMannerRating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PF_SchemaTarget> HR_PF_SchemaTarget { get; set; }
    }
}
