//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_PF_TableTargetDimensionality
    {
        public System.Guid uTableTargetDimensionalityPK { get; set; }
        public System.Guid uTableTargetPK { get; set; }
        public string cDimensionalityCode { get; set; }
        public decimal fWeight { get; set; }
        public string cPsn_num { get; set; }
        public Nullable<decimal> fPsnWeight { get; set; }
        public byte[] tStamp { get; set; }
        public string cDefine1 { get; set; }
        public string cDefine2 { get; set; }
        public string cDefine3 { get; set; }
    
        public virtual hr_hi_person hr_hi_person { get; set; }
        public virtual HR_PF_Dimensionality HR_PF_Dimensionality { get; set; }
        public virtual HR_PF_TableTarget HR_PF_TableTarget { get; set; }
    }
}
