//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_rt_abiltrai
    {
        public System.Guid PK_hr_rt_abiltrai { get; set; }
        public string cAbBillNo { get; set; }
        public string cbusinessid { get; set; }
        public string rtra_Type { get; set; }
        public string rtra_chara { get; set; }
        public string rtra_mode { get; set; }
        public string dbegindate { get; set; }
        public string denddate { get; set; }
        public Nullable<int> itra_time { get; set; }
        public string vtra_content { get; set; }
        public string vtra_className { get; set; }
        public string vtra_act { get; set; }
        public Nullable<decimal> ntra_cost { get; set; }
        public Nullable<decimal> ntra_score { get; set; }
        public string rtra_result { get; set; }
        public string vChargeUnit { get; set; }
        public string rcuType { get; set; }
        public string vStudyUnit { get; set; }
        public string rsuType { get; set; }
        public Nullable<int> iRecordID { get; set; }
        public string bLastFlag { get; set; }
        public string vStatus1 { get; set; }
        public Nullable<decimal> nStatus2 { get; set; }
        public string cVoucherId { get; set; }
    }
}
