//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_rt_abilitypsn
    {
        public Nullable<System.Guid> pk_hr_rt_abilitypsn { get; set; }
        public string cAbBusinessId { get; set; }
        public string cAbBillNo { get; set; }
        public string dAbMakeDate { get; set; }
        public string cAbMaker { get; set; }
        public string cAbVerifier { get; set; }
        public string dAbVerifyDate { get; set; }
        public string vAbVerifyNote { get; set; }
        public string cAbInvalider { get; set; }
        public string vAbMemo { get; set; }
        public byte[] ufts { get; set; }
        public string vName { get; set; }
        public string rSex { get; set; }
        public string dBirthDate { get; set; }
        public string rNation { get; set; }
        public string rWedlock { get; set; }
        public Nullable<decimal> nDesiredSalary { get; set; }
        public string rHouseRegister { get; set; }
        public string rNativePlace { get; set; }
        public string vIDCardNo { get; set; }
        public string rMaxEdu { get; set; }
        public string vSpecialty { get; set; }
        public string vSchool { get; set; }
        public string dGraDate { get; set; }
        public string vContactAddr { get; set; }
        public string eEmail { get; set; }
        public string vPhone { get; set; }
        public string vMobile { get; set; }
        public string dReceDate { get; set; }
        public string vRelaDispose { get; set; }
        public Nullable<bool> bHaveRela { get; set; }
        public string vRelaName { get; set; }
        public string vSelfAssessment { get; set; }
        public byte[] mPhoto { get; set; }
        public string mPhotoqpb { get; set; }
        public string dJoinJob { get; set; }
        public string vPostCode { get; set; }
        public string vExpeDate { get; set; }
        public string rAbilityPsnType { get; set; }
    }
}
