//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_rt_register
    {
        public Nullable<System.Guid> pk_hr_rt_register { get; set; }
        public string cBusinessId { get; set; }
        public string cBillNo { get; set; }
        public string dMakeDate { get; set; }
        public string cMaker { get; set; }
        public string cVerifier { get; set; }
        public string dVerifyDate { get; set; }
        public string vVerifyNote { get; set; }
        public string cInvalider { get; set; }
        public string vMemo { get; set; }
        public byte[] hrts { get; set; }
        public string blinkplan { get; set; }
        public string cPlanCode { get; set; }
        public string vSourceType { get; set; }
        public string cAbBillNo { get; set; }
        public string cDeptCode { get; set; }
        public string cJobCode { get; set; }
        public string rChanCode { get; set; }
        public string vStatus { get; set; }
        public Nullable<bool> bIsReport { get; set; }
        public Nullable<int> iRecordID { get; set; }
        public string bLastFlag { get; set; }
        public string cPsn_Num { get; set; }
        public string dEmployDate { get; set; }
        public string cAdmiteCode { get; set; }
    }
}
