//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_rt_abiledu
    {
        public System.Guid PK_hr_rt_abiledu { get; set; }
        public string cAbBillNo { get; set; }
        public string cbusinessid { get; set; }
        public string dentranceDate { get; set; }
        public string dgrduateDate { get; set; }
        public string vschool { get; set; }
        public string rmajor { get; set; }
        public Nullable<decimal> nedusystem { get; set; }
        public string rstudymode { get; set; }
        public string reducation { get; set; }
        public string rdegree { get; set; }
        public string ddegreedate { get; set; }
        public string vdegreeunit { get; set; }
        public string vcertifcode { get; set; }
        public string vmemo { get; set; }
        public Nullable<int> iRecordID { get; set; }
        public string bLastFlag { get; set; }
        public string vStatus1 { get; set; }
        public Nullable<decimal> nStatus2 { get; set; }
    }
}
