//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_staff_relationship
    {
        public long id { get; set; }
        public Nullable<long> member_id { get; set; }
        public string relationship { get; set; }
        public string name { get; set; }
        public string organization { get; set; }
        public string post { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<int> political_position { get; set; }
    }
}
