//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_tm_RestDay
    {
        public System.Guid uRecordId { get; set; }
        public string cCode { get; set; }
        public string dRestDate { get; set; }
        public string vRestName { get; set; }
        public string rDateProperty { get; set; }
        public string vMemo { get; set; }
    
        public virtual hr_tm_RestType hr_tm_RestType { get; set; }
    }
}
