//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_tm_OverTimeType
    {
        public string cCode { get; set; }
        public string vName { get; set; }
        public Nullable<bool> bSumTime { get; set; }
        public Nullable<bool> bCountTime { get; set; }
        public string vSumField { get; set; }
        public string vCountField { get; set; }
        public Nullable<bool> bOverInLegalHoliday { get; set; }
        public Nullable<bool> bCanDeduct { get; set; }
        public Nullable<decimal> nDeductQuotiety { get; set; }
        public string vPreSumOverField { get; set; }
        public string vCurOverDeductField { get; set; }
        public string vCurSumOverField { get; set; }
        public string vCurBalanceOverField { get; set; }
        public Nullable<int> iDeductSequence { get; set; }
        public string vMemo { get; set; }
        public Nullable<int> iOvertimeUse { get; set; }
        public Nullable<int> bDayCanDeduct { get; set; }
        public Nullable<int> iDayDeductSequence { get; set; }
    }
}
