//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_TM_WorkCalendar
    {
        public System.Guid uPK { get; set; }
        public string cDept_num { get; set; }
        public System.DateTime dDate { get; set; }
        public int rDateProperty { get; set; }
        public bool bRoot { get; set; }
        public bool bReadOnly { get; set; }
    }
}
