//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_wa_pay_temp
    {
        public System.Guid PK_hr_wa_pay_temp { get; set; }
        public string cPsn_Num { get; set; }
        public Nullable<int> iRecordID { get; set; }
        public bool blastflag { get; set; }
        public string vstatus1 { get; set; }
        public Nullable<decimal> nstatus2 { get; set; }
        public string csalarygrade { get; set; }
        public string csalarylevel { get; set; }
        public Nullable<decimal> nbasesalary { get; set; }
        public Nullable<decimal> ndutysalary { get; set; }
        public Nullable<decimal> nlevelsalary { get; set; }
        public Nullable<decimal> nagesalary { get; set; }
        public Nullable<decimal> ntrysalary { get; set; }
        public Nullable<decimal> nbackshish { get; set; }
        public string csalaryleveltype { get; set; }
        public Nullable<decimal> ngradesalary { get; set; }
        public Nullable<decimal> njobsubsidy { get; set; }
        public string JobNumber { get; set; }
    }
}
