//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_wm_docu_wm13_old
    {
        public System.Guid pk_wm_docu_wm13 { get; set; }
        public string vdocuyear { get; set; }
        public string vdocumonth { get; set; }
        public string cpsn_num { get; set; }
        public string cpsn_name { get; set; }
        public string cdepcode { get; set; }
        public string vcumputercode { get; set; }
        public string vensurecode { get; set; }
        public Nullable<decimal> ncustbase { get; set; }
        public Nullable<decimal> ninviscale { get; set; }
        public Nullable<decimal> ncorpscale { get; set; }
        public Nullable<decimal> ncorppullscale { get; set; }
        public string vstartpaydate { get; set; }
        public string daccountdate { get; set; }
        public string dstartdate { get; set; }
        public string denddate { get; set; }
        public Nullable<int> itotalpaymon { get; set; }
        public string baccountflag { get; set; }
        public string vaddcause { get; set; }
        public string vreducause { get; set; }
        public string bswitchflag { get; set; }
        public string dswitchindate { get; set; }
        public string vswitchinunit { get; set; }
        public string dkeepdate { get; set; }
        public string dopendate { get; set; }
        public string ddestroydate { get; set; }
        public string dswitchoutdate { get; set; }
        public string vswitchoutunit { get; set; }
        public byte[] hrts { get; set; }
        public string rperclass { get; set; }
        public Nullable<int> iRecordID { get; set; }
        public string blastflag { get; set; }
        public string vstatus1 { get; set; }
        public Nullable<decimal> nstatus2 { get; set; }
        public string rpersontype { get; set; }
    }
}
