//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_wm_typeset
    {
        public System.Guid pk_wm_typeset { get; set; }
        public string vtypecode { get; set; }
        public string vtypename { get; set; }
        public string vbooncode { get; set; }
        public Nullable<decimal> napportscal { get; set; }
        public string vpzclass { get; set; }
        public byte[] hrts { get; set; }
    }
}
