//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_wm_itemset_base
    {
        public string citemcode { get; set; }
        public string vitemname { get; set; }
        public string vitemclscode { get; set; }
        public string vitemprop { get; set; }
        public string vpayercode { get; set; }
        public Nullable<bool> bAddup { get; set; }
        public string cParentCode { get; set; }
        public Nullable<bool> bsys { get; set; }
        public string LocaleID { get; set; }
    }
}
