//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HY_DZ_HU_ConsultPrices_Limit
    {
        public string cCode { get; set; }
        public string cInvCode { get; set; }
        public Nullable<double> iLow { get; set; }
        public Nullable<double> iUpper { get; set; }
        public Nullable<double> iPrice { get; set; }
        public Nullable<decimal> iPriceTax { get; set; }
        public Nullable<double> iTax { get; set; }
        public int iNum { get; set; }
        public string cVenCode { get; set; }
        public string cexch_code { get; set; }
        public string free1 { get; set; }
        public string free2 { get; set; }
        public string free3 { get; set; }
        public string free4 { get; set; }
        public string free5 { get; set; }
        public string free6 { get; set; }
        public string free7 { get; set; }
        public string free8 { get; set; }
        public string free9 { get; set; }
        public string free10 { get; set; }
        public long AutoID { get; set; }
    }
}
