//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HY_DZ_HU_ConsultPrices
    {
        public long AutoID { get; set; }
        public long ID { get; set; }
        public string cCodeZ { get; set; }
        public int iRowNo { get; set; }
        public int IDPlan { get; set; }
        public string cCodePlan { get; set; }
        public Nullable<double> iTaxRate { get; set; }
        public string cInvCode { get; set; }
        public Nullable<int> partid { get; set; }
        public Nullable<double> iQuantity { get; set; }
        public Nullable<double> iLowerLimit { get; set; }
        public Nullable<double> iUpperLimit { get; set; }
        public Nullable<double> iUnitPrice { get; set; }
        public Nullable<decimal> iUnitPriceTax { get; set; }
        public Nullable<double> iOkPrice { get; set; }
        public Nullable<decimal> OkPrice { get; set; }
        public Nullable<System.DateTime> Ddate { get; set; }
        public Nullable<System.DateTime> EffectDate { get; set; }
        public string Remarks { get; set; }
        public int PUID { get; set; }
        public Nullable<decimal> fnum { get; set; }
        public string cinva_unitcode { get; set; }
        public Nullable<decimal> iinvexchrate { get; set; }
        public string cdefine22 { get; set; }
        public string cdefine23 { get; set; }
        public string cdefine24 { get; set; }
        public string cdefine25 { get; set; }
        public Nullable<double> cdefine26 { get; set; }
        public Nullable<double> cdefine27 { get; set; }
        public string cdefine28 { get; set; }
        public string cdefine29 { get; set; }
        public string cdefine30 { get; set; }
        public string cdefine31 { get; set; }
        public string cdefine32 { get; set; }
        public string cdefine33 { get; set; }
        public Nullable<int> cdefine34 { get; set; }
        public Nullable<int> cdefine35 { get; set; }
        public Nullable<System.DateTime> cdefine36 { get; set; }
        public Nullable<System.DateTime> cdefine37 { get; set; }
        public string cbsysbarcode { get; set; }
        public string cItem_class { get; set; }
        public string cItemCode { get; set; }
        public string cItemName { get; set; }
    }
}
