//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hy_scrapreports
    {
        public int autoid { get; set; }
        public int id { get; set; }
        public string cinvcode { get; set; }
        public string cFree1 { get; set; }
        public string cFree2 { get; set; }
        public string cFree3 { get; set; }
        public string cFree4 { get; set; }
        public string cFree5 { get; set; }
        public string cFree6 { get; set; }
        public string cFree7 { get; set; }
        public string cFree8 { get; set; }
        public string cFree9 { get; set; }
        public string cFree10 { get; set; }
        public string cDefine22 { get; set; }
        public string cDefine23 { get; set; }
        public string cDefine24 { get; set; }
        public string cDefine25 { get; set; }
        public Nullable<double> cDefine26 { get; set; }
        public Nullable<double> cDefine27 { get; set; }
        public string cDefine28 { get; set; }
        public string cDefine29 { get; set; }
        public string cDefine30 { get; set; }
        public string cDefine31 { get; set; }
        public string cDefine32 { get; set; }
        public string cDefine33 { get; set; }
        public Nullable<int> cDefine34 { get; set; }
        public Nullable<int> cDefine35 { get; set; }
        public Nullable<System.DateTime> cDefine36 { get; set; }
        public Nullable<System.DateTime> cDefine37 { get; set; }
        public string cOutOpCode { get; set; }
        public Nullable<int> iOutStatus { get; set; }
        public Nullable<int> imoautoid { get; set; }
        public string copcode { get; set; }
        public string cdescription { get; set; }
        public string cmocode { get; set; }
        public Nullable<decimal> fOpScrapQuantity { get; set; }
        public Nullable<decimal> fMaScrapQuantity { get; set; }
        public Nullable<decimal> finlostQuantity { get; set; }
        public Nullable<decimal> flostQuantity { get; set; }
        public Nullable<decimal> fRedoQuantity { get; set; }
        public Nullable<decimal> fOpScrapnum { get; set; }
        public Nullable<decimal> fMaScrapnum { get; set; }
        public Nullable<decimal> finlostnum { get; set; }
        public Nullable<decimal> flostnum { get; set; }
        public Nullable<decimal> fRedonum { get; set; }
        public string cOpScrapreasoncode { get; set; }
        public string cMaScrapreasoncode { get; set; }
        public string cinlostreasoncode { get; set; }
        public string clostreasoncode { get; set; }
        public string cRedoreasoncode { get; set; }
        public Nullable<int> bflag { get; set; }
        public string cunitid { get; set; }
        public Nullable<decimal> fchangerate { get; set; }
        public string cmoordercode { get; set; }
        public Nullable<int> imoorderseq { get; set; }
        public Nullable<int> CREDORESPONSE { get; set; }
        public Nullable<int> partid { get; set; }
        public string cusedvouchcode { get; set; }
        public Nullable<int> iusedvouchautoid { get; set; }
        public Nullable<int> isourceautoid { get; set; }
        public string opseq { get; set; }
        public string citem_class { get; set; }
        public string citemcode { get; set; }
        public string citemname { get; set; }
        public string cbSysBarCode { get; set; }
        public Nullable<byte> cSource { get; set; }
        public string PFCODE { get; set; }
    
        public virtual hy_scrapreport hy_scrapreport { get; set; }
    }
}
