//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HY_UsedVouchDetailsTmp
    {
        public int autoid { get; set; }
        public Nullable<int> groupid { get; set; }
        public byte iselectflag { get; set; }
        public byte ivouchtype { get; set; }
        public int imainid { get; set; }
        public int idetailsid { get; set; }
        public string ccode { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public Nullable<int> imoorderid { get; set; }
        public Nullable<int> imoorderdid { get; set; }
        public string cmoordercode { get; set; }
        public Nullable<int> imoorderseq { get; set; }
        public Nullable<int> ihyorderid { get; set; }
        public Nullable<int> ihyorderdid { get; set; }
        public string chyordercode { get; set; }
        public string cvencode { get; set; }
        public string copcode { get; set; }
        public int partid { get; set; }
        public string cinvcode { get; set; }
        public string cfree1 { get; set; }
        public string cfree2 { get; set; }
        public string cfree3 { get; set; }
        public string cfree4 { get; set; }
        public string cfree5 { get; set; }
        public string cfree6 { get; set; }
        public string cfree7 { get; set; }
        public string cfree8 { get; set; }
        public string cfree9 { get; set; }
        public string cfree10 { get; set; }
        public Nullable<decimal> fvalidqty { get; set; }
        public Nullable<decimal> fopscrapqty { get; set; }
        public Nullable<decimal> fmascrapqty { get; set; }
        public Nullable<decimal> fopscrapnum { get; set; }
        public Nullable<decimal> fmascrapnum { get; set; }
        public Nullable<decimal> fvalidnum { get; set; }
        public string cunitid { get; set; }
        public Nullable<decimal> iinvexchrate { get; set; }
        public Nullable<decimal> fqty { get; set; }
        public Nullable<decimal> fnum { get; set; }
        public Nullable<decimal> finlostqty { get; set; }
        public Nullable<decimal> finlostnum { get; set; }
        public string cvalidreasoncode { get; set; }
        public string copscrapreasoncode { get; set; }
        public string cinlostreasoncode { get; set; }
        public Nullable<decimal> flostqty { get; set; }
        public Nullable<decimal> flostnum { get; set; }
        public string clostreasoncode { get; set; }
        public Nullable<bool> bgsp { get; set; }
        public string cdepcode { get; set; }
        public string cpersoncode { get; set; }
        public string csourceufts { get; set; }
        public string cmascrapreasoncode { get; set; }
        public string cmolot { get; set; }
        public Nullable<decimal> freworkqty { get; set; }
        public Nullable<decimal> freworknum { get; set; }
        public string creworkreasoncode { get; set; }
        public Nullable<int> credoresponse { get; set; }
        public string opseq { get; set; }
        public Nullable<decimal> fReworkJFQty { get; set; }
        public Nullable<decimal> fReworkJFNum { get; set; }
        public string citem_class { get; set; }
        public string citem_name { get; set; }
        public string citemcode { get; set; }
        public string citemname { get; set; }
        public string cDefine1 { get; set; }
        public string cDefine2 { get; set; }
        public string cDefine3 { get; set; }
        public Nullable<System.DateTime> cDefine4 { get; set; }
        public Nullable<int> cDefine5 { get; set; }
        public Nullable<System.DateTime> cDefine6 { get; set; }
        public Nullable<double> cDefine7 { get; set; }
        public string cDefine8 { get; set; }
        public string cDefine9 { get; set; }
        public string cDefine10 { get; set; }
        public string cDefine11 { get; set; }
        public string cDefine12 { get; set; }
        public string cDefine13 { get; set; }
        public string cDefine14 { get; set; }
        public Nullable<int> cDefine15 { get; set; }
        public Nullable<double> cDefine16 { get; set; }
        public string cDefine22 { get; set; }
        public string cDefine23 { get; set; }
        public string cDefine24 { get; set; }
        public string cDefine25 { get; set; }
        public Nullable<double> cDefine26 { get; set; }
        public Nullable<double> cDefine27 { get; set; }
        public string cDefine28 { get; set; }
        public string cDefine29 { get; set; }
        public string cDefine30 { get; set; }
        public string cDefine31 { get; set; }
        public string cDefine32 { get; set; }
        public string cDefine33 { get; set; }
        public Nullable<int> cDefine34 { get; set; }
        public string cDefine35 { get; set; }
        public Nullable<System.DateTime> cDefine36 { get; set; }
        public Nullable<System.DateTime> cDefine37 { get; set; }
        public Nullable<decimal> fTaxRate { get; set; }
        public Nullable<decimal> fUnitPrice { get; set; }
        public Nullable<decimal> fMoney { get; set; }
        public Nullable<decimal> fTax { get; set; }
        public Nullable<decimal> ftaxunitprice { get; set; }
        public Nullable<decimal> fTaxSum { get; set; }
        public Nullable<decimal> fNatUnitPrice { get; set; }
        public Nullable<decimal> fNatMoney { get; set; }
        public Nullable<decimal> fNatTax { get; set; }
        public Nullable<decimal> fNatTaxPrice { get; set; }
        public Nullable<decimal> fNatTaxSum { get; set; }
        public Nullable<decimal> fValidUnitPrice { get; set; }
        public Nullable<decimal> fValidMoney { get; set; }
        public Nullable<byte> iMaScrapdealtype { get; set; }
        public Nullable<decimal> fMaScrapUnitPrice { get; set; }
        public Nullable<decimal> fMaScrapMoney { get; set; }
        public Nullable<byte> iopscrapdealtype { get; set; }
        public Nullable<byte> iinlostdealtype { get; set; }
        public Nullable<decimal> finlostunitprice { get; set; }
        public Nullable<byte> iMaScrapdealtype_bak { get; set; }
        public Nullable<byte> iopscrapdealtype_bak { get; set; }
        public Nullable<byte> iinlostdealtype_Bak { get; set; }
        public Nullable<decimal> finlostmoney { get; set; }
        public Nullable<decimal> fOpScrapUnitPrice { get; set; }
        public Nullable<decimal> fOpScrapMoney { get; set; }
        public Nullable<decimal> fReworkJFPrice { get; set; }
        public Nullable<decimal> fReworkJFMoney { get; set; }
        public Nullable<decimal> nFlat { get; set; }
        public string cexch_name { get; set; }
        public Nullable<byte> btaxcost { get; set; }
        public Nullable<bool> bcal { get; set; }
        public string cMemo { get; set; }
    }
}
