//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class im_bondedbill
    {
        public int id { get; set; }
        public string guid { get; set; }
        public string ccode { get; set; }
        public Nullable<int> ibondedtrademode { get; set; }
        public string cciqbookid { get; set; }
        public string cciqbookcode { get; set; }
        public Nullable<int> iimbustype { get; set; }
        public string ccuscode { get; set; }
        public string cvencode { get; set; }
        public string cdepcode { get; set; }
        public string cpersoncode { get; set; }
        public string cvouchtype { get; set; }
        public string cexch_name { get; set; }
        public Nullable<decimal> fexchrate { get; set; }
        public Nullable<int> idec { get; set; }
        public Nullable<bool> bcal { get; set; }
        public string cdefine1 { get; set; }
        public string cdefine2 { get; set; }
        public string cdefine3 { get; set; }
        public string cdefine4 { get; set; }
        public string cdefine5 { get; set; }
        public string cdefine6 { get; set; }
        public string cdefine7 { get; set; }
        public string cdefine8 { get; set; }
        public string cdefine9 { get; set; }
        public string cdefine10 { get; set; }
        public string cdefine11 { get; set; }
        public string cdefine12 { get; set; }
        public string cdefine13 { get; set; }
        public string cdefine14 { get; set; }
        public string cdefine15 { get; set; }
        public string cdefine16 { get; set; }
        public string cmemos { get; set; }
        public Nullable<bool> bcancel { get; set; }
        public Nullable<System.DateTime> ddate { get; set; }
        public byte[] ufts { get; set; }
        public Nullable<int> ivtid { get; set; }
        public string cmaker { get; set; }
        public string cprinter { get; set; }
        public Nullable<System.DateTime> dprintdate { get; set; }
        public Nullable<int> iprinttime { get; set; }
        public Nullable<System.DateTime> dcreatesystime { get; set; }
        public Nullable<System.DateTime> dmodifydate { get; set; }
        public string cmodifier { get; set; }
        public Nullable<System.DateTime> dmodifysystime { get; set; }
        public Nullable<bool> bpositive { get; set; }
        public string ccbcode { get; set; }
        public Nullable<System.DateTime> dcbdate { get; set; }
        public string cciqbookcode2 { get; set; }
        public string cciqbookid2 { get; set; }
        public Nullable<bool> bcancelflag { get; set; }
        public string cverifier { get; set; }
        public Nullable<System.DateTime> dverifydate { get; set; }
        public Nullable<int> iverifystate { get; set; }
        public Nullable<int> iflowstate { get; set; }
        public Nullable<int> ireturncount { get; set; }
        public Nullable<bool> iswfcontrolled { get; set; }
        public Nullable<System.DateTime> dverifysystime { get; set; }
        public string csysbarcode { get; set; }
        public string cCurrentAuditor { get; set; }
    }
}
