//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IN_Reconcile
    {
        public string CheckId { get; set; }
        public string ModuleId { get; set; }
        public string CheckContent { get; set; }
        public string AuthId { get; set; }
        public bool IsCheck { get; set; }
        public string TemplatePath { get; set; }
        public string FilterID { get; set; }
        public string UserFilterXml { get; set; }
        public string UserFilterText { get; set; }
        public string ComName { get; set; }
        public string DataSourceType { get; set; }
        public int iOrder { get; set; }
        public string IsEnable { get; set; }
    }
}
