//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class info_magazine
    {
        public long id { get; set; }
        public string name { get; set; }
        public long create_user_id { get; set; }
        public System.DateTime create_time { get; set; }
        public Nullable<long> last_user_id { get; set; }
        public Nullable<System.DateTime> last_time { get; set; }
        public Nullable<byte> state { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<byte> is_new { get; set; }
        public long acount_id { get; set; }
        public string magazine_desc { get; set; }
        public Nullable<int> top_num { get; set; }
        public Nullable<int> sort_num { get; set; }
        public Nullable<System.DateTime> last_publish_time { get; set; }
        public string publish_range { get; set; }
        public Nullable<long> last_publish_record_id { get; set; }
        public Nullable<long> last_publish_user_id { get; set; }
        public Nullable<byte> is_delete { get; set; }
    }
}
