//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jk_triggers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jk_triggers()
        {
            this.jk_trigger_listeners = new HashSet<jk_trigger_listeners>();
        }
    
        public string TRIGGER_NAME { get; set; }
        public string TRIGGER_GROUP { get; set; }
        public string JOB_NAME { get; set; }
        public string JOB_GROUP { get; set; }
        public string IS_VOLATILE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> NEXT_FIRE_TIME { get; set; }
        public Nullable<long> PREV_FIRE_TIME { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public string TRIGGER_STATE { get; set; }
        public string TRIGGER_TYPE { get; set; }
        public long START_TIME { get; set; }
        public Nullable<long> END_TIME { get; set; }
        public string CALENDAR_NAME { get; set; }
        public Nullable<int> MISFIRE_INSTR { get; set; }
        public byte[] JOB_DATA { get; set; }
    
        public virtual jk_cron_triggers jk_cron_triggers { get; set; }
        public virtual jk_image_triggers jk_image_triggers { get; set; }
        public virtual jk_job_details jk_job_details { get; set; }
        public virtual jk_simple_triggers jk_simple_triggers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jk_trigger_listeners> jk_trigger_listeners { get; set; }
    }
}
