//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JustInVouchs
    {
        public int AutoID { get; set; }
        public string cJVCode { get; set; }
        public Nullable<int> CorID { get; set; }
        public string cCorCode { get; set; }
        public string cInvCode { get; set; }
        public Nullable<decimal> iJVPrice { get; set; }
        public string cJVBatch { get; set; }
        public string cObjCode { get; set; }
        public string cFree1 { get; set; }
        public string cFree2 { get; set; }
        public string cDefine22 { get; set; }
        public string cDefine23 { get; set; }
        public string cDefine24 { get; set; }
        public string cDefine25 { get; set; }
        public Nullable<double> cDefine26 { get; set; }
        public Nullable<double> cDefine27 { get; set; }
        public string cItemCode { get; set; }
        public string cItem_class { get; set; }
        public string cName { get; set; }
        public string cItemCName { get; set; }
        public Nullable<int> iJustInsId { get; set; }
        public string cBVencode { get; set; }
        public string cFree3 { get; set; }
        public Nullable<int> iMassDate { get; set; }
        public Nullable<System.DateTime> dMadeDate { get; set; }
        public string cInVouchCode { get; set; }
        public string cFree4 { get; set; }
        public string cFree5 { get; set; }
        public string cFree6 { get; set; }
        public string cFree7 { get; set; }
        public string cFree8 { get; set; }
        public string cFree9 { get; set; }
        public string cFree10 { get; set; }
        public string cDefine28 { get; set; }
        public string cDefine29 { get; set; }
        public string cDefine30 { get; set; }
        public string cDefine31 { get; set; }
        public string cDefine32 { get; set; }
        public string cDefine33 { get; set; }
        public Nullable<int> cDefine34 { get; set; }
        public Nullable<int> cDefine35 { get; set; }
        public Nullable<System.DateTime> cDefine36 { get; set; }
        public Nullable<System.DateTime> cDefine37 { get; set; }
        public Nullable<bool> bcosting { get; set; }
        public string cbAccounter { get; set; }
        public string cSRcVoutype { get; set; }
        public string cmocode { get; set; }
        public Nullable<int> imoseq { get; set; }
        public string iopseq { get; set; }
        public string copdesc { get; set; }
        public string cmworkcentercode { get; set; }
        public string cMoLotCode { get; set; }
        public Nullable<System.DateTime> dKeepDate { get; set; }
        public Nullable<decimal> ijvpricedif { get; set; }
        public Nullable<decimal> fInvQuanDif { get; set; }
        public Nullable<decimal> fInvPriceDif { get; set; }
        public Nullable<decimal> fLbrQuanDif { get; set; }
        public Nullable<decimal> fLbrPriceDif { get; set; }
        public Nullable<decimal> fSemiLbrQuanDif { get; set; }
        public Nullable<decimal> fManuFixQuanDif { get; set; }
        public Nullable<decimal> fManuFixPriceDif { get; set; }
        public Nullable<decimal> fSemiManuFixQuanDif { get; set; }
        public Nullable<decimal> fManuVarQuanDif { get; set; }
        public Nullable<decimal> fManuVarPriceDif { get; set; }
        public Nullable<decimal> fSemiManuVarQuanDif { get; set; }
        public Nullable<decimal> fOmCostDif { get; set; }
        public Nullable<decimal> fSemiOmQuanDif { get; set; }
        public string ccccode { get; set; }
    }
}
