//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KC_Ascii_Config
    {
        public int ID { get; set; }
        public string cbinary { get; set; }
        public string cdecimal { get; set; }
        public string csixteen { get; set; }
        public string cabbreviation { get; set; }
        public string cremark { get; set; }
    }
}
