//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogoutTable_Base
    {
        public string cSubId { get; set; }
        public string cSerial { get; set; }
        public string cEnTableName { get; set; }
        public string cEnFldName { get; set; }
        public string cChkProcedureName { get; set; }
        public string cExeProcedureName { get; set; }
        public bool bReplaceDep { get; set; }
        public bool bRefEndGrade { get; set; }
    }
}
