//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_AUTO_VIOLATE
    {
        public long APPLY_ID { get; set; }
        public string AUTO_ID { get; set; }
        public string REG_TIME { get; set; }
        public string REG_ADDR { get; set; }
        public string REG_BEHAVIOR { get; set; }
        public Nullable<long> REG_SITU { get; set; }
        public Nullable<long> AUTO_DRIVER { get; set; }
        public string REG_MEMO { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<long> DEL_FLAG { get; set; }
    }
}
