//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_book_info
    {
        public long book_id { get; set; }
        public string book_name { get; set; }
        public long book_type { get; set; }
        public string book_code { get; set; }
        public byte book_field { get; set; }
        public string book_author { get; set; }
        public string book_pub { get; set; }
        public Nullable<System.DateTime> book_date { get; set; }
        public Nullable<decimal> book_price { get; set; }
        public string book_sum { get; set; }
        public Nullable<decimal> book_total { get; set; }
        public int book_count { get; set; }
        public Nullable<int> book_avacount { get; set; }
        public Nullable<long> book_mge { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<byte> book_state { get; set; }
        public Nullable<byte> del_flag { get; set; }
        public long domain_id { get; set; }
    }
}
