//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialOut_SubTable_Stock
    {
        public string userid { get; set; }
        public string policy { get; set; }
        public Nullable<byte> igrouptype { get; set; }
        public string invcode { get; set; }
        public string invaddcode { get; set; }
        public string invname { get; set; }
        public string ccomunitcode { get; set; }
        public string ccomunitname { get; set; }
        public string cassunit { get; set; }
        public string cinva_unit { get; set; }
        public Nullable<double> qty_cksl { get; set; }
        public Nullable<double> iinvexchrate { get; set; }
        public Nullable<double> qty_ckjs { get; set; }
        public Nullable<double> qty_sub { get; set; }
        public Nullable<double> js_sub { get; set; }
        public string wccode { get; set; }
        public string wcname { get; set; }
        public string free1 { get; set; }
        public string free2 { get; set; }
        public string free3 { get; set; }
        public string free4 { get; set; }
        public string free5 { get; set; }
        public string free6 { get; set; }
        public string free7 { get; set; }
        public string free8 { get; set; }
        public string free9 { get; set; }
        public string free10 { get; set; }
        public string lotno { get; set; }
        public Nullable<decimal> cbatchproperty1 { get; set; }
        public Nullable<decimal> cbatchproperty2 { get; set; }
        public Nullable<decimal> cbatchproperty3 { get; set; }
        public Nullable<decimal> cbatchproperty4 { get; set; }
        public Nullable<decimal> cbatchproperty5 { get; set; }
        public string cbatchproperty6 { get; set; }
        public string cbatchproperty7 { get; set; }
        public string cbatchproperty8 { get; set; }
        public string cbatchproperty9 { get; set; }
        public Nullable<System.DateTime> cbatchproperty10 { get; set; }
        public Nullable<int> isoseq { get; set; }
        public Nullable<int> isotype { get; set; }
        public string isodid { get; set; }
        public string isocode { get; set; }
        public int id { get; set; }
    }
}
