//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mps_ssr_simuorderdetail
    {
        public int SsrId { get; set; }
        public int SimuSoDId { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> SimuSoId { get; set; }
        public Nullable<byte> SoType { get; set; }
        public string SoDId { get; set; }
        public string SoCode { get; set; }
        public Nullable<int> SoSeq { get; set; }
        public Nullable<int> PartId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<System.DateTime> PromisedDate { get; set; }
        public Nullable<decimal> PromisedQty { get; set; }
        public Nullable<int> CustBomId { get; set; }
        public Nullable<bool> OrderBomFlag { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<bool> ProcFlag { get; set; }
        public Nullable<int> BomId { get; set; }
    }
}
