//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mps_lrpschedule
    {
        public int SchId { get; set; }
        public Nullable<int> PartId { get; set; }
        public Nullable<System.DateTime> DemDate { get; set; }
        public Nullable<byte> DemType { get; set; }
        public Nullable<byte> SoType { get; set; }
        public string SoDId { get; set; }
        public string SoCode { get; set; }
        public Nullable<int> SoSeq { get; set; }
        public Nullable<byte> DocType { get; set; }
        public Nullable<int> DocDId { get; set; }
        public string DocCode { get; set; }
        public Nullable<int> DocSeq { get; set; }
        public Nullable<int> RefDataId { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public Nullable<decimal> DocQty { get; set; }
        public Nullable<decimal> BalQty { get; set; }
        public Nullable<byte> Status { get; set; }
        public string PDocCode { get; set; }
        public Nullable<byte> OrgDemType { get; set; }
        public Nullable<int> OrgDemDId { get; set; }
        public string OrgDemCode { get; set; }
        public Nullable<int> OrgDemSeq { get; set; }
        public Nullable<int> OpComponentId { get; set; }
        public Nullable<byte> ByProductFlag { get; set; }
        public Nullable<byte> FVFlag { get; set; }
        public Nullable<byte> FRefType { get; set; }
        public string FRefCode { get; set; }
        public Nullable<int> FRefId { get; set; }
        public string DemandCode { get; set; }
    }
}
