//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mps_lrppartstock
    {
        public int ProjectId { get; set; }
        public int PartId { get; set; }
        public byte SoType { get; set; }
        public string SoDId { get; set; }
        public Nullable<decimal> Onhand { get; set; }
        public Nullable<decimal> InQty { get; set; }
        public Nullable<decimal> OutQty { get; set; }
    }
}
