//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NB_payment
    {
        public int iID { get; set; }
        public string cBillID { get; set; }
        public string cBillIdInput { get; set; }
        public System.DateTime dBillDate { get; set; }
        public decimal mOriginMoney { get; set; }
        public string cPaySpeed { get; set; }
        public double sExchRate { get; set; }
        public decimal mNativeMoney { get; set; }
        public string cMoneyType { get; set; }
        public string cAccountFrom { get; set; }
        public string cAccountGroup { get; set; }
        public string cAccountTo { get; set; }
        public string cSettle { get; set; }
        public string cComeFrom { get; set; }
        public string cPurpose { get; set; }
        public string cAppend { get; set; }
        public string cRemark { get; set; }
        public string cComment { get; set; }
        public string cExaminer { get; set; }
        public string cApprover { get; set; }
        public Nullable<byte> iExamPass { get; set; }
        public Nullable<byte> iApprovePass { get; set; }
        public Nullable<bool> bPayed { get; set; }
        public Nullable<byte> iExported { get; set; }
        public Nullable<bool> bBalanced { get; set; }
        public Nullable<byte> iDZPeriod { get; set; }
        public Nullable<bool> bMakeBill { get; set; }
        public Nullable<System.DateTime> dOperateDate { get; set; }
        public string cOperator { get; set; }
        public string cModifier { get; set; }
        public string cPayer { get; set; }
        public string cTransNo { get; set; }
        public string cPzSys { get; set; }
        public string cDepCode { get; set; }
        public string cItemClass { get; set; }
        public string cItemCode { get; set; }
        public string cPerson { get; set; }
        public byte[] ufts { get; set; }
        public string cPackageId { get; set; }
        public int iBillStatus { get; set; }
        public Nullable<int> iChargeFrom { get; set; }
        public string cChargeAcc { get; set; }
        public string cBankUniqueNo { get; set; }
        public Nullable<int> iPayModel { get; set; }
        public Nullable<int> iPayType { get; set; }
        public string cErrInfoRet { get; set; }
        public string cAccountAgent { get; set; }
        public string cItemCodeName { get; set; }
        public string vt_id { get; set; }
        public string cAlterReason { get; set; }
        public Nullable<byte> bInner { get; set; }
        public string cDefine1 { get; set; }
        public string cDefine2 { get; set; }
        public string cDefine3 { get; set; }
        public Nullable<System.DateTime> cDefine4 { get; set; }
        public Nullable<int> cDefine5 { get; set; }
        public Nullable<System.DateTime> cDefine6 { get; set; }
        public Nullable<double> cDefine7 { get; set; }
        public string cDefine8 { get; set; }
        public string cDefine9 { get; set; }
        public string cDefine10 { get; set; }
        public string cDefine11 { get; set; }
        public string cDefine12 { get; set; }
        public string cDefine13 { get; set; }
        public string cDefine14 { get; set; }
        public Nullable<int> cDefine15 { get; set; }
        public Nullable<double> cDefine16 { get; set; }
        public string csysbarcode { get; set; }
        public string cAccountSub { get; set; }
        public string cVouchTypeFrom { get; set; }
        public string cVouchIdFrom { get; set; }
        public string cNoteNo { get; set; }
        public string cExpCode { get; set; }
        public string cwfapprover { get; set; }
        public Nullable<byte> iwfapprovepass { get; set; }
        public Nullable<System.DateTime> dwfapprovetime { get; set; }
        public int ireturncount { get; set; }
        public int iswfcontrolled { get; set; }
        public int iflowstate { get; set; }
    }
}
