//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_Extend
    {
        public string Key { get; set; }
        public int DocType { get; set; }
        public string layoutid { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
    }
}
