//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_OperationType
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public int TypeID { get; set; }
        public string ShowModelCode { get; set; }
        public int PrintModelCode { get; set; }
        public Nullable<bool> IsNeedApply { get; set; }
        public Nullable<bool> IsAllowLoan { get; set; }
        public Nullable<bool> IsBudgetControl { get; set; }
        public Nullable<bool> IsCreditControl { get; set; }
        public Nullable<bool> IsNeedBudgetItem { get; set; }
        public Nullable<bool> IsReturnLoan { get; set; }
        public Nullable<bool> IsModifyStandard { get; set; }
        public string SystemLink { get; set; }
        public string MenuID { get; set; }
        public string PrefixCode { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public byte[] ts { get; set; }
        public string SystemID { get; set; }
        public Nullable<int> LoanPayPrintModelCode { get; set; }
        public Nullable<int> LoanReturnPrintModelCode { get; set; }
        public Nullable<int> ExpenseVerifyPrintModelCode { get; set; }
        public Nullable<int> ExpensePayPrintModelCode { get; set; }
        public Nullable<int> IncomeReceiptPrintModelCode { get; set; }
        public Nullable<int> ReturnReceiptPrintModelCode { get; set; }
        public string MobileShowTemplateCode { get; set; }
        public string MobileEditTemplateCode { get; set; }
        public string MobileHeadEditColumnCode { get; set; }
        public string MobileBodyEditColumnCode { get; set; }
        public string MobileHeadShowColumnCode { get; set; }
        public string MobileBodyShowColumnCode { get; set; }
    }
}
