//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDM_PDMBusinessMeta
    {
        public int autoid { get; set; }
        public string cRegCode { get; set; }
        public string cBusinessObject { get; set; }
        public string cField { get; set; }
        public string cTable { get; set; }
        public string cCaption { get; set; }
        public string cDataType { get; set; }
        public Nullable<int> iLength { get; set; }
    }
}
