//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pl_co_temp_omjustdif
    {
        public int Ia_AutoId { get; set; }
        public int iOMoDid { get; set; }
        public bool bCurCo { get; set; }
        public bool bClosed { get; set; }
        public string cVouchType { get; set; }
        public string cVouchCode { get; set; }
        public string cDeptId { get; set; }
        public int iPartId { get; set; }
        public string cWhCode { get; set; }
        public string cRdCode { get; set; }
        public double fJustDif { get; set; }
    }
}
