//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pl_CO_ErrColumnsDic
    {
        public int iColumnID { get; set; }
        public string HeadColumns { get; set; }
        public string ColumnWidth { get; set; }
        public string Columns_CN { get; set; }
        public string Columns_TW { get; set; }
        public string Columns_US { get; set; }
    }
}
