//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pl_CO_SubsiDiary_ItemCost
    {
        public int iPeriod { get; set; }
        public int Ia_AutoId { get; set; }
        public int iMatItemId { get; set; }
        public Nullable<decimal> fInvQuanDif { get; set; }
        public Nullable<decimal> fInvPriceDif { get; set; }
        public Nullable<decimal> fStdCost { get; set; }
    }
}
