//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pl_co_temp_MorphTransDetails
    {
        public int AutoId { get; set; }
        public int Ia_AutoId_I { get; set; }
        public int Ia_AutoId_O { get; set; }
        public string cBusDepCode { get; set; }
        public int iPartId_I { get; set; }
        public Nullable<int> BomId_I { get; set; }
        public string cInvCode_I { get; set; }
        public string cRdCode_I { get; set; }
        public string cWhCode_I { get; set; }
        public double iNum_I { get; set; }
        public int iPartId_O { get; set; }
        public string cInvCode_O { get; set; }
        public Nullable<int> BomId_O { get; set; }
        public string cRdCode_O { get; set; }
        public string cWhCode_O { get; set; }
        public double iNum_O { get; set; }
        public decimal fChgMatDif { get; set; }
        public decimal fChgLbrDif { get; set; }
        public decimal fChgOmDif { get; set; }
    }
}
