//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pl_CO_bom_opcomponentrmk1
    {
        public string COVersion { get; set; }
        public string COVersionDesc { get; set; }
        public int RemarkId { get; set; }
        public int OpComponentId { get; set; }
        public int SortSeq { get; set; }
        public string Remark { get; set; }
    }
}
