//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pl_co_temp_partInvRcost
    {
        public int iPartId { get; set; }
        public decimal iInvRCost { get; set; }
        public decimal fLaborStdCost { get; set; }
        public decimal fLaborStdCost_CurL { get; set; }
        public decimal fManuVarCost { get; set; }
        public decimal fManuVarCost_CurL { get; set; }
        public decimal fManuFixCost { get; set; }
        public decimal fManuCost { get; set; }
        public decimal fManuFixCost_CurL { get; set; }
        public decimal fOmCost { get; set; }
        public decimal fOmCost_CurL { get; set; }
    }
}
