//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pl_co_temp_instockdif_details
    {
        public int autoid { get; set; }
        public int Ia_AutoId { get; set; }
        public Nullable<int> ID { get; set; }
        public int iPartId { get; set; }
        public string cWhCode { get; set; }
        public string cRdcode { get; set; }
        public string cBusDepCode { get; set; }
        public Nullable<bool> bTransfer { get; set; }
        public double iNum { get; set; }
        public double fInvQuanDif { get; set; }
        public double fSemiLaborQuanDif { get; set; }
        public double fSemiOmQuanDif { get; set; }
        public double fInvPriceDif { get; set; }
        public double fLaborQuanDif { get; set; }
        public double fLaborPriceDif { get; set; }
        public double fOmCostDif { get; set; }
        public Nullable<double> fChgMatDif { get; set; }
        public Nullable<double> fChgLbrDif { get; set; }
        public Nullable<double> fChgOmDif { get; set; }
    }
}
