//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_PzSet
    {
        public string cPzType { get; set; }
        public string cCenterCode { get; set; }
        public string cElementCode { get; set; }
        public string csign { get; set; }
        public string cJFCode { get; set; }
        public string cDFCode { get; set; }
        public string cDigest { get; set; }
        public int iPzMode { get; set; }
        public string cDepCodeDF { get; set; }
        public string cItemCodeDF { get; set; }
        public string iYear { get; set; }
    }
}
