//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PP_POMain
    {
        public byte[] ufts { get; set; }
        public int MainId { get; set; }
        public Nullable<int> ID { get; set; }
        public string cInvCode { get; set; }
        public System.DateTime dStartDate { get; set; }
        public System.DateTime dEndDate { get; set; }
        public string cMemo { get; set; }
        public Nullable<decimal> fQuantity { get; set; }
        public Nullable<decimal> fInQuantity { get; set; }
        public Nullable<int> iDataFrom { get; set; }
        public string cFree1 { get; set; }
        public string cFree2 { get; set; }
        public string cFree3 { get; set; }
        public string cFree4 { get; set; }
        public string cFree5 { get; set; }
        public string cFree6 { get; set; }
        public string cFree7 { get; set; }
        public string cFree8 { get; set; }
        public string cFree9 { get; set; }
        public string cFree10 { get; set; }
        public bool bUsed { get; set; }
        public string cClose { get; set; }
        public Nullable<bool> bCheck { get; set; }
        public Nullable<decimal> FTotalCheck { get; set; }
    
        public virtual PP_ProductPO PP_ProductPO { get; set; }
    }
}
