//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PP_PPCDetails
    {
        public string cPeriod { get; set; }
        public string cInvCode { get; set; }
        public string cUnit { get; set; }
        public Nullable<double> iPQTY { get; set; }
        public Nullable<System.DateTime> dArriveDate { get; set; }
        public string cPurchaser { get; set; }
        public Nullable<double> iPrice { get; set; }
        public Nullable<double> iCStock { get; set; }
        public Nullable<double> iSafeNum { get; set; }
        public Nullable<double> iInvBatch { get; set; }
        public string cFree1 { get; set; }
        public string cFree2 { get; set; }
        public string cFree3 { get; set; }
        public string cFree4 { get; set; }
        public string cFree5 { get; set; }
        public string cFree6 { get; set; }
        public string cFree7 { get; set; }
        public string cFree8 { get; set; }
        public string cFree9 { get; set; }
        public string cFree10 { get; set; }
        public int PPCIds { get; set; }
        public string cmemo { get; set; }
        public string cVenCode { get; set; }
        public Nullable<decimal> fQuota { get; set; }
        public Nullable<decimal> fQuantity { get; set; }
        public Nullable<int> iDataFrom { get; set; }
        public Nullable<System.DateTime> dPlanDate { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> iInvAdvance { get; set; }
        public Nullable<bool> iSelectQuota { get; set; }
        public Nullable<decimal> fshQty { get; set; }
    }
}
