//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PP_ROPMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PP_ROPMain()
        {
            this.PP_ROPDetails = new HashSet<PP_ROPDetails>();
        }
    
        public int MUID { get; set; }
        public byte[] ufts { get; set; }
        public int iVTid { get; set; }
        public string cROPCode { get; set; }
        public Nullable<int> iState { get; set; }
        public string cDefine1 { get; set; }
        public string cDefine2 { get; set; }
        public string cDefine3 { get; set; }
        public Nullable<System.DateTime> cDefine4 { get; set; }
        public Nullable<int> cDefine5 { get; set; }
        public Nullable<System.DateTime> cDefine6 { get; set; }
        public Nullable<double> cDefine7 { get; set; }
        public string cDefine8 { get; set; }
        public string cDefine9 { get; set; }
        public string cDefine10 { get; set; }
        public string cDefine11 { get; set; }
        public string cDefine12 { get; set; }
        public string cDefine13 { get; set; }
        public string cDefine14 { get; set; }
        public Nullable<int> cDefine15 { get; set; }
        public Nullable<double> cDefine16 { get; set; }
        public Nullable<System.DateTime> dCreateDate { get; set; }
        public string cMaker { get; set; }
        public Nullable<System.DateTime> dVerifiedDate { get; set; }
        public string cVerifier { get; set; }
        public string cCloser { get; set; }
        public string cMemo { get; set; }
        public string cLog { get; set; }
        public string cModifyPerson { get; set; }
        public Nullable<System.DateTime> dModifyDate { get; set; }
        public Nullable<System.DateTime> dnmaketime { get; set; }
        public Nullable<System.DateTime> dnmodifytime { get; set; }
        public Nullable<System.DateTime> dnverifytime { get; set; }
        public Nullable<int> iPrintCount { get; set; }
        public string csysbarcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PP_ROPDetails> PP_ROPDetails { get; set; }
    }
}
