//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProxyVenWh
    {
        public string CWhCode { get; set; }
        public string cInvCode { get; set; }
        public string cVenCode { get; set; }
        public Nullable<double> iTopSum { get; set; }
        public Nullable<double> iSafeNum { get; set; }
        public Nullable<double> iLowSum { get; set; }
        public byte[] pubufts { get; set; }
        public Nullable<int> iMaterialsCycle { get; set; }
    }
}
