//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PU_AppVouchs
    {
        public int ID { get; set; }
        public int AutoID { get; set; }
        public string cVenCode { get; set; }
        public string cInvCode { get; set; }
        public decimal fQuantity { get; set; }
        public Nullable<decimal> fUnitPrice { get; set; }
        public Nullable<decimal> iPerTaxRate { get; set; }
        public Nullable<decimal> fTaxPrice { get; set; }
        public Nullable<decimal> fMoney { get; set; }
        public Nullable<System.DateTime> dRequirDate { get; set; }
        public Nullable<System.DateTime> dArriveDate { get; set; }
        public Nullable<decimal> iReceivedQTY { get; set; }
        public string cFree1 { get; set; }
        public string cFree2 { get; set; }
        public string cFree3 { get; set; }
        public string cFree4 { get; set; }
        public string cFree5 { get; set; }
        public string cFree6 { get; set; }
        public string cFree7 { get; set; }
        public string cFree8 { get; set; }
        public string cFree9 { get; set; }
        public string cFree10 { get; set; }
        public string cDefine22 { get; set; }
        public string cDefine23 { get; set; }
        public string cDefine24 { get; set; }
        public string cDefine25 { get; set; }
        public Nullable<double> cDefine26 { get; set; }
        public Nullable<double> cDefine27 { get; set; }
        public string cDefine28 { get; set; }
        public string cDefine29 { get; set; }
        public string cDefine30 { get; set; }
        public string cDefine31 { get; set; }
        public string cDefine32 { get; set; }
        public string cDefine33 { get; set; }
        public Nullable<int> cDefine34 { get; set; }
        public Nullable<int> cDefine35 { get; set; }
        public Nullable<System.DateTime> cDefine36 { get; set; }
        public Nullable<System.DateTime> cDefine37 { get; set; }
        public string cItem_class { get; set; }
        public string cItemCode { get; set; }
        public string CItemName { get; set; }
        public Nullable<bool> bTaxCost { get; set; }
        public Nullable<int> iPPartId { get; set; }
        public Nullable<decimal> iPQuantity { get; set; }
        public Nullable<int> iPTOSeq { get; set; }
        public string cSource { get; set; }
        public string SoDId { get; set; }
        public Nullable<byte> SoType { get; set; }
        public Nullable<int> iMrpsid { get; set; }
        public Nullable<int> iRopsid { get; set; }
        public string cbcloser { get; set; }
        public Nullable<decimal> fNum { get; set; }
        public string cUnitID { get; set; }
        public Nullable<decimal> iReceivedNum { get; set; }
        public string cPersonCodeExec { get; set; }
        public string cDepCodeExec { get; set; }
        public Nullable<decimal> iInvMPCost { get; set; }
        public byte[] dUfts { get; set; }
        public string cexch_name { get; set; }
        public Nullable<decimal> iExchRate { get; set; }
        public Nullable<decimal> iOriCost { get; set; }
        public Nullable<decimal> iOriTaxCost { get; set; }
        public Nullable<decimal> iOriMoney { get; set; }
        public Nullable<decimal> iOriTaxPrice { get; set; }
        public Nullable<decimal> iOriSum { get; set; }
        public Nullable<decimal> iMoney { get; set; }
        public Nullable<decimal> iTaxPrice { get; set; }
        public string cdemandcode { get; set; }
        public string cdetailsdemandmemo { get; set; }
        public string cBG_ItemCode { get; set; }
        public string cBG_ItemName { get; set; }
        public string cBG_CaliberKey1 { get; set; }
        public string cBG_CaliberKeyName1 { get; set; }
        public string cBG_CaliberKey2 { get; set; }
        public string cBG_CaliberKeyName2 { get; set; }
        public string cBG_CaliberKey3 { get; set; }
        public string cBG_CaliberKeyName3 { get; set; }
        public string cBG_CaliberCode1 { get; set; }
        public string cBG_CaliberName1 { get; set; }
        public string cBG_CaliberCode2 { get; set; }
        public string cBG_CaliberName2 { get; set; }
        public string cBG_CaliberCode3 { get; set; }
        public string cBG_CaliberName3 { get; set; }
        public Nullable<byte> iBG_Ctrl { get; set; }
        public string cBG_Auditopinion { get; set; }
        public string mocode { get; set; }
        public Nullable<int> ivouchrowno { get; set; }
        public Nullable<decimal> fconquantity { get; set; }
        public Nullable<decimal> fconmoney { get; set; }
        public Nullable<decimal> fconnum { get; set; }
        public Nullable<decimal> fconorimoney { get; set; }
        public string cBG_CaliberKey4 { get; set; }
        public string cBG_CaliberKeyName4 { get; set; }
        public string cBG_CaliberKey5 { get; set; }
        public string cBG_CaliberKeyName5 { get; set; }
        public string cBG_CaliberKey6 { get; set; }
        public string cBG_CaliberKeyName6 { get; set; }
        public string cBG_CaliberCode4 { get; set; }
        public string cBG_CaliberName4 { get; set; }
        public string cBG_CaliberCode5 { get; set; }
        public string cBG_CaliberName5 { get; set; }
        public string cBG_CaliberCode6 { get; set; }
        public string cBG_CaliberName6 { get; set; }
        public string csocode { get; set; }
        public Nullable<int> irowno { get; set; }
        public Nullable<decimal> iSumXJqty { get; set; }
        public Nullable<decimal> iSumXJCGqty { get; set; }
        public Nullable<System.DateTime> dbCloseDate { get; set; }
        public Nullable<System.DateTime> dbCloseTime { get; set; }
        public string cbMemo { get; set; }
        public string cbsysbarcode { get; set; }
        public Nullable<int> isosid { get; set; }
        public Nullable<int> iorderdid { get; set; }
        public Nullable<byte> iordertype { get; set; }
        public string csoordercode { get; set; }
        public Nullable<int> iorderseq { get; set; }
        public string planlotnumber { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
