//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PU_ArrivalVouchHistory
    {
        public int iVTid { get; set; }
        public byte[] ufts { get; set; }
        public int ID { get; set; }
        public string cCode { get; set; }
        public string cPTCode { get; set; }
        public System.DateTime dDate { get; set; }
        public string cVenCode { get; set; }
        public string cDepCode { get; set; }
        public string cPersonCode { get; set; }
        public string cPayCode { get; set; }
        public string cSCCode { get; set; }
        public string cexch_name { get; set; }
        public Nullable<double> iExchRate { get; set; }
        public Nullable<decimal> iTaxRate { get; set; }
        public string cMemo { get; set; }
        public string cBusType { get; set; }
        public string cMaker { get; set; }
        public int bNegative { get; set; }
        public string cDefine1 { get; set; }
        public string cDefine2 { get; set; }
        public string cDefine3 { get; set; }
        public Nullable<System.DateTime> cDefine4 { get; set; }
        public Nullable<int> cDefine5 { get; set; }
        public Nullable<System.DateTime> cDefine6 { get; set; }
        public Nullable<double> cDefine7 { get; set; }
        public string cDefine8 { get; set; }
        public string cDefine9 { get; set; }
        public string cDefine10 { get; set; }
        public string cDefine11 { get; set; }
        public string cDefine12 { get; set; }
        public string cDefine13 { get; set; }
        public string cDefine14 { get; set; }
        public Nullable<int> cDefine15 { get; set; }
        public Nullable<double> cDefine16 { get; set; }
        public string ccloser { get; set; }
        public Nullable<byte> iDiscountTaxType { get; set; }
        public byte iBillType { get; set; }
        public string cvouchtype { get; set; }
        public string cgeneralordercode { get; set; }
        public string ctmcode { get; set; }
        public string cincotermcode { get; set; }
        public string ctransordercode { get; set; }
        public Nullable<System.DateTime> dportdate { get; set; }
        public string csportcode { get; set; }
        public string caportcode { get; set; }
        public string csvencode { get; set; }
        public string carrivalplace { get; set; }
        public Nullable<System.DateTime> dclosedate { get; set; }
        public Nullable<int> idec { get; set; }
        public Nullable<bool> bcal { get; set; }
        public string guid { get; set; }
        public Nullable<System.DateTime> cMakeTime { get; set; }
        public Nullable<System.DateTime> cModifyTime { get; set; }
        public Nullable<System.DateTime> cModifyDate { get; set; }
        public string cReviser { get; set; }
        public Nullable<int> iverifystate { get; set; }
        public Nullable<System.DateTime> cAuditDate { get; set; }
        public Nullable<System.DateTime> caudittime { get; set; }
        public string cverifier { get; set; }
        public Nullable<int> iverifystateex { get; set; }
        public Nullable<int> ireturncount { get; set; }
        public Nullable<bool> IsWfControlled { get; set; }
        public string cVenPUOMProtocol { get; set; }
        public string cchanger { get; set; }
        public Nullable<int> iflowid { get; set; }
        public Nullable<int> iPrintCount { get; set; }
        public string ccleanver { get; set; }
        public string cpocode { get; set; }
        public string csysbarcode { get; set; }
        public string cCurrentAuditor { get; set; }
        public long HistoryId { get; set; }
        public Nullable<byte> VariationAction { get; set; }
        public Nullable<int> VariationLogId { get; set; }
        public Nullable<byte> SubVariationAction { get; set; }
    }
}
