//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pu_vendorverify
    {
        public int id { get; set; }
        public string ccode { get; set; }
        public System.DateTime ddate { get; set; }
        public string cpersoncode { get; set; }
        public string cmaker { get; set; }
        public string cvenname { get; set; }
        public string cvenabbname { get; set; }
        public int bputype { get; set; }
        public int bomtype { get; set; }
        public int bsertype { get; set; }
        public string ccorpotype { get; set; }
        public string cdccode { get; set; }
        public string ctrade { get; set; }
        public string cbusinesstype { get; set; }
        public string cinvcode { get; set; }
        public Nullable<int> iemployeecount { get; set; }
        public Nullable<decimal> fregistfund { get; set; }
        public string cvenregcode { get; set; }
        public Nullable<System.DateTime> dvendevdate { get; set; }
        public string cvenbank { get; set; }
        public string cvenaccount { get; set; }
        public string cvenlperson { get; set; }
        public string clicencename { get; set; }
        public string clicencecode { get; set; }
        public string clicencearea { get; set; }
        public string clicencelperson { get; set; }
        public Nullable<System.DateTime> dlicencesdate { get; set; }
        public Nullable<System.DateTime> dlicenceedate { get; set; }
        public string cmasstype { get; set; }
        public string cvenaddress { get; set; }
        public string cveniaddress { get; set; }
        public string cvenpostcode { get; set; }
        public string cvenperson { get; set; }
        public string cvenphone { get; set; }
        public string cvenemail { get; set; }
        public string cvenfax { get; set; }
        public string cvenpperson { get; set; }
        public string cvenppersonphone { get; set; }
        public string creviewperson { get; set; }
        public Nullable<System.DateTime> creviewdate { get; set; }
        public string creviewtype { get; set; }
        public string creviewthing { get; set; }
        public string cbizdepidea { get; set; }
        public string cmassdepidea { get; set; }
        public string cmassdepperson { get; set; }
        public string cverifier { get; set; }
        public Nullable<System.DateTime> dverifydate { get; set; }
        public string cmemo { get; set; }
        public string cDefine1 { get; set; }
        public string cDefine2 { get; set; }
        public string cDefine3 { get; set; }
        public Nullable<System.DateTime> cDefine4 { get; set; }
        public Nullable<int> cDefine5 { get; set; }
        public Nullable<System.DateTime> cDefine6 { get; set; }
        public Nullable<double> cDefine7 { get; set; }
        public string cDefine8 { get; set; }
        public string cDefine9 { get; set; }
        public string cDefine10 { get; set; }
        public string cDefine11 { get; set; }
        public string cDefine12 { get; set; }
        public string cDefine13 { get; set; }
        public string cDefine14 { get; set; }
        public Nullable<int> cDefine15 { get; set; }
        public Nullable<double> cDefine16 { get; set; }
        public int bswitchtovendor { get; set; }
        public string cdepcode { get; set; }
        public int iverifystate { get; set; }
        public byte[] ufts { get; set; }
        public Nullable<int> ivtid { get; set; }
        public Nullable<int> iverifystateex { get; set; }
        public Nullable<int> ireturncount { get; set; }
        public Nullable<bool> IsWfControlled { get; set; }
        public Nullable<System.DateTime> cMakeTime { get; set; }
        public Nullable<System.DateTime> cModifyTime { get; set; }
        public Nullable<System.DateTime> cAuditTime { get; set; }
        public Nullable<System.DateTime> cModifyDate { get; set; }
        public string cReviser { get; set; }
        public Nullable<int> ibilltype { get; set; }
        public string cvencode { get; set; }
        public int bvenaccperiodmng { get; set; }
        public string cvenpuomprotocol { get; set; }
        public string cvenimprotocol { get; set; }
        public string cvencmprotocol { get; set; }
        public string cvenotherprotocol { get; set; }
        public Nullable<int> iPrintCount { get; set; }
        public string ccleanver { get; set; }
        public string cExch_name { get; set; }
        public Nullable<double> iTaxRate { get; set; }
        public string cVenDepCode { get; set; }
        public string cVenPersonCode { get; set; }
        public string cSSCode { get; set; }
        public string cPayCode { get; set; }
        public string cVenDefine1 { get; set; }
        public string cVenDefine2 { get; set; }
        public string cVenDefine3 { get; set; }
        public string cVenDefine4 { get; set; }
        public string cVenDefine5 { get; set; }
        public string cVenDefine6 { get; set; }
        public string cVenDefine7 { get; set; }
        public string cVenDefine8 { get; set; }
        public string cVenDefine9 { get; set; }
        public string cVenDefine10 { get; set; }
        public Nullable<int> cVenDefine11 { get; set; }
        public Nullable<int> cVenDefine12 { get; set; }
        public Nullable<double> cVenDefine13 { get; set; }
        public Nullable<double> cVenDefine14 { get; set; }
        public Nullable<System.DateTime> cVenDefine15 { get; set; }
        public Nullable<System.DateTime> cVenDefine16 { get; set; }
        public Nullable<double> iCreLine { get; set; }
        public Nullable<int> iCreDate { get; set; }
        public string csysbarcode { get; set; }
        public string cCurrentAuditor { get; set; }
        public string cdcname { get; set; }
        public string cattachment { get; set; }
        public Nullable<System.DateTime> denddate { get; set; }
    }
}
