//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurBillVouch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurBillVouch()
        {
            this.PurBillVouchs = new HashSet<PurBillVouchs>();
        }
    
        public int PBVID { get; set; }
        public string cPBVBillType { get; set; }
        public string cPBVCode { get; set; }
        public string cPTCode { get; set; }
        public System.DateTime dPBVDate { get; set; }
        public string cVenCode { get; set; }
        public string cUnitCode { get; set; }
        public string cDepCode { get; set; }
        public string cPersonCode { get; set; }
        public string cPayCode { get; set; }
        public string cexch_name { get; set; }
        public Nullable<double> cExchRate { get; set; }
        public Nullable<double> iPBVTaxRate { get; set; }
        public string cPBVMemo { get; set; }
        public string cOrderCode { get; set; }
        public string cInCode { get; set; }
        public string cBusType { get; set; }
        public Nullable<System.DateTime> dSDate { get; set; }
        public string cPBVMaker { get; set; }
        public string cPBVVerifier { get; set; }
        public bool bNegative { get; set; }
        public bool bOriginal { get; set; }
        public bool bFirst { get; set; }
        public string citem_class { get; set; }
        public string citemcode { get; set; }
        public string cHeadCode { get; set; }
        public Nullable<float> iNetLock { get; set; }
        public string cDefine1 { get; set; }
        public string cDefine2 { get; set; }
        public string cDefine3 { get; set; }
        public Nullable<System.DateTime> cDefine4 { get; set; }
        public Nullable<int> cDefine5 { get; set; }
        public Nullable<System.DateTime> cDefine6 { get; set; }
        public Nullable<double> cDefine7 { get; set; }
        public string cDefine8 { get; set; }
        public string cDefine9 { get; set; }
        public string cDefine10 { get; set; }
        public string bPayment { get; set; }
        public Nullable<System.DateTime> dVouDate { get; set; }
        public int iVTid { get; set; }
        public byte[] ufts { get; set; }
        public string cAccounter { get; set; }
        public string cSource { get; set; }
        public string cDefine11 { get; set; }
        public string cDefine12 { get; set; }
        public string cDefine13 { get; set; }
        public string cDefine14 { get; set; }
        public Nullable<int> cDefine15 { get; set; }
        public Nullable<double> cDefine16 { get; set; }
        public Nullable<bool> bIAFirst { get; set; }
        public Nullable<byte> iDiscountTaxType { get; set; }
        public string cVenPUOMProtocol { get; set; }
        public Nullable<System.DateTime> dCreditStart { get; set; }
        public Nullable<int> iCreditPeriod { get; set; }
        public Nullable<System.DateTime> dGatheringDate { get; set; }
        public Nullable<System.DateTime> cModifyDate { get; set; }
        public string cReviser { get; set; }
        public Nullable<short> bCredit { get; set; }
        public Nullable<short> iBG_OverFlag { get; set; }
        public string cBG_Auditor { get; set; }
        public string cBG_AuditTime { get; set; }
        public Nullable<short> ControlResult { get; set; }
        public Nullable<int> iflowid { get; set; }
        public Nullable<System.DateTime> dverifydate { get; set; }
        public Nullable<System.DateTime> dverifysystime { get; set; }
        public string cVenAccount { get; set; }
        public Nullable<int> iPrintCount { get; set; }
        public string ccleanver { get; set; }
        public string cContactCode { get; set; }
        public string cVenPerson { get; set; }
        public string cVenBank { get; set; }
        public string cVerifier { get; set; }
        public Nullable<System.DateTime> cAuditDate { get; set; }
        public Nullable<System.DateTime> cAuditTime { get; set; }
        public Nullable<int> iverifystateex { get; set; }
        public Nullable<int> ireturncount { get; set; }
        public Nullable<bool> IsWfControlled { get; set; }
        public string csysbarcode { get; set; }
        public string cCurrentAuditor { get; set; }
        public Nullable<System.DateTime> cmaketime { get; set; }
        public Nullable<System.DateTime> cmodifytime { get; set; }
        public Nullable<short> bMerger { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual foreigncurrency foreigncurrency { get; set; }
        public virtual PayCondition PayCondition { get; set; }
        public virtual Person Person { get; set; }
        public virtual PurchaseType PurchaseType { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurBillVouchs> PurBillVouchs { get; set; }
    }
}
