//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseType()
        {
            this.PO_Pomain = new HashSet<PO_Pomain>();
            this.PU_AppVouch = new HashSet<PU_AppVouch>();
            this.PU_ArrivalVouch = new HashSet<PU_ArrivalVouch>();
            this.PU_T_VMIUsedVouch = new HashSet<PU_T_VMIUsedVouch>();
            this.PurBillVouch = new HashSet<PurBillVouch>();
            this.rdrecord891bak = new HashSet<rdrecord891bak>();
        }
    
        public string cPTCode { get; set; }
        public string cPTName { get; set; }
        public string cRdCode { get; set; }
        public bool bDefault { get; set; }
        public byte[] pubufts { get; set; }
        public bool bPFDefault { get; set; }
        public bool bPTMPS_MRP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_Pomain> PO_Pomain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PU_AppVouch> PU_AppVouch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PU_ArrivalVouch> PU_ArrivalVouch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PU_T_VMIUsedVouch> PU_T_VMIUsedVouch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurBillVouch> PurBillVouch { get; set; }
        public virtual Rd_Style Rd_Style { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rdrecord891bak> rdrecord891bak { get; set; }
    }
}
