//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QMDOCMANAGER
    {
        public System.Guid CDOCGUID { get; set; }
        public string CDOCCODE { get; set; }
        public string CDOCNAME { get; set; }
        public string CPATH { get; set; }
        public string CPARENTNODE { get; set; }
        public Nullable<bool> BEND { get; set; }
        public string CMAKER { get; set; }
        public string CVERIFIER { get; set; }
        public string CDOCTYPE { get; set; }
        public Nullable<System.DateTime> DPASSDATE { get; set; }
        public Nullable<System.DateTime> DISSUEDATE { get; set; }
        public string CCONTROL { get; set; }
        public string CSENDDEPNAME { get; set; }
        public string CDISPATCHDEPCODE { get; set; }
        public string CSENDPERSON { get; set; }
        public string CMEMO { get; set; }
        public byte[] UFTS { get; set; }
    }
}
