//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rb_GeneralModuleDefinitions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rb_GeneralModuleDefinitions()
        {
            this.rb_GeneralModuleSettings = new HashSet<rb_GeneralModuleSettings>();
            this.rb_ModuleActions = new HashSet<rb_ModuleActions>();
            this.rb_ModuleDefaultActions = new HashSet<rb_ModuleDefaultActions>();
            this.rb_ModuleDefinitions = new HashSet<rb_ModuleDefinitions>();
            this.rb_SolutionModuleDefinitions = new HashSet<rb_SolutionModuleDefinitions>();
        }
    
        public System.Guid GeneralModDefID { get; set; }
        public string FriendlyName { get; set; }
        public string DesktopSrc { get; set; }
        public string MobileSrc { get; set; }
        public string AssemblyName { get; set; }
        public string ClassName { get; set; }
        public Nullable<bool> Admin { get; set; }
        public Nullable<bool> Searchable { get; set; }
        public string cSystemID { get; set; }
        public Nullable<short> nActionSrcType { get; set; }
        public string nActionSrc { get; set; }
        public string cNavigationTarget { get; set; }
        public string cNavigationURL { get; set; }
        public string cNavigationParams { get; set; }
        public string cDescription { get; set; }
        public bool cIsFixed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rb_GeneralModuleSettings> rb_GeneralModuleSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rb_ModuleActions> rb_ModuleActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rb_ModuleDefaultActions> rb_ModuleDefaultActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rb_ModuleDefinitions> rb_ModuleDefinitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rb_SolutionModuleDefinitions> rb_SolutionModuleDefinitions { get; set; }
    }
}
