//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rd_Style
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rd_Style()
        {
            this.AssemVouch = new HashSet<AssemVouch>();
            this.EnDispatch = new HashSet<EnDispatch>();
            this.JustInVouch = new HashSet<JustInVouch>();
            this.MaterialAppVouch = new HashSet<MaterialAppVouch>();
            this.PurchaseType = new HashSet<PurchaseType>();
            this.DispatchList = new HashSet<DispatchList>();
            this.rdrecord891bak = new HashSet<rdrecord891bak>();
            this.SaleType = new HashSet<SaleType>();
            this.TransVouch = new HashSet<TransVouch>();
            this.TransVouch1 = new HashSet<TransVouch>();
            this.VouchRdContrapose = new HashSet<VouchRdContrapose>();
            this.VouchRdContrapose1 = new HashSet<VouchRdContrapose>();
        }
    
        public string cRdCode { get; set; }
        public string cRdName { get; set; }
        public byte iRdGrade { get; set; }
        public int bRdFlag { get; set; }
        public bool bRdEnd { get; set; }
        public string cOppHead { get; set; }
        public byte[] pubufts { get; set; }
        public Nullable<bool> bRetail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssemVouch> AssemVouch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnDispatch> EnDispatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JustInVouch> JustInVouch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialAppVouch> MaterialAppVouch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseType> PurchaseType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispatchList> DispatchList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rdrecord891bak> rdrecord891bak { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleType> SaleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransVouch> TransVouch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransVouch> TransVouch1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VouchRdContrapose> VouchRdContrapose { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VouchRdContrapose> VouchRdContrapose1 { get; set; }
    }
}
