//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_EndPoint
    {
        public string ID { get; set; }
        public string Address { get; set; }
        public string ProtocolID { get; set; }
        public string ProtocolParams { get; set; }
        public int AppTagID { get; set; }
        public string Description { get; set; }
    
        public virtual MOM_Protocol MOM_Protocol { get; set; }
    }
}
