//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rel_message_user
    {
        public decimal message_id { get; set; }
        public string user_id { get; set; }
        public short read_flag { get; set; }
        public string msg_id { get; set; }
        public Nullable<short> bc_flag { get; set; }
        public Nullable<short> server_flag { get; set; }
        public byte[] crm_timestamp { get; set; }
        public Nullable<short> issender { get; set; }
    }
}
