//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class relate_member
    {
        public long id { get; set; }
        public long relate_member_id { get; set; }
        public long related_id { get; set; }
        public byte relate_wsbs { get; set; }
        public byte relate_type { get; set; }
        public Nullable<int> order_num { get; set; }
    }
}
