//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_fundef_Base
    {
        public string cSystemID { get; set; }
        public int ID { get; set; }
        public string cFunName { get; set; }
        public string cFunDefine { get; set; }
        public string cGroupDefine { get; set; }
        public bool buserdefine { get; set; }
        public string cLimitRange { get; set; }
        public bool blimited { get; set; }
        public Nullable<int> ifirst { get; set; }
        public string LocaleID { get; set; }
    }
}
