//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rpt_GRPDEF_Base
    {
        public string Systemid { get; set; }
        public string Tablename { get; set; }
        public string Tabledefine { get; set; }
        public Nullable<int> Tabletype { get; set; }
        public string SystemName { get; set; }
        public string LocaleID { get; set; }
    }
}
