//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SA_ReferVoucherConfig
    {
        public string cardnum { get; set; }
        public string referkey { get; set; }
        public string maincolumnkey { get; set; }
        public string detailcolumnkey { get; set; }
        public string toolbarkey { get; set; }
        public string subsysid { get; set; }
        public string filtername { get; set; }
        public string maindatasource { get; set; }
        public string detaildatasource { get; set; }
        public string selecttype { get; set; }
        public string fillkey { get; set; }
        public string mainuniquekey { get; set; }
        public Nullable<long> pagesize { get; set; }
        public long autoid { get; set; }
        public string defaultfilter { get; set; }
        public string filltype { get; set; }
        public string captionresid { get; set; }
        public string detailuniquekey { get; set; }
        public string buttonspara { get; set; }
        public string uniqueflds { get; set; }
        public string condition { get; set; }
        public string setdetailvalues { get; set; }
        public string alertflds { get; set; }
        public string uniquefldsB { get; set; }
        public string alertfldsB { get; set; }
        public Nullable<int> itype { get; set; }
        public string defaultsubfilter { get; set; }
        public Nullable<byte> iGetdataOrder { get; set; }
        public Nullable<byte> iFillTimes { get; set; }
    }
}
