//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCM_ImportDefaultValSet
    {
        public int Autoid { get; set; }
        public string cSys_ID { get; set; }
        public string cCardNum { get; set; }
        public string CardItemName { get; set; }
        public string cFldName { get; set; }
        public int iReferType { get; set; }
        public string cRetFldName { get; set; }
        public string cCheckString { get; set; }
        public string cValue { get; set; }
        public string cReferString { get; set; }
        public Nullable<int> iType { get; set; }
    }
}
