//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCM_SKUTransactionRule
    {
        public int RuleId { get; set; }
        public string DocumentType { get; set; }
        public string cBusType { get; set; }
        public string cSource { get; set; }
        public Nullable<bool> bSKUGSPStop { get; set; }
        public Nullable<bool> bSKUStop { get; set; }
        public bool bTransactionAllowed { get; set; }
    }
}
