//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCM_StockCheckResult
    {
        public Nullable<int> ResultType { get; set; }
        public Nullable<int> iControlMethod { get; set; }
        public Nullable<decimal> iNum { get; set; }
        public Nullable<decimal> iQuantity { get; set; }
        public Nullable<decimal> iBillNum { get; set; }
        public Nullable<decimal> iBillQuantity { get; set; }
        public string cWhCode { get; set; }
        public string cInvCode { get; set; }
        public int ItemId { get; set; }
        public string cVMIVenCode { get; set; }
        public string cBatch { get; set; }
        public string TransactionId { get; set; }
        public int SequenceId { get; set; }
        public string DocumentType { get; set; }
        public int DocumentId { get; set; }
        public int DocumentDId { get; set; }
        public int DemandPlanType { get; set; }
        public string DemandPlanDId { get; set; }
        public Nullable<decimal> iOldAvaQuantity { get; set; }
        public Nullable<decimal> iOldAvaNum { get; set; }
        public Nullable<decimal> iNewAvaQuantity { get; set; }
        public Nullable<decimal> iNewAvaNum { get; set; }
        public Nullable<decimal> iLowStock { get; set; }
        public Nullable<decimal> iTopStock { get; set; }
        public Nullable<decimal> iLessLowStock { get; set; }
        public Nullable<decimal> iMoreTopStock { get; set; }
        public Nullable<decimal> iOldStockQuantity { get; set; }
        public Nullable<decimal> iOldStockNum { get; set; }
        public Nullable<decimal> iNewStockQuantity { get; set; }
        public Nullable<decimal> iNewStockNum { get; set; }
    }
}
