//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrapVouchs
    {
        public int AutoId { get; set; }
        public int ID { get; set; }
        public string cBarCode { get; set; }
        public string cInvCode { get; set; }
        public string cFree1 { get; set; }
        public string cFree2 { get; set; }
        public string cFree3 { get; set; }
        public string cFree4 { get; set; }
        public string cFree5 { get; set; }
        public string cFree6 { get; set; }
        public string cFree7 { get; set; }
        public string cFree8 { get; set; }
        public string cFree9 { get; set; }
        public string cFree10 { get; set; }
        public Nullable<double> iQuantity { get; set; }
        public string cAssUnit { get; set; }
        public Nullable<double> iNum { get; set; }
        public Nullable<double> iUnitCost { get; set; }
        public Nullable<decimal> iPrice { get; set; }
        public Nullable<double> iPUnitCost { get; set; }
        public Nullable<decimal> iPPrice { get; set; }
        public string cBatch { get; set; }
        public string cItem_class { get; set; }
        public string cItemCName { get; set; }
        public string cItemCode { get; set; }
        public string cName { get; set; }
        public string cDefine22 { get; set; }
        public string cDefine23 { get; set; }
        public string cDefine24 { get; set; }
        public string cDefine25 { get; set; }
        public Nullable<double> cDefine26 { get; set; }
        public Nullable<double> cDefine27 { get; set; }
        public string cDefine28 { get; set; }
        public string cDefine29 { get; set; }
        public string cDefine30 { get; set; }
        public string cDefine31 { get; set; }
        public string cDefine32 { get; set; }
        public string cDefine33 { get; set; }
        public Nullable<int> cDefine34 { get; set; }
        public Nullable<int> cDefine35 { get; set; }
        public Nullable<System.DateTime> cDefine36 { get; set; }
        public Nullable<System.DateTime> cDefine37 { get; set; }
        public string cBVencode { get; set; }
        public Nullable<int> iCheckIds { get; set; }
        public Nullable<int> iArvIds { get; set; }
        public Nullable<int> iMassDate { get; set; }
        public string cInVouchCode { get; set; }
        public Nullable<System.DateTime> dDealDate { get; set; }
        public string cDealPlace { get; set; }
        public string cDealMode { get; set; }
        public Nullable<System.DateTime> dMadeDate { get; set; }
        public string cGspState { get; set; }
        public Nullable<int> rdsid { get; set; }
        public Nullable<System.DateTime> dVDate { get; set; }
        public string cRejectCode { get; set; }
        public Nullable<int> iRejectIds { get; set; }
        public string cCheckPersonCode { get; set; }
        public Nullable<System.DateTime> dCheckDate { get; set; }
        public string cCheckCode { get; set; }
        public Nullable<bool> bRelated { get; set; }
        public Nullable<int> impoids { get; set; }
        public Nullable<short> cMassUnit { get; set; }
        public Nullable<int> iSoType { get; set; }
        public string iSodid { get; set; }
        public string cvmivencode { get; set; }
        public Nullable<int> iinvsncount { get; set; }
        public Nullable<short> iExpiratDateCalcu { get; set; }
        public string cExpirationdate { get; set; }
        public Nullable<System.DateTime> dExpirationdate { get; set; }
        public Nullable<decimal> iBondedSumQty { get; set; }
        public Nullable<decimal> cBatchProperty1 { get; set; }
        public Nullable<decimal> cBatchProperty2 { get; set; }
        public Nullable<decimal> cBatchProperty3 { get; set; }
        public Nullable<decimal> cBatchProperty4 { get; set; }
        public Nullable<decimal> cBatchProperty5 { get; set; }
        public string cBatchProperty6 { get; set; }
        public string cBatchProperty7 { get; set; }
        public string cBatchProperty8 { get; set; }
        public string cBatchProperty9 { get; set; }
        public Nullable<System.DateTime> cBatchProperty10 { get; set; }
        public string cbMemo { get; set; }
        public Nullable<int> applydid { get; set; }
        public string applycode { get; set; }
        public string corufts { get; set; }
        public Nullable<int> irowno { get; set; }
        public string cinvouchtype { get; set; }
        public string cbsysbarcode { get; set; }
    }
}
