//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sfc_opaccountcfg
    {
        public int CfgId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<byte> ToOpStatus { get; set; }
        public Nullable<byte> OpFlag { get; set; }
        public Nullable<int> AccStatus1 { get; set; }
        public Nullable<int> AccStatus2 { get; set; }
        public Nullable<int> AccStatus3 { get; set; }
        public Nullable<int> AccStatus4 { get; set; }
        public Nullable<int> AccStatus5 { get; set; }
        public Nullable<int> AccStatus6 { get; set; }
        public Nullable<int> AccStatus7 { get; set; }
        public Nullable<int> AccStatus8 { get; set; }
    }
}
