//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sfc_optranstatus
    {
        public int StatusId { get; set; }
        public Nullable<byte> TransformType { get; set; }
        public Nullable<byte> InterStageFlag { get; set; }
        public Nullable<bool> ReWorkFlag { get; set; }
        public Nullable<byte> FromOpStatus { get; set; }
        public string StatusDesc { get; set; }
    }
}
