//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SR_Feedback
    {
        public string OID { get; set; }
        public int ID { get; set; }
        public Nullable<int> VT_ID { get; set; }
        public string SerRequestID { get; set; }
        public string cCustAdvice { get; set; }
        public string FeedbackModeID { get; set; }
        public string cFeedbackPersonCode { get; set; }
        public Nullable<System.DateTime> dFeedbackDate { get; set; }
        public Nullable<System.DateTime> dFeedbackTime { get; set; }
        public Nullable<bool> bFeedback { get; set; }
        public string cDefine1 { get; set; }
        public string cDefine2 { get; set; }
        public string cDefine3 { get; set; }
        public Nullable<System.DateTime> cDefine4 { get; set; }
        public Nullable<int> cDefine5 { get; set; }
        public Nullable<System.DateTime> cDefine6 { get; set; }
        public Nullable<double> cDefine7 { get; set; }
        public string cDefine8 { get; set; }
        public string cDefine9 { get; set; }
        public string cDefine10 { get; set; }
        public string cDefine11 { get; set; }
        public string cDefine12 { get; set; }
        public string cDefine13 { get; set; }
        public string cDefine14 { get; set; }
        public Nullable<int> cDefine15 { get; set; }
        public Nullable<double> cDefine16 { get; set; }
        public string cCreator { get; set; }
        public Nullable<System.DateTime> dCreatedDate { get; set; }
        public Nullable<System.DateTime> dModifiedDate { get; set; }
        public string cModifier { get; set; }
        public byte[] ufts { get; set; }
        public string cResource { get; set; }
        public Nullable<int> iPrintCount { get; set; }
        public string cCleanVer { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
