//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SR_ServiceItemsHis
    {
        public string OID { get; set; }
        public int AutoID { get; set; }
        public Nullable<int> VT_ID { get; set; }
        public string SerBillID { get; set; }
        public string cInvCode { get; set; }
        public string cItemFlag { get; set; }
        public string cFree1 { get; set; }
        public string cFree2 { get; set; }
        public string cFree3 { get; set; }
        public string cFree4 { get; set; }
        public string cFree5 { get; set; }
        public string cFree6 { get; set; }
        public string cFree7 { get; set; }
        public string cFree8 { get; set; }
        public string cFree9 { get; set; }
        public string cFree10 { get; set; }
        public Nullable<double> fQuantity { get; set; }
        public string cSalesUnitCode { get; set; }
        public Nullable<double> fNumber { get; set; }
        public Nullable<double> fConversionRate { get; set; }
        public Nullable<decimal> mQuotedUnitPrice { get; set; }
        public Nullable<decimal> mTaxUnitPrice { get; set; }
        public Nullable<decimal> mTaxFreeUnitPrice { get; set; }
        public Nullable<decimal> mTaxFreeSum { get; set; }
        public Nullable<decimal> mTaxSum { get; set; }
        public Nullable<decimal> mDiscountSum { get; set; }
        public Nullable<decimal> mTotalSum { get; set; }
        public Nullable<double> fTaxRate { get; set; }
        public Nullable<double> fDiscount1 { get; set; }
        public Nullable<double> fDiscount2 { get; set; }
        public Nullable<decimal> mNatTaxFreeUnitPrice { get; set; }
        public Nullable<decimal> mNatTaxFreeSum { get; set; }
        public Nullable<decimal> mNatTaxSum { get; set; }
        public Nullable<decimal> mNatTotalSum { get; set; }
        public Nullable<decimal> mNatDiscountSum { get; set; }
        public Nullable<double> fDrawQuantitySum { get; set; }
        public Nullable<double> fDrawNumberSum { get; set; }
        public string cDefine22 { get; set; }
        public string cDefine23 { get; set; }
        public string cDefine24 { get; set; }
        public string cDefine25 { get; set; }
        public Nullable<double> cDefine26 { get; set; }
        public Nullable<double> cDefine27 { get; set; }
        public string cDefine28 { get; set; }
        public string cDefine29 { get; set; }
        public string cDefine30 { get; set; }
        public string cDefine31 { get; set; }
        public string cDefine32 { get; set; }
        public string cDefine33 { get; set; }
        public Nullable<int> cDefine34 { get; set; }
        public Nullable<int> cDefine35 { get; set; }
        public Nullable<System.DateTime> cDefine36 { get; set; }
        public Nullable<System.DateTime> cDefine37 { get; set; }
        public string cCreator { get; set; }
        public Nullable<System.DateTime> dCreatedDate { get; set; }
        public string cModifier { get; set; }
        public Nullable<System.DateTime> dModifiedDate { get; set; }
        public byte[] ufts { get; set; }
        public string cTypeClass { get; set; }
        public Nullable<decimal> fDrawJSSum { get; set; }
        public string SerBodyOID { get; set; }
        public Nullable<byte> bRepair { get; set; }
        public string citem_class { get; set; }
        public string citem_cname { get; set; }
        public string citemcode { get; set; }
        public string citemname { get; set; }
    }
}
