//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_RdRecords_bak
    {
        public int autoid { get; set; }
        public Nullable<decimal> itaxrate { get; set; }
        public Nullable<decimal> iPrice { get; set; }
        public Nullable<double> iUnitCost { get; set; }
        public Nullable<decimal> iTaxPrice { get; set; }
        public Nullable<decimal> iSum { get; set; }
        public Nullable<decimal> iOriMoney { get; set; }
        public Nullable<decimal> iOriSum { get; set; }
        public Nullable<decimal> iOriTaxPrice { get; set; }
        public Nullable<decimal> iOriCost { get; set; }
        public Nullable<decimal> iOriTaxCost { get; set; }
    }
}
