//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_SNDefine_base
    {
        public int Autoid { get; set; }
        public Nullable<short> iSNState { get; set; }
        public string cSNFldName { get; set; }
        public string cSNDefineName { get; set; }
        public string localeid { get; set; }
        public string cSNDefineValue { get; set; }
    }
}
