//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Template
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> KindID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] BinaryData { get; set; }
        public Nullable<int> Type_ { get; set; }
        public Nullable<int> IsFlow__ { get; set; }
        public byte[] ImageData { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public Nullable<bool> isSingleNode { get; set; }
    }
}
