//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskExtendField
    {
        public System.Guid cTaskID { get; set; }
        public string ExtendField1 { get; set; }
        public string ExtendField2 { get; set; }
        public string ExtendField3 { get; set; }
        public string ExtendField4 { get; set; }
        public string ExtendField5 { get; set; }
        public string ExtendField6 { get; set; }
        public string ExtendField7 { get; set; }
        public string ExtendField8 { get; set; }
        public string ExtendField9 { get; set; }
        public string ExtendField10 { get; set; }
    }
}
