//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_button_link
    {
        public decimal bl_id { get; set; }
        public short obj_type { get; set; }
        public string bl_name { get; set; }
        public string bl_label { get; set; }
        public string bl_description { get; set; }
        public Nullable<short> disp_type { get; set; }
        public Nullable<int> disp_oder { get; set; }
        public Nullable<short> behavior { get; set; }
        public short url_type { get; set; }
        public string url_content { get; set; }
        public string icon_url { get; set; }
        public Nullable<decimal> icon_id { get; set; }
        public string js_code { get; set; }
        public string php_code { get; set; }
        public short php_code_type { get; set; }
        public Nullable<int> disp_order { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string modify_user_id { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
        public Nullable<short> server_flag { get; set; }
        public byte[] crm_timestamp { get; set; }
        public string self_btn { get; set; }
    }
}
