//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_background_user_task
    {
        public decimal task_id { get; set; }
        public string user_id { get; set; }
        public Nullable<short> obj_type { get; set; }
        public string task_subject { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public short task_status { get; set; }
        public string result_desc { get; set; }
        public Nullable<decimal> max_interval { get; set; }
        public Nullable<decimal> occur_interval { get; set; }
        public Nullable<decimal> total_records { get; set; }
        public Nullable<decimal> success_records { get; set; }
        public Nullable<decimal> fail_records { get; set; }
        public string file_resources { get; set; }
        public Nullable<short> server_flag { get; set; }
        public byte[] crm_timestamp { get; set; }
    }
}
