//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_borrowfeedback_xattr
    {
        public decimal id { get; set; }
        public Nullable<short> bfeedback_int49 { get; set; }
        public Nullable<short> bfeedback_int50 { get; set; }
        public Nullable<short> bfeedback_int51 { get; set; }
        public Nullable<short> bfeedback_int52 { get; set; }
        public Nullable<short> bfeedback_int53 { get; set; }
        public Nullable<short> bfeedback_int54 { get; set; }
        public Nullable<short> bfeedback_int55 { get; set; }
        public Nullable<short> bfeedback_int56 { get; set; }
        public Nullable<short> bfeedback_int57 { get; set; }
        public Nullable<short> bfeedback_int58 { get; set; }
        public Nullable<short> bfeedback_int59 { get; set; }
        public Nullable<short> bfeedback_int60 { get; set; }
        public Nullable<short> bfeedback_int61 { get; set; }
        public Nullable<short> bfeedback_int62 { get; set; }
        public Nullable<short> bfeedback_int63 { get; set; }
        public Nullable<short> bfeedback_int64 { get; set; }
        public string bfeedback_multi21 { get; set; }
        public string bfeedback_multi22 { get; set; }
        public string bfeedback_multi23 { get; set; }
        public string bfeedback_multi24 { get; set; }
        public string bfeedback_multi25 { get; set; }
        public string bfeedback_multi26 { get; set; }
        public string bfeedback_multi27 { get; set; }
        public string bfeedback_multi28 { get; set; }
        public Nullable<decimal> bfeedback_dec25 { get; set; }
        public Nullable<decimal> bfeedback_dec26 { get; set; }
        public Nullable<decimal> bfeedback_dec27 { get; set; }
        public Nullable<decimal> bfeedback_dec28 { get; set; }
        public Nullable<decimal> bfeedback_dec29 { get; set; }
        public Nullable<decimal> bfeedback_dec30 { get; set; }
        public Nullable<decimal> bfeedback_dec31 { get; set; }
        public Nullable<decimal> bfeedback_dec32 { get; set; }
        public string bfeedback_refid05 { get; set; }
        public string bfeedback_refid06 { get; set; }
        public string bfeedback_refid07 { get; set; }
        public string bfeedback_refid08 { get; set; }
        public Nullable<decimal> bfeedback_img01 { get; set; }
        public Nullable<short> server_flag { get; set; }
        public byte[] crm_timestamp { get; set; }
    }
}
