//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_blacklist_xattr
    {
        public decimal blacklist_id { get; set; }
        public Nullable<short> blist_int49 { get; set; }
        public Nullable<short> blist_int50 { get; set; }
        public Nullable<short> blist_int51 { get; set; }
        public Nullable<short> blist_int52 { get; set; }
        public Nullable<short> blist_int53 { get; set; }
        public Nullable<short> blist_int54 { get; set; }
        public Nullable<short> blist_int55 { get; set; }
        public Nullable<short> blist_int56 { get; set; }
        public Nullable<short> blist_int57 { get; set; }
        public Nullable<short> blist_int58 { get; set; }
        public Nullable<short> blist_int59 { get; set; }
        public Nullable<short> blist_int60 { get; set; }
        public Nullable<short> blist_int61 { get; set; }
        public Nullable<short> blist_int62 { get; set; }
        public Nullable<short> blist_int63 { get; set; }
        public Nullable<short> blist_int64 { get; set; }
        public string blist_multi21 { get; set; }
        public string blist_multi22 { get; set; }
        public string blist_multi23 { get; set; }
        public string blist_multi24 { get; set; }
        public string blist_multi25 { get; set; }
        public string blist_multi26 { get; set; }
        public string blist_multi27 { get; set; }
        public string blist_multi28 { get; set; }
        public Nullable<decimal> blist_dec25 { get; set; }
        public Nullable<decimal> blist_dec26 { get; set; }
        public Nullable<decimal> blist_dec27 { get; set; }
        public Nullable<decimal> blist_dec28 { get; set; }
        public Nullable<decimal> blist_dec29 { get; set; }
        public Nullable<decimal> blist_dec30 { get; set; }
        public Nullable<decimal> blist_dec31 { get; set; }
        public Nullable<decimal> blist_dec32 { get; set; }
        public Nullable<decimal> blist_img01 { get; set; }
        public string blist_refid05 { get; set; }
        public string blist_refid06 { get; set; }
        public string blist_refid07 { get; set; }
        public string blist_refid08 { get; set; }
        public Nullable<short> server_flag { get; set; }
        public byte[] crm_timestamp { get; set; }
    }
}
