//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_deliver_attr
    {
        public decimal deliver_id { get; set; }
        public Nullable<short> dlr_int25 { get; set; }
        public Nullable<short> dlr_int26 { get; set; }
        public Nullable<short> dlr_int27 { get; set; }
        public Nullable<short> dlr_int28 { get; set; }
        public Nullable<short> dlr_int29 { get; set; }
        public Nullable<short> dlr_int30 { get; set; }
        public Nullable<short> dlr_int31 { get; set; }
        public Nullable<short> dlr_int32 { get; set; }
        public Nullable<short> dlr_int33 { get; set; }
        public Nullable<short> dlr_int34 { get; set; }
        public Nullable<short> dlr_int35 { get; set; }
        public Nullable<short> dlr_int36 { get; set; }
        public Nullable<short> dlr_int37 { get; set; }
        public Nullable<short> dlr_int38 { get; set; }
        public Nullable<short> dlr_int39 { get; set; }
        public Nullable<short> dlr_int40 { get; set; }
        public Nullable<short> dlr_int41 { get; set; }
        public Nullable<short> dlr_int42 { get; set; }
        public Nullable<short> dlr_int43 { get; set; }
        public Nullable<short> dlr_int44 { get; set; }
        public Nullable<short> dlr_int45 { get; set; }
        public Nullable<short> dlr_int46 { get; set; }
        public Nullable<short> dlr_int47 { get; set; }
        public Nullable<short> dlr_int48 { get; set; }
        public string dlr_multi07 { get; set; }
        public string dlr_multi08 { get; set; }
        public string dlr_multi09 { get; set; }
        public string dlr_multi10 { get; set; }
        public string dlr_multi11 { get; set; }
        public string dlr_multi12 { get; set; }
        public string dlr_multi13 { get; set; }
        public string dlr_multi14 { get; set; }
        public string dlr_multi15 { get; set; }
        public string dlr_multi16 { get; set; }
        public string dlr_multi17 { get; set; }
        public string dlr_multi18 { get; set; }
        public string dlr_multi19 { get; set; }
        public string dlr_multi20 { get; set; }
        public string dlr_char13 { get; set; }
        public string dlr_char14 { get; set; }
        public string dlr_char15 { get; set; }
        public string dlr_char16 { get; set; }
        public Nullable<decimal> dlr_dec17 { get; set; }
        public Nullable<decimal> dlr_dec18 { get; set; }
        public Nullable<decimal> dlr_dec19 { get; set; }
        public Nullable<decimal> dlr_dec20 { get; set; }
        public Nullable<decimal> dlr_dec21 { get; set; }
        public Nullable<decimal> dlr_dec22 { get; set; }
        public Nullable<decimal> dlr_dec23 { get; set; }
        public Nullable<decimal> dlr_dec24 { get; set; }
        public Nullable<System.DateTime> dlr_date09 { get; set; }
        public Nullable<System.DateTime> dlr_date10 { get; set; }
        public Nullable<System.DateTime> dlr_date11 { get; set; }
        public Nullable<System.DateTime> dlr_date12 { get; set; }
        public Nullable<System.DateTime> dlr_date13 { get; set; }
        public Nullable<System.DateTime> dlr_date14 { get; set; }
        public Nullable<System.DateTime> dlr_date15 { get; set; }
        public Nullable<System.DateTime> dlr_date16 { get; set; }
        public string dlr_txt01 { get; set; }
        public string dlr_refid03 { get; set; }
        public string dlr_refid04 { get; set; }
        public Nullable<short> server_flag { get; set; }
        public Nullable<System.DateTime> crm_timestamp { get; set; }
    }
}
