//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_dispatch_xattr
    {
        public decimal dlid { get; set; }
        public Nullable<decimal> dpl_dec25 { get; set; }
        public Nullable<decimal> dpl_dec26 { get; set; }
        public Nullable<decimal> dpl_dec27 { get; set; }
        public Nullable<decimal> dpl_dec28 { get; set; }
        public Nullable<decimal> dpl_dec29 { get; set; }
        public Nullable<decimal> dpl_dec30 { get; set; }
        public Nullable<decimal> dpl_dec31 { get; set; }
        public Nullable<decimal> dpl_dec32 { get; set; }
        public Nullable<short> server_flag { get; set; }
        public byte[] crm_timestamp { get; set; }
    }
}
