//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_forum_attr
    {
        public decimal forum_id { get; set; }
        public Nullable<short> slt_int25 { get; set; }
        public Nullable<short> slt_int26 { get; set; }
        public Nullable<short> slt_int27 { get; set; }
        public Nullable<short> slt_int28 { get; set; }
        public Nullable<short> slt_int29 { get; set; }
        public Nullable<short> slt_int30 { get; set; }
        public Nullable<short> slt_int31 { get; set; }
        public Nullable<short> slt_int32 { get; set; }
        public Nullable<short> slt_int33 { get; set; }
        public Nullable<short> slt_int34 { get; set; }
        public Nullable<short> slt_int35 { get; set; }
        public Nullable<short> slt_int36 { get; set; }
        public Nullable<short> slt_int37 { get; set; }
        public Nullable<short> slt_int38 { get; set; }
        public Nullable<short> slt_int39 { get; set; }
        public Nullable<short> slt_int40 { get; set; }
        public Nullable<short> slt_int41 { get; set; }
        public Nullable<short> slt_int42 { get; set; }
        public Nullable<short> slt_int43 { get; set; }
        public Nullable<short> slt_int44 { get; set; }
        public Nullable<short> slt_int45 { get; set; }
        public Nullable<short> slt_int46 { get; set; }
        public Nullable<short> slt_int47 { get; set; }
        public Nullable<short> slt_int48 { get; set; }
        public string slt_multi07 { get; set; }
        public string slt_multi08 { get; set; }
        public string slt_multi09 { get; set; }
        public string slt_multi10 { get; set; }
        public string slt_multi11 { get; set; }
        public string slt_multi12 { get; set; }
        public string slt_multi13 { get; set; }
        public string slt_multi14 { get; set; }
        public string slt_multi15 { get; set; }
        public string slt_multi16 { get; set; }
        public string slt_multi17 { get; set; }
        public string slt_multi18 { get; set; }
        public string slt_multi19 { get; set; }
        public string slt_multi20 { get; set; }
        public string slt_char13 { get; set; }
        public string slt_char14 { get; set; }
        public string slt_char15 { get; set; }
        public string slt_char16 { get; set; }
        public Nullable<decimal> slt_dec17 { get; set; }
        public Nullable<decimal> slt_dec18 { get; set; }
        public Nullable<decimal> slt_dec19 { get; set; }
        public Nullable<decimal> slt_dec20 { get; set; }
        public Nullable<decimal> slt_dec21 { get; set; }
        public Nullable<decimal> slt_dec22 { get; set; }
        public Nullable<decimal> slt_dec23 { get; set; }
        public Nullable<decimal> slt_dec24 { get; set; }
        public Nullable<System.DateTime> slt_date09 { get; set; }
        public Nullable<System.DateTime> slt_date10 { get; set; }
        public Nullable<System.DateTime> slt_date11 { get; set; }
        public Nullable<System.DateTime> slt_date12 { get; set; }
        public Nullable<System.DateTime> slt_date13 { get; set; }
        public Nullable<System.DateTime> slt_date14 { get; set; }
        public Nullable<System.DateTime> slt_date15 { get; set; }
        public Nullable<System.DateTime> slt_date16 { get; set; }
        public string slt_txt01 { get; set; }
        public string slt_refid03 { get; set; }
        public string slt_refid04 { get; set; }
        public Nullable<short> server_flag { get; set; }
        public byte[] crm_timestamp { get; set; }
    }
}
