//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_failurelog_d
    {
        public decimal failurelog_d_id { get; set; }
        public decimal failurelog_id { get; set; }
        public string product_id { get; set; }
        public string unit_id { get; set; }
        public string cbatch { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> piece { get; set; }
        public Nullable<decimal> suminqty { get; set; }
        public Nullable<decimal> sumoutqty { get; set; }
        public Nullable<decimal> suminpiece { get; set; }
        public Nullable<decimal> sumoutpiece { get; set; }
        public string sn { get; set; }
        public Nullable<short> failurelog_d_int01 { get; set; }
        public Nullable<short> failurelog_d_int02 { get; set; }
        public Nullable<short> failurelog_d_int03 { get; set; }
        public Nullable<short> failurelog_d_int04 { get; set; }
        public Nullable<short> failurelog_d_int05 { get; set; }
        public Nullable<short> failurelog_d_int06 { get; set; }
        public Nullable<short> failurelog_d_int07 { get; set; }
        public Nullable<short> failurelog_d_int08 { get; set; }
        public Nullable<short> failurelog_d_int09 { get; set; }
        public Nullable<short> failurelog_d_int10 { get; set; }
        public Nullable<short> failurelog_d_int11 { get; set; }
        public Nullable<short> failurelog_d_int12 { get; set; }
        public Nullable<short> failurelog_d_int13 { get; set; }
        public Nullable<short> failurelog_d_int14 { get; set; }
        public Nullable<short> failurelog_d_int15 { get; set; }
        public Nullable<short> failurelog_d_int16 { get; set; }
        public Nullable<short> failurelog_d_int17 { get; set; }
        public Nullable<short> failurelog_d_int18 { get; set; }
        public Nullable<short> failurelog_d_int19 { get; set; }
        public Nullable<short> failurelog_d_int20 { get; set; }
        public Nullable<short> failurelog_d_int21 { get; set; }
        public Nullable<short> failurelog_d_int22 { get; set; }
        public Nullable<short> failurelog_d_int23 { get; set; }
        public Nullable<short> failurelog_d_int24 { get; set; }
        public string failurelog_d_multi01 { get; set; }
        public string failurelog_d_multi02 { get; set; }
        public string failurelog_d_multi03 { get; set; }
        public string failurelog_d_multi04 { get; set; }
        public string failurelog_d_multi05 { get; set; }
        public string failurelog_d_multi06 { get; set; }
        public string failurelog_d_char01 { get; set; }
        public string failurelog_d_char02 { get; set; }
        public string failurelog_d_char03 { get; set; }
        public string failurelog_d_char04 { get; set; }
        public string failurelog_d_char05 { get; set; }
        public string failurelog_d_char06 { get; set; }
        public string failurelog_d_char07 { get; set; }
        public string failurelog_d_char08 { get; set; }
        public string failurelog_d_char09 { get; set; }
        public string failurelog_d_char10 { get; set; }
        public string failurelog_d_char11 { get; set; }
        public string failurelog_d_char12 { get; set; }
        public Nullable<decimal> failurelog_d_dec01 { get; set; }
        public Nullable<decimal> failurelog_d_dec02 { get; set; }
        public Nullable<decimal> failurelog_d_dec03 { get; set; }
        public Nullable<decimal> failurelog_d_dec04 { get; set; }
        public Nullable<decimal> failurelog_d_dec05 { get; set; }
        public Nullable<decimal> failurelog_d_dec06 { get; set; }
        public Nullable<decimal> failurelog_d_dec07 { get; set; }
        public Nullable<decimal> failurelog_d_dec08 { get; set; }
        public Nullable<decimal> failurelog_d_dec09 { get; set; }
        public Nullable<decimal> failurelog_d_dec10 { get; set; }
        public Nullable<decimal> failurelog_d_dec11 { get; set; }
        public Nullable<decimal> failurelog_d_dec12 { get; set; }
        public Nullable<decimal> failurelog_d_dec13 { get; set; }
        public Nullable<decimal> failurelog_d_dec14 { get; set; }
        public Nullable<decimal> failurelog_d_dec15 { get; set; }
        public Nullable<decimal> failurelog_d_dec16 { get; set; }
        public Nullable<System.DateTime> failurelog_d_date01 { get; set; }
        public Nullable<System.DateTime> failurelog_d_date02 { get; set; }
        public Nullable<System.DateTime> failurelog_d_date03 { get; set; }
        public Nullable<System.DateTime> failurelog_d_date04 { get; set; }
        public Nullable<System.DateTime> failurelog_d_date05 { get; set; }
        public Nullable<System.DateTime> failurelog_d_date06 { get; set; }
        public Nullable<System.DateTime> failurelog_d_date07 { get; set; }
        public Nullable<System.DateTime> failurelog_d_date08 { get; set; }
        public string failurelog_d_refid01 { get; set; }
        public string failurelog_d_refid02 { get; set; }
        public Nullable<short> is_deleted { get; set; }
        public Nullable<decimal> deleted_user_id { get; set; }
        public Nullable<System.DateTime> deleted_time { get; set; }
        public Nullable<decimal> deleted_id { get; set; }
        public Nullable<short> server_flag { get; set; }
        public byte[] crm_timestamp { get; set; }
    }
}
