//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_profile_trans
    {
        public decimal profile_trans_id { get; set; }
        public decimal profile_id { get; set; }
        public string src_attribute { get; set; }
        public string dest_attribute { get; set; }
        public short sys_flag { get; set; }
        public string dest_prefix { get; set; }
        public string dest_postfix { get; set; }
        public string create_emp_id { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string modify_emp_id { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public short server_flag { get; set; }
        public byte[] crm_timestamp { get; set; }
    }
}
