//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_queue_remind
    {
        public decimal remind_id { get; set; }
        public Nullable<decimal> queue_id { get; set; }
        public Nullable<short> remind_flag { get; set; }
        public Nullable<short> remind_user { get; set; }
        public Nullable<short> remind_sms { get; set; }
        public Nullable<short> remind_email { get; set; }
        public Nullable<short> remind_notice { get; set; }
        public string remind_description { get; set; }
        public Nullable<short> server_flag { get; set; }
        public byte[] crm_timestamp { get; set; }
    }
}
