//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_receipt
    {
        public decimal receipt_id { get; set; }
        public string receipt_name { get; set; }
        public Nullable<decimal> type { get; set; }
        public string dept_id { get; set; }
        public string owner_user_id { get; set; }
        public string account_id { get; set; }
        public Nullable<int> currency_id { get; set; }
        public Nullable<decimal> exchange_ratio { get; set; }
        public Nullable<short> pay_type { get; set; }
        public Nullable<decimal> foreign_pay_amount { get; set; }
        public Nullable<decimal> instead_amount { get; set; }
        public Nullable<decimal> unmatched_amount { get; set; }
        public Nullable<decimal> receipted_amount { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> receipted_date { get; set; }
        public Nullable<short> rec_int01 { get; set; }
        public Nullable<short> rec_int02 { get; set; }
        public Nullable<short> rec_int03 { get; set; }
        public Nullable<short> rec_int04 { get; set; }
        public Nullable<short> rec_int05 { get; set; }
        public Nullable<short> rec_int06 { get; set; }
        public Nullable<short> rec_int07 { get; set; }
        public Nullable<short> rec_int08 { get; set; }
        public Nullable<short> rec_int09 { get; set; }
        public Nullable<short> rec_int10 { get; set; }
        public Nullable<short> rec_int11 { get; set; }
        public Nullable<short> rec_int12 { get; set; }
        public Nullable<short> rec_int13 { get; set; }
        public Nullable<short> rec_int14 { get; set; }
        public Nullable<short> rec_int15 { get; set; }
        public Nullable<short> rec_int16 { get; set; }
        public Nullable<short> rec_int17 { get; set; }
        public Nullable<short> rec_int18 { get; set; }
        public Nullable<short> rec_int19 { get; set; }
        public Nullable<short> rec_int20 { get; set; }
        public Nullable<short> rec_int21 { get; set; }
        public Nullable<short> rec_int22 { get; set; }
        public Nullable<short> rec_int23 { get; set; }
        public Nullable<short> rec_int24 { get; set; }
        public string rec_multi01 { get; set; }
        public string rec_multi02 { get; set; }
        public string rec_multi03 { get; set; }
        public string rec_multi04 { get; set; }
        public string rec_multi05 { get; set; }
        public string rec_multi06 { get; set; }
        public string rec_char01 { get; set; }
        public string rec_char02 { get; set; }
        public string rec_char03 { get; set; }
        public string rec_char04 { get; set; }
        public string rec_char05 { get; set; }
        public string rec_char06 { get; set; }
        public string rec_char07 { get; set; }
        public string rec_char08 { get; set; }
        public string rec_char09 { get; set; }
        public string rec_char10 { get; set; }
        public string rec_char11 { get; set; }
        public string rec_char12 { get; set; }
        public Nullable<decimal> rec_dec01 { get; set; }
        public Nullable<decimal> rec_dec02 { get; set; }
        public Nullable<decimal> rec_dec03 { get; set; }
        public Nullable<decimal> rec_dec04 { get; set; }
        public Nullable<decimal> rec_dec05 { get; set; }
        public Nullable<decimal> rec_dec06 { get; set; }
        public Nullable<decimal> rec_dec07 { get; set; }
        public Nullable<decimal> rec_dec08 { get; set; }
        public Nullable<decimal> rec_dec09 { get; set; }
        public Nullable<decimal> rec_dec10 { get; set; }
        public Nullable<decimal> rec_dec11 { get; set; }
        public Nullable<decimal> rec_dec12 { get; set; }
        public Nullable<decimal> rec_dec13 { get; set; }
        public Nullable<decimal> rec_dec14 { get; set; }
        public Nullable<decimal> rec_dec15 { get; set; }
        public Nullable<decimal> rec_dec16 { get; set; }
        public Nullable<System.DateTime> rec_date01 { get; set; }
        public Nullable<System.DateTime> rec_date02 { get; set; }
        public Nullable<System.DateTime> rec_date03 { get; set; }
        public Nullable<System.DateTime> rec_date04 { get; set; }
        public Nullable<System.DateTime> rec_date05 { get; set; }
        public Nullable<System.DateTime> rec_date06 { get; set; }
        public Nullable<System.DateTime> rec_date07 { get; set; }
        public Nullable<System.DateTime> rec_date08 { get; set; }
        public string rec_refid01 { get; set; }
        public string rec_refid02 { get; set; }
        public string close_user_id { get; set; }
        public Nullable<System.DateTime> close_date { get; set; }
        public Nullable<short> close_flag { get; set; }
        public Nullable<short> is_deleted { get; set; }
        public string deleted_user_id { get; set; }
        public Nullable<System.DateTime> deleted_time { get; set; }
        public Nullable<decimal> deleted_id { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string modify_user_id { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
        public string identify_code { get; set; }
        public Nullable<short> server_flag { get; set; }
        public Nullable<System.DateTime> crm_timestamp { get; set; }
        public string privilege_01 { get; set; }
        public string privilege_02 { get; set; }
        public string privilege_03 { get; set; }
        public string privilege_04 { get; set; }
        public Nullable<decimal> audit_stage_id { get; set; }
        public Nullable<decimal> audit_flow_id { get; set; }
        public Nullable<short> audit_flag { get; set; }
        public string submit_user_id { get; set; }
        public Nullable<System.DateTime> submit_time { get; set; }
        public string audit_user_id { get; set; }
        public Nullable<System.DateTime> audit_time { get; set; }
        public string activated_user_id { get; set; }
        public Nullable<System.DateTime> activated_time { get; set; }
        public Nullable<short> receipt_is_valid { get; set; }
    }
}
