//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_remind_conf
    {
        public string user_id { get; set; }
        public short obj_type { get; set; }
        public Nullable<short> on_event_type { get; set; }
        public Nullable<short> remind_scope { get; set; }
        public string query_conds { get; set; }
        public Nullable<short> remind_to_desktop { get; set; }
        public Nullable<short> remind_to_email { get; set; }
        public Nullable<short> remind_to_sms { get; set; }
        public string remind_email { get; set; }
        public string remind_mobile { get; set; }
        public Nullable<short> code_flag { get; set; }
        public string code { get; set; }
        public Nullable<decimal> system_action { get; set; }
        public Nullable<short> server_flag { get; set; }
        public byte[] crm_timestamp { get; set; }
    }
}
