//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_servicesettle_d_xattr
    {
        public string OID { get; set; }
        public Nullable<short> sersetd_int49 { get; set; }
        public Nullable<short> sersetd_int50 { get; set; }
        public Nullable<short> sersetd_int51 { get; set; }
        public Nullable<short> sersetd_int52 { get; set; }
        public Nullable<short> sersetd_int53 { get; set; }
        public Nullable<short> sersetd_int54 { get; set; }
        public Nullable<short> sersetd_int55 { get; set; }
        public Nullable<short> sersetd_int56 { get; set; }
        public Nullable<short> sersetd_int57 { get; set; }
        public Nullable<short> sersetd_int58 { get; set; }
        public Nullable<short> sersetd_int59 { get; set; }
        public Nullable<short> sersetd_int60 { get; set; }
        public Nullable<short> sersetd_int61 { get; set; }
        public Nullable<short> sersetd_int62 { get; set; }
        public Nullable<short> sersetd_int63 { get; set; }
        public Nullable<short> sersetd_int64 { get; set; }
        public string sersetd_multi21 { get; set; }
        public string sersetd_multi22 { get; set; }
        public string sersetd_multi23 { get; set; }
        public string sersetd_multi24 { get; set; }
        public string sersetd_multi25 { get; set; }
        public string sersetd_multi26 { get; set; }
        public string sersetd_multi27 { get; set; }
        public string sersetd_multi28 { get; set; }
        public Nullable<decimal> sersetd_dec25 { get; set; }
        public Nullable<decimal> sersetd_dec26 { get; set; }
        public Nullable<decimal> sersetd_dec27 { get; set; }
        public Nullable<decimal> sersetd_dec28 { get; set; }
        public Nullable<decimal> sersetd_dec29 { get; set; }
        public Nullable<decimal> sersetd_dec30 { get; set; }
        public Nullable<decimal> sersetd_dec31 { get; set; }
        public Nullable<decimal> sersetd_dec32 { get; set; }
        public Nullable<decimal> sersetd_img01 { get; set; }
        public Nullable<decimal> sersetd_refid05 { get; set; }
        public Nullable<decimal> sersetd_refid06 { get; set; }
        public Nullable<decimal> sersetd_refid07 { get; set; }
        public Nullable<decimal> sersetd_refid08 { get; set; }
        public Nullable<short> server_flag { get; set; }
        public byte[] crm_timestamp { get; set; }
    }
}
