//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_user_list_report
    {
        public decimal report_id { get; set; }
        public decimal obj_type { get; set; }
        public decimal type_id { get; set; }
        public decimal report_class { get; set; }
        public string report_name { get; set; }
        public string quick_list_flds { get; set; }
        public string quick_cond_flds { get; set; }
        public decimal disp_nums { get; set; }
        public short is_default { get; set; }
        public Nullable<short> server_flag { get; set; }
        public byte[] crm_timestamp { get; set; }
    }
}
