//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_voicemail
    {
        public decimal voicemail_id { get; set; }
        public string caller_number { get; set; }
        public string called_number { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public Nullable<decimal> how_long { get; set; }
        public Nullable<decimal> ipagent_id { get; set; }
        public string account_id { get; set; }
        public Nullable<short> voicemail_status { get; set; }
        public string dept_id { get; set; }
        public string owner_user_id { get; set; }
        public string file_path { get; set; }
        public string identify_code { get; set; }
        public Nullable<short> voicemail_int01 { get; set; }
        public Nullable<short> voicemail_int02 { get; set; }
        public Nullable<short> voicemail_int03 { get; set; }
        public Nullable<short> voicemail_int04 { get; set; }
        public Nullable<short> voicemail_int05 { get; set; }
        public Nullable<short> voicemail_int06 { get; set; }
        public Nullable<short> voicemail_int07 { get; set; }
        public Nullable<short> voicemail_int08 { get; set; }
        public Nullable<short> voicemail_int09 { get; set; }
        public Nullable<short> voicemail_int10 { get; set; }
        public Nullable<short> voicemail_int11 { get; set; }
        public Nullable<short> voicemail_int12 { get; set; }
        public Nullable<short> voicemail_int13 { get; set; }
        public Nullable<short> voicemail_int14 { get; set; }
        public Nullable<short> voicemail_int15 { get; set; }
        public Nullable<short> voicemail_int16 { get; set; }
        public Nullable<short> voicemail_int17 { get; set; }
        public Nullable<short> voicemail_int18 { get; set; }
        public Nullable<short> voicemail_int19 { get; set; }
        public Nullable<short> voicemail_int20 { get; set; }
        public Nullable<short> voicemail_int21 { get; set; }
        public Nullable<short> voicemail_int22 { get; set; }
        public Nullable<short> voicemail_int23 { get; set; }
        public Nullable<short> voicemail_int24 { get; set; }
        public string voicemail_multi01 { get; set; }
        public string voicemail_multi02 { get; set; }
        public string voicemail_multi03 { get; set; }
        public string voicemail_multi04 { get; set; }
        public string voicemail_multi05 { get; set; }
        public string voicemail_multi06 { get; set; }
        public string voicemail_char01 { get; set; }
        public string voicemail_char02 { get; set; }
        public string voicemail_char03 { get; set; }
        public string voicemail_char04 { get; set; }
        public string voicemail_char05 { get; set; }
        public string voicemail_char06 { get; set; }
        public string voicemail_char07 { get; set; }
        public string voicemail_char08 { get; set; }
        public string voicemail_char09 { get; set; }
        public string voicemail_char10 { get; set; }
        public string voicemail_char11 { get; set; }
        public string voicemail_char12 { get; set; }
        public Nullable<decimal> voicemail_dec01 { get; set; }
        public Nullable<decimal> voicemail_dec02 { get; set; }
        public Nullable<decimal> voicemail_dec03 { get; set; }
        public Nullable<decimal> voicemail_dec04 { get; set; }
        public Nullable<decimal> voicemail_dec05 { get; set; }
        public Nullable<decimal> voicemail_dec06 { get; set; }
        public Nullable<decimal> voicemail_dec07 { get; set; }
        public Nullable<decimal> voicemail_dec08 { get; set; }
        public Nullable<decimal> voicemail_dec09 { get; set; }
        public Nullable<decimal> voicemail_dec10 { get; set; }
        public Nullable<decimal> voicemail_dec11 { get; set; }
        public Nullable<decimal> voicemail_dec12 { get; set; }
        public Nullable<decimal> voicemail_dec13 { get; set; }
        public Nullable<decimal> voicemail_dec14 { get; set; }
        public Nullable<decimal> voicemail_dec15 { get; set; }
        public Nullable<decimal> voicemail_dec16 { get; set; }
        public Nullable<System.DateTime> voicemail_date01 { get; set; }
        public Nullable<System.DateTime> voicemail_date02 { get; set; }
        public Nullable<System.DateTime> voicemail_date03 { get; set; }
        public Nullable<System.DateTime> voicemail_date04 { get; set; }
        public Nullable<System.DateTime> voicemail_date05 { get; set; }
        public Nullable<System.DateTime> voicemail_date06 { get; set; }
        public Nullable<System.DateTime> voicemail_date07 { get; set; }
        public Nullable<System.DateTime> voicemail_date08 { get; set; }
        public string voicemail_refid01 { get; set; }
        public string voicemail_refid02 { get; set; }
        public Nullable<short> is_deleted { get; set; }
        public string deleted_user_id { get; set; }
        public Nullable<System.DateTime> deleted_time { get; set; }
        public Nullable<decimal> deleted_id { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string modify_user_id { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
        public Nullable<short> server_flag { get; set; }
        public byte[] crm_timestamp { get; set; }
        public string privilege_01 { get; set; }
        public string privilege_02 { get; set; }
        public string privilege_03 { get; set; }
        public string privilege_04 { get; set; }
    }
}
