//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_worksheet_d_attr
    {
        public decimal ws_d_id { get; set; }
        public Nullable<short> wsd_int25 { get; set; }
        public Nullable<short> wsd_int26 { get; set; }
        public Nullable<short> wsd_int27 { get; set; }
        public Nullable<short> wsd_int28 { get; set; }
        public Nullable<short> wsd_int29 { get; set; }
        public Nullable<short> wsd_int30 { get; set; }
        public Nullable<short> wsd_int31 { get; set; }
        public Nullable<short> wsd_int32 { get; set; }
        public Nullable<short> wsd_int33 { get; set; }
        public Nullable<short> wsd_int34 { get; set; }
        public Nullable<short> wsd_int35 { get; set; }
        public Nullable<short> wsd_int36 { get; set; }
        public Nullable<short> wsd_int37 { get; set; }
        public Nullable<short> wsd_int38 { get; set; }
        public Nullable<short> wsd_int39 { get; set; }
        public Nullable<short> wsd_int40 { get; set; }
        public Nullable<short> wsd_int41 { get; set; }
        public Nullable<short> wsd_int42 { get; set; }
        public Nullable<short> wsd_int43 { get; set; }
        public Nullable<short> wsd_int44 { get; set; }
        public Nullable<short> wsd_int45 { get; set; }
        public Nullable<short> wsd_int46 { get; set; }
        public Nullable<short> wsd_int47 { get; set; }
        public Nullable<short> wsd_int48 { get; set; }
        public string wsd_multi07 { get; set; }
        public string wsd_multi08 { get; set; }
        public string wsd_multi09 { get; set; }
        public string wsd_multi10 { get; set; }
        public string wsd_multi11 { get; set; }
        public string wsd_multi12 { get; set; }
        public string wsd_multi13 { get; set; }
        public string wsd_multi14 { get; set; }
        public string wsd_multi15 { get; set; }
        public string wsd_multi16 { get; set; }
        public string wsd_multi17 { get; set; }
        public string wsd_multi18 { get; set; }
        public string wsd_multi19 { get; set; }
        public string wsd_multi20 { get; set; }
        public string wsd_char13 { get; set; }
        public string wsd_char14 { get; set; }
        public string wsd_char15 { get; set; }
        public string wsd_char16 { get; set; }
        public Nullable<decimal> wsd_dec17 { get; set; }
        public Nullable<decimal> wsd_dec18 { get; set; }
        public Nullable<decimal> wsd_dec19 { get; set; }
        public Nullable<decimal> wsd_dec20 { get; set; }
        public Nullable<decimal> wsd_dec21 { get; set; }
        public Nullable<decimal> wsd_dec22 { get; set; }
        public Nullable<decimal> wsd_dec23 { get; set; }
        public Nullable<decimal> wsd_dec24 { get; set; }
        public Nullable<System.DateTime> wsd_date09 { get; set; }
        public Nullable<System.DateTime> wsd_date10 { get; set; }
        public Nullable<System.DateTime> wsd_date11 { get; set; }
        public Nullable<System.DateTime> wsd_date12 { get; set; }
        public Nullable<System.DateTime> wsd_date13 { get; set; }
        public Nullable<System.DateTime> wsd_date14 { get; set; }
        public Nullable<System.DateTime> wsd_date15 { get; set; }
        public Nullable<System.DateTime> wsd_date16 { get; set; }
        public string wsd_txt01 { get; set; }
        public string wsd_refid03 { get; set; }
        public string wsd_refid04 { get; set; }
        public Nullable<short> server_flag { get; set; }
        public byte[] crm_timestamp { get; set; }
    }
}
