//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_worksheet_attr
    {
        public decimal ws_id { get; set; }
        public Nullable<short> ws_int25 { get; set; }
        public Nullable<short> ws_int26 { get; set; }
        public Nullable<short> ws_int27 { get; set; }
        public Nullable<short> ws_int28 { get; set; }
        public Nullable<short> ws_int29 { get; set; }
        public Nullable<short> ws_int30 { get; set; }
        public Nullable<short> ws_int31 { get; set; }
        public Nullable<short> ws_int32 { get; set; }
        public Nullable<short> ws_int33 { get; set; }
        public Nullable<short> ws_int34 { get; set; }
        public Nullable<short> ws_int35 { get; set; }
        public Nullable<short> ws_int36 { get; set; }
        public Nullable<short> ws_int37 { get; set; }
        public Nullable<short> ws_int38 { get; set; }
        public Nullable<short> ws_int39 { get; set; }
        public Nullable<short> ws_int40 { get; set; }
        public Nullable<short> ws_int41 { get; set; }
        public Nullable<short> ws_int42 { get; set; }
        public Nullable<short> ws_int43 { get; set; }
        public Nullable<short> ws_int44 { get; set; }
        public Nullable<short> ws_int45 { get; set; }
        public Nullable<short> ws_int46 { get; set; }
        public Nullable<short> ws_int47 { get; set; }
        public Nullable<short> ws_int48 { get; set; }
        public string ws_multi07 { get; set; }
        public string ws_multi08 { get; set; }
        public string ws_multi09 { get; set; }
        public string ws_multi10 { get; set; }
        public string ws_multi11 { get; set; }
        public string ws_multi12 { get; set; }
        public string ws_multi13 { get; set; }
        public string ws_multi14 { get; set; }
        public string ws_multi15 { get; set; }
        public string ws_multi16 { get; set; }
        public string ws_multi17 { get; set; }
        public string ws_multi18 { get; set; }
        public string ws_multi19 { get; set; }
        public string ws_multi20 { get; set; }
        public string ws_char13 { get; set; }
        public string ws_char14 { get; set; }
        public string ws_char15 { get; set; }
        public string ws_char16 { get; set; }
        public Nullable<decimal> ws_dec17 { get; set; }
        public Nullable<decimal> ws_dec18 { get; set; }
        public Nullable<decimal> ws_dec19 { get; set; }
        public Nullable<decimal> ws_dec20 { get; set; }
        public Nullable<decimal> ws_dec21 { get; set; }
        public Nullable<decimal> ws_dec22 { get; set; }
        public Nullable<decimal> ws_dec23 { get; set; }
        public Nullable<decimal> ws_dec24 { get; set; }
        public Nullable<System.DateTime> ws_date09 { get; set; }
        public Nullable<System.DateTime> ws_date10 { get; set; }
        public Nullable<System.DateTime> ws_date11 { get; set; }
        public Nullable<System.DateTime> ws_date12 { get; set; }
        public Nullable<System.DateTime> ws_date13 { get; set; }
        public Nullable<System.DateTime> ws_date14 { get; set; }
        public Nullable<System.DateTime> ws_date15 { get; set; }
        public Nullable<System.DateTime> ws_date16 { get; set; }
        public string ws_txt01 { get; set; }
        public string ws_refid03 { get; set; }
        public string ws_refid04 { get; set; }
        public Nullable<short> server_flag { get; set; }
        public byte[] crm_timestamp { get; set; }
    }
}
