//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class U8TaskFactory
    {
        public string FactoryClassID { get; set; }
        public string subid { get; set; }
        public string cAuthID { get; set; }
        public string Type { get; set; }
        public byte[] pubufts { get; set; }
        public int FunctionType { get; set; }
    }
}
