//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UA_FlowItems_Ex
    {
        public string cSubSys { get; set; }
        public string cUserId { get; set; }
        public string cCmdId { get; set; }
        public string cCmdName { get; set; }
        public string cShortcut { get; set; }
        public int nImage { get; set; }
        public double fX { get; set; }
        public double fY { get; set; }
        public string cAccId { get; set; }
    }
}
