//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAP_ReportUserState
    {
        public string userId { get; set; }
        public string ReportId { get; set; }
        public Nullable<short> PrintSet { get; set; }
        public Nullable<short> printDefault { get; set; }
        public Nullable<short> FilterInfo { get; set; }
        public Nullable<short> ExtendState { get; set; }
        public Nullable<bool> IncludeBackColor { get; set; }
        public Nullable<short> Layout { get; set; }
    }
}
