//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UFFA_Model_fa_CardOfPUColSet_Init
    {
        public byte iFun { get; set; }
        public string sIDKey { get; set; }
        public int iColPos { get; set; }
        public bool bFixed { get; set; }
        public bool bDisp { get; set; }
        public bool bMustSel { get; set; }
    }
}
