//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UFSUB_dsign
    {
        public int i_id { get; set; }
        public string csign { get; set; }
        public byte isignseq { get; set; }
        public string ctext { get; set; }
        public Nullable<byte> itype { get; set; }
        public Nullable<int> iotherused { get; set; }
    }
}
