//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UFTmpTable_2904843_5309696728677335210
    {
        public int baseid { get; set; }
        public string iperiod { get; set; }
        public string cdepName { get; set; }
        public decimal lastcost { get; set; }
        public Nullable<decimal> LastPercent { get; set; }
        public decimal thiscost { get; set; }
        public Nullable<decimal> thisPercent { get; set; }
        public decimal totalcost { get; set; }
        public Nullable<decimal> totalPercent { get; set; }
    }
}
