//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UFTmpTable_14674387_5227481438121208402
    {
        public int baseid { get; set; }
        public string cinvcode { get; set; }
        public Nullable<int> iinvid { get; set; }
        public string ccuscode { get; set; }
        public string cauthid { get; set; }
        public string cdepcode { get; set; }
        public string cPersoncode { get; set; }
        public string cmaker { get; set; }
        public string cstcode { get; set; }
        public System.DateTime 日期 { get; set; }
        public string 销售类型名称 { get; set; }
        public string 业务类型 { get; set; }
        public string 客户分类名称 { get; set; }
        public string 客户分类编码 { get; set; }
        public string 客户名称 { get; set; }
        public string 客户简称 { get; set; }
        public string 客户级别 { get; set; }
        public string ccuspersoncode { get; set; }
        public string 客户级别编码 { get; set; }
        public string 行业名称 { get; set; }
        public string 行业编码 { get; set; }
        public string 地区分类 { get; set; }
        public string 地区分类编码 { get; set; }
        public string 总公司编码 { get; set; }
        public string 总公司名称 { get; set; }
        public string 部门名称 { get; set; }
        public string 业务员名称 { get; set; }
        public string 存货分类编码 { get; set; }
        public string 存货分类名称 { get; set; }
        public string 存货名称 { get; set; }
        public string 规格型号 { get; set; }
        public string 存货代码 { get; set; }
        public string cfree1 { get; set; }
        public string cfree2 { get; set; }
        public string cfree3 { get; set; }
        public string cfree4 { get; set; }
        public string cfree5 { get; set; }
        public string cfree6 { get; set; }
        public string cfree7 { get; set; }
        public string cfree8 { get; set; }
        public string cfree9 { get; set; }
        public string cfree10 { get; set; }
        public string cinvdefine1 { get; set; }
        public string cinvdefine2 { get; set; }
        public string cinvdefine3 { get; set; }
        public string cinvdefine4 { get; set; }
        public string cinvdefine5 { get; set; }
        public string cinvdefine6 { get; set; }
        public string cinvdefine7 { get; set; }
        public string cinvdefine8 { get; set; }
        public string cinvdefine9 { get; set; }
        public string cinvdefine10 { get; set; }
        public Nullable<int> cinvdefine11 { get; set; }
        public Nullable<int> cinvdefine12 { get; set; }
        public Nullable<double> cinvdefine13 { get; set; }
        public Nullable<double> cinvdefine14 { get; set; }
        public Nullable<System.DateTime> cinvdefine15 { get; set; }
        public Nullable<System.DateTime> cinvdefine16 { get; set; }
        public string 主计量单位编码 { get; set; }
        public string 主计量单位 { get; set; }
        public string 辅计量单位 { get; set; }
        public string 币种 { get; set; }
        public string 换算率 { get; set; }
        public string iGroupType { get; set; }
        public Nullable<decimal> 数量 { get; set; }
        public Nullable<decimal> 件数 { get; set; }
        public Nullable<decimal> 原币金额 { get; set; }
        public Nullable<decimal> 本币金额 { get; set; }
        public Nullable<decimal> 原币无税金额 { get; set; }
        public Nullable<decimal> 本币无税金额 { get; set; }
    }
}
