//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDefDataEngineConfig
    {
        public System.Guid guid { get; set; }
        public string cTableName { get; set; }
        public string BD_EntitiesMetaID { get; set; }
        public string BD_BusinessObjectsMetaID { get; set; }
        public string BD_EntitiesName { get; set; }
        public string BD_BusinessObjectsName { get; set; }
        public string BD_BusinessObjectQueryData { get; set; }
        public string BD_BusinessObjectGetData { get; set; }
        public Nullable<bool> bExist { get; set; }
    }
}
