//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTU_MaMessage
    {
        public System.Guid uidID { get; set; }
        public string cToUserID { get; set; }
        public string cAppID { get; set; }
        public string cAccount { get; set; }
        public string cAccountName { get; set; }
        public string cMsgTitle { get; set; }
        public Nullable<int> iMsgType { get; set; }
        public string cTaskID { get; set; }
        public string cFromUserID { get; set; }
        public Nullable<System.DateTime> dSendTime { get; set; }
        public Nullable<int> iUnreadCount { get; set; }
    }
}
