//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v3x_ws_register
    {
        public long id { get; set; }
        public Nullable<byte> app_type { get; set; }
        public Nullable<long> user_id { get; set; }
        public string login_id { get; set; }
        public string password { get; set; }
        public string ws_url { get; set; }
        public Nullable<byte> status { get; set; }
        public string remark { get; set; }
    }
}
