//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v3x_document_signature
    {
        public long id { get; set; }
        public string record_id { get; set; }
        public string markname { get; set; }
        public string username { get; set; }
        public System.DateTime sign_date { get; set; }
        public string hostname { get; set; }
        public string markguid { get; set; }
    }
}
