//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v3x_biz_config_item
    {
        public long id { get; set; }
        public Nullable<long> biz_config_id { get; set; }
        public Nullable<byte> source_type { get; set; }
        public Nullable<long> source_id { get; set; }
        public string name { get; set; }
        public Nullable<long> menu_id { get; set; }
        public Nullable<int> sort_id { get; set; }
        public Nullable<long> form_appmain_id { get; set; }
        public Nullable<byte> flow_menu_type { get; set; }
    }
}
