//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class variationbilltype
    {
        public int BillTypeId { get; set; }
        public string BillTypeName { get; set; }
        public Nullable<bool> Selected { get; set; }
        public string Caption { get; set; }
        public string cMenuId { get; set; }
        public string cProductId { get; set; }
        public short iVoucherType { get; set; }
        public string cComName { get; set; }
        public string cFunName { get; set; }
        public string cardNum { get; set; }
        public string sXMLParam { get; set; }
        public int iOrder { get; set; }
    }
}
