//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucheritems_prn_base
    {
        public int AutoId { get; set; }
        public int VT_ID { get; set; }
        public string CardNum { get; set; }
        public string CardItemNum { get; set; }
        public Nullable<bool> CanNotSelect { get; set; }
        public Nullable<bool> ShowIt { get; set; }
        public Nullable<short> LinkIt { get; set; }
        public string LinkTbl { get; set; }
        public string LinkField { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public Nullable<short> FieldType { get; set; }
        public Nullable<short> ReferType { get; set; }
        public string ReferTable { get; set; }
        public string CardSection { get; set; }
        public Nullable<bool> CanModify { get; set; }
        public Nullable<int> MaxLength { get; set; }
        public Nullable<int> MaxShowLen { get; set; }
        public Nullable<int> NumPoint { get; set; }
        public Nullable<bool> IsNull { get; set; }
        public Nullable<int> CanDelete { get; set; }
        public string UserCheck { get; set; }
        public string UserPrompt { get; set; }
        public string FormatChar { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public Nullable<short> NeedSum { get; set; }
        public Nullable<bool> CalcField { get; set; }
        public Nullable<short> AliasNum { get; set; }
        public Nullable<int> isSelfDef { get; set; }
        public Nullable<int> COX { get; set; }
        public Nullable<int> COY { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> TabIndex { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<bool> IsFixedLenght { get; set; }
        public string FormatData { get; set; }
        public Nullable<bool> PrintCaption { get; set; }
        public Nullable<bool> PrintUpcase { get; set; }
        public string PrintInterval { get; set; }
        public int DataSource { get; set; }
        public int EnterType { get; set; }
        public string DataRule { get; set; }
        public bool ValidityCheck { get; set; }
        public bool ReserveSegTitlePos { get; set; }
        public bool BuildArchives { get; set; }
        public Nullable<int> nBorder { get; set; }
        public string ReferReturnField { get; set; }
        public string cmemo { get; set; }
        public byte[] pubufts { get; set; }
        public string EnumType { get; set; }
        public Nullable<bool> IsEnum { get; set; }
        public string EnumTypeString { get; set; }
        public Nullable<bool> bZeroAllowable { get; set; }
        public Nullable<short> iFlags { get; set; }
        public string vValueDefault { get; set; }
        public string refObject { get; set; }
        public string AutoFillRule { get; set; }
        public int Catalog { get; set; }
        public Nullable<bool> bsplit { get; set; }
        public Nullable<bool> IsJoinQuery { get; set; }
        public Nullable<int> bExtended { get; set; }
        public Nullable<byte> bIMFld { get; set; }
        public Nullable<bool> bAutoComplete { get; set; }
        public Nullable<bool> bColShow { get; set; }
    }
}
