//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VQD_QuerySchemaDetail
    {
        public System.Guid SchemaID { get; set; }
        public int RowID { get; set; }
        public string LeftBracket { get; set; }
        public string RowKey { get; set; }
        public string RowComparor { get; set; }
        public string RowValue { get; set; }
        public string RightBracket { get; set; }
        public string RowLogical { get; set; }
        public Nullable<bool> bSystem { get; set; }
        public Nullable<int> PID { get; set; }
        public string Comparors { get; set; }
        public Nullable<bool> bCanChangeKey { get; set; }
        public Nullable<bool> bCanChangeValue { get; set; }
        public Nullable<bool> bCanChangeComparor { get; set; }
        public Nullable<bool> bCanChangeAll { get; set; }
        public string RowCode { get; set; }
        public string RowValue2 { get; set; }
    }
}
