//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VQD_Dictionary
    {
        public string TableName { get; set; }
        public string ColName { get; set; }
        public Nullable<int> Precision1 { get; set; }
        public string SaveType { get; set; }
        public Nullable<bool> bNull { get; set; }
        public Nullable<int> ColWidth { get; set; }
        public byte[] ts { get; set; }
        public Nullable<bool> bOnlyOne { get; set; }
        public Nullable<byte> bSystem { get; set; }
        public Nullable<bool> bCanFilter { get; set; }
        public Nullable<bool> bCanBind { get; set; }
        public Nullable<bool> bShowInTemplate { get; set; }
        public Nullable<bool> bFilter { get; set; }
    }
}
