//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WA_BankTop
    {
        public string cGZGradeNum { get; set; }
        public int i_id { get; set; }
        public Nullable<byte> iLocate { get; set; }
        public Nullable<bool> bSum { get; set; }
        public string cContent { get; set; }
        public string cTable { get; set; }
        public string cRecord { get; set; }
        public int id { get; set; }
    }
}
