//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WA_Bank
    {
        public string cGZGradeNum { get; set; }
        public int i_id { get; set; }
        public string cBank_Name { get; set; }
        public string cBankFileName { get; set; }
        public string cBankFilePath { get; set; }
        public Nullable<bool> bBankUse { get; set; }
        public Nullable<short> iBW { get; set; }
    }
}
