//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WA_OutPeriod
    {
        public string cGZGradeNum { get; set; }
        public int iPeriod { get; set; }
        public Nullable<bool> bOutP1 { get; set; }
        public Nullable<bool> bOutP2 { get; set; }
        public Nullable<bool> bOutP3 { get; set; }
        public Nullable<bool> bOutP4 { get; set; }
        public Nullable<bool> bOutP5 { get; set; }
        public Nullable<bool> bOutP6 { get; set; }
        public Nullable<bool> bOutP7 { get; set; }
        public Nullable<bool> bOutP8 { get; set; }
        public Nullable<bool> bOutP9 { get; set; }
        public Nullable<bool> bOutP10 { get; set; }
        public Nullable<bool> bOutP11 { get; set; }
        public Nullable<bool> bOutP12 { get; set; }
        public Nullable<double> fOutP1 { get; set; }
        public Nullable<double> fOutP2 { get; set; }
        public Nullable<double> fOutP3 { get; set; }
        public Nullable<double> fOutP4 { get; set; }
        public Nullable<double> fOutP5 { get; set; }
        public Nullable<double> fOutP6 { get; set; }
        public Nullable<double> fOutP7 { get; set; }
        public Nullable<double> fOutP8 { get; set; }
        public Nullable<double> fOutP9 { get; set; }
        public Nullable<double> fOutP10 { get; set; }
        public Nullable<double> fOutP11 { get; set; }
        public Nullable<double> fOutP12 { get; set; }
        public short iYear { get; set; }
    }
}
