//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WA_psn
    {
        public string cGZGradeNum { get; set; }
        public string cPsn_Num { get; set; }
        public string cPsn_Name { get; set; }
        public string cLkxcode { get; set; }
        public string cDept_num { get; set; }
        public int iPsnGrd_id { get; set; }
        public string cAccount { get; set; }
        public Nullable<System.DateTime> dInTime { get; set; }
        public Nullable<System.DateTime> dGZTFTime { get; set; }
        public string cMemo { get; set; }
        public bool bForeign { get; set; }
        public Nullable<bool> bTaxBz { get; set; }
        public Nullable<bool> bPRCal { get; set; }
        public Nullable<int> i_id { get; set; }
        public Nullable<byte> iPsnMove { get; set; }
        public string M1 { get; set; }
        public string M2 { get; set; }
        public string M3 { get; set; }
        public string M4 { get; set; }
        public string M5 { get; set; }
        public string M6 { get; set; }
        public string M7 { get; set; }
        public string M8 { get; set; }
        public string M9 { get; set; }
        public string M10 { get; set; }
        public string M11 { get; set; }
        public string M12 { get; set; }
        public string M13 { get; set; }
        public string M14 { get; set; }
        public string M15 { get; set; }
        public string M16 { get; set; }
        public string M17 { get; set; }
        public string M18 { get; set; }
        public string M19 { get; set; }
        public string M20 { get; set; }
        public string M21 { get; set; }
        public string M22 { get; set; }
        public string M23 { get; set; }
        public string M24 { get; set; }
        public string M25 { get; set; }
        public string M26 { get; set; }
        public string M27 { get; set; }
        public string M28 { get; set; }
        public string M29 { get; set; }
        public string M30 { get; set; }
        public string M31 { get; set; }
        public string M32 { get; set; }
        public string M33 { get; set; }
        public string M34 { get; set; }
        public string M35 { get; set; }
        public string M36 { get; set; }
        public string M37 { get; set; }
        public string M38 { get; set; }
        public string M39 { get; set; }
        public string M40 { get; set; }
        public string M41 { get; set; }
        public string M42 { get; set; }
        public string M43 { get; set; }
        public string M44 { get; set; }
        public string M45 { get; set; }
        public string M46 { get; set; }
        public string M47 { get; set; }
        public string M48 { get; set; }
        public string M49 { get; set; }
        public string M50 { get; set; }
        public string M51 { get; set; }
        public string M52 { get; set; }
        public string M53 { get; set; }
        public string M54 { get; set; }
        public string M55 { get; set; }
        public string M56 { get; set; }
        public string M57 { get; set; }
        public string M58 { get; set; }
        public string M59 { get; set; }
        public string M60 { get; set; }
        public string M61 { get; set; }
        public string M62 { get; set; }
        public string M63 { get; set; }
        public string M64 { get; set; }
        public string M65 { get; set; }
        public string M66 { get; set; }
        public string M67 { get; set; }
        public string M68 { get; set; }
        public string M69 { get; set; }
        public string M70 { get; set; }
        public string M71 { get; set; }
        public string M72 { get; set; }
        public string M73 { get; set; }
        public string M74 { get; set; }
        public string M75 { get; set; }
        public string M76 { get; set; }
        public string M77 { get; set; }
        public string M78 { get; set; }
        public string M79 { get; set; }
        public string M80 { get; set; }
        public string M81 { get; set; }
        public string M82 { get; set; }
        public string M83 { get; set; }
        public string M84 { get; set; }
        public string M85 { get; set; }
        public string M86 { get; set; }
        public string M87 { get; set; }
        public string M88 { get; set; }
        public string M89 { get; set; }
        public string M90 { get; set; }
        public string M91 { get; set; }
        public string M92 { get; set; }
        public string M93 { get; set; }
        public string M94 { get; set; }
        public string M95 { get; set; }
        public string M96 { get; set; }
        public string M97 { get; set; }
        public string M98 { get; set; }
        public string M99 { get; set; }
        public string M100 { get; set; }
        public short iYear { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
