//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WA_SDS_Set
    {
        public short iSL_id { get; set; }
        public Nullable<decimal> yMin_level { get; set; }
        public Nullable<decimal> yMax_level { get; set; }
        public Nullable<double> iSL { get; set; }
        public Nullable<decimal> ySSKCS { get; set; }
        public short sType { get; set; }
        public string cVersion { get; set; }
        public bool blastflag { get; set; }
    }
}
