//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFAudit
    {
        public System.Guid id { get; set; }
        public string TaskId { get; set; }
        public string TaskName { get; set; }
        public string VoucherId { get; set; }
        public string VoucherType { get; set; }
        public string VoucherCode { get; set; }
        public string BizObjectId { get; set; }
        public string BizEventId { get; set; }
        public string ProcessId { get; set; }
        public string InstanceId { get; set; }
        public string ActivatyId { get; set; }
        public string Opinion { get; set; }
        public string Attachment { get; set; }
        public string Signature { get; set; }
        public string FromUserId { get; set; }
        public string FromUserName { get; set; }
        public int Action { get; set; }
        public string AccountId { get; set; }
        public Nullable<short> AccountYear { get; set; }
        public string OperatorId { get; set; }
        public string OperatorName { get; set; }
        public System.DateTime OperationDate { get; set; }
        public string MessageId { get; set; }
        public string OriginalID { get; set; }
        public string OriginalName { get; set; }
    }
}
