//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTaskItem
    {
        public System.Guid Taskitemid { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ScenarioID { get; set; }
        public string Operatorid { get; set; }
        public string TaskXml { get; set; }
        public bool Issys { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<bool> IsShowFlag { get; set; }
    }
}
